### ISSUE TITLE
SwizzlingError - Original method not called

### ISSUE THREAD

**Issue by PhilippeWeidmann** [getsentry/sentry-cocoa#1368] opened 2021-10-11 07:38 UTC
### Environment

Sentry self hosted

Sentry iOS 7.4.3 - iOS 12

### Steps to Reproduce

1. Start Sentry 
2. Navigate to some other view controller

### Expected Result

Not crash.

### Actual Result

The app crashed.
```
Terminating app due to uncaught exception 'SwizzlingError', reason: 'Original method not called'
*** First throw call stack:
(0x18170504c 0x19a374f54 0x1045a7d9c 0x183cbf434 0x183dee12c 0x10549028c 0x105493544 0x105493070 0x105494460 0x105499ec8 0x105499ce8 0x1054942e0 0x105493fb0 0x10549633c 0x105496220 0x1054961a0 0x1044af358 0x183fdb0a4 0x104562454 0x184106dfc 0x183e823a4 0x183f1ef48 0x1841b1b18 0x183c850d0 0x183cb6ad8 0x183e663f4 0x183c89c84 0x183c7ea70 0x184ac085c 0x1842efafc 0x184969104 0x1849686f4 0x181727020 0x181737ce0 0x181671fe8 0x1816777f4 0x18168b3b8 0x19d6bb38c 0x18402bb60 0x183daa8b8 0x1044faddc 0x104fe1a24)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'SwizzlingError', reason: 'Original method not called'
terminating with uncaught exception of type NSException
```
`SentryUIViewControllerSwizziling`:
<img width="705" alt="Capture d’écran 2021-10-11 à 09 33 59" src="https://user-images.githubusercontent.com/5843044/136750350-1a273372-9603-4871-8869-c6370c35e096.png">

**Comment by marandaneto** [comment] 2021-10-11 08:56
@PhilippeWeidmann thanks for raising it, we'll be looking into it, do you have any steps to reproduce it? thanks

**Comment by brustolin** [comment] 2021-10-11 16:45
Hello @PhilippeWeidmann do you have the stack track to share with us? Thanks!

**Comment by vincentisambart** [comment] 2021-10-13 02:17
In the closure you pass to `SentrySDK.start`, adding `options.enableAutoPerformanceTracking = false` seems to disable the swizzling that causes this problem.

**Comment by philipphofmann** [comment] 2021-10-14 10:04
We identified an issue with our Swizzling code and it is going to be fixed with https://github.com/getsentry/sentry-cocoa/pull/1383. The problem was that when an error occurred in `viewDidAppear` we threw `'SwizzlingError', reason: 'Original method not called'` hiding the actual error happening in the `viewDidAppear`. This issue should be fixed in the next release, and the actual underlying errors should pop up.

**Closed as completed** 2021-10-14 10:04 UTC
Labels: Component: Performance
