### ISSUE TITLE
Test Apple Major OS releases 2024

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cocoa#4300] opened 2024-08-26 09:24 UTC
### Description

iOS 18, tvOS 18, watchOS 11, macOS 15 are about to GA in September 2024. We should test whether our SDK works appropriately on these new OS versions.

# Other tasks

```[tasklist]
### Must-have - pre release
- [x] Test plan manual iOS+macOS/MacCatalyst
- [x] Test plan manual tvOS
- [x] Test plan manual watchOS
```

```[tasklist]
### Must-have - post release
- [ ] Test plan check with customer data
```

```[tasklist]
### Optional / TBD
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3105
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3719
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3103
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3100
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3104
```

# Test plan manual test 

| Feature                         | iOS | macOS | tvOS | MacCatalyst |
|---------------------------------|-----|-------|------|-------------|
| Crashes with symbolication      | ✅   | ✅     |      |  ✅           |
| Error events with symbolication | ✅   | ✅     |      |   ✅          |
| OOMs                            | ✅   |  🚫   |      |     🚫      |
| App hangs                       | ✅   |  🚫   |      |    ❓       |
| Release health                  | ✅   |   ✅   |      | ✅             | 
| View hierarchy                  | ✅   |  🚫   |      |    ✅         |
| Screenshots                     | ✅   |  🚫   |      |  ✅           |
| Auto-generated breadcrumbs      | ✅   |   ✅    |      |  ✅           |
| Attachments                     | ✅   | ✅     |      |  ✅           |
| App start                       | ✅   |  🚫   |  ☑️  |   ✅          |
| Slow & frozen frames            | ✅   |  🚫   |      |   ✅          |
| UIViewController tracking       | ✅   |  🚫   |      |    ✅         |
| TTID/TTFD                       | ✅   |  🚫   |      |   ✅          |
| Network tracking                | ✅   |  🚫   |      |  ✅           |
| File I/O tracking               | ✅   |  🚫   |      |  ✅           |
| Core data tracking              | ✅   |  🚫   |  ☑️  |   ✅          |
| User interaction tracking       | ✅   |  🚫   |      |  ✅           |
| Swift UI tracking               | ✅   | ✅     |      |  ✅           |
| MetricKit                       | ✅   | ❓  |  ☑️  |  ✅           |
| Profiling                       | ❓ |  🚫   |  ☑️  |   ✅          |

🚫 = not available
☑️ = works on another platform. Not needed to put in the effort to test on this platform, because we are going to validate the feature with customer data.
✅ = tested successfully

# Test plan check with customer data

Check features with customer data once iOS 18 is released. We only check iOS with customer data as things breaking there would have the most significant negative impact because we have, by far, the most projects on iOS. For the other platforms, the manual test above is sufficient. 

| Feature                         | iOS | 
|---------------------------------|-----|
| Crashes with symbolication      |     |
| Error events with symbolication |     |
| OOMs                            |     |
| App hangs                       |     |
| Release health                  |     |
| View hierarchy                  |     |
| Screenshots                     |     |
| Auto-generated breadcrumbs      |     |
| Attachments                     |     |
| App start                       |     |
| Slow & frozen frames            |     |
| UIViewController tracking       |     |
| TTID/TTFD                       |     |
| Network tracking                |     |
| File I/O tracking               |     |
| Core data tracking              |     |
| User interaction tracking       |     |
| Swift UI tracking               |     |
| MetricKit                       |     |
| Profiling                       |     |   

--- 
Similar to https://github.com/getsentry/sentry-cocoa/issues/3129

**Comment by denrase** [comment] 2024-09-04 12:57
# iOS Setup

iPhone 13 Pro - iOS 18.0 (22A5350a) Public Beta
Sentry 8.36.0 - TestFlight & Sentry 8.35.1 Debug build with Xcode 16.0 Beta 6

# Manual Tests

## Crashes with symbolication ✅

- Works as expected
  - https://sentry-sdks.sentry.io/issues/3607568922/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=4

## Error events with symbolication ✅

- Works with "Capture error"
    - https://sentry-sdks.sentry.io/issues/5485500008/events/9eeeff026c74498bb966c919d6925094/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=next-event&statsPeriod=1h&stream_index=0
- Works with "Capture NSException"
    - https://sentry-sdks.sentry.io/issues/2862440042/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

## OOMs ✅
 
- Works as expected
  - https://sentry-sdks.sentry.io/issues/3808632822/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=1

## App hangs ✅

- Works as expected
  - https://sentry-sdks.sentry.io/issues/5795592786/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

Release Health ✅

- Works as expected
  - https://sentry-sdks.sentry.io/releases/io.sentry.sample.iOS-Swift%408.36.0%2B1716/?project=5428557

## View hierarchy ✅ / ❓

- Works as expected in error
  - https://sentry-sdks.sentry.io/issues/2862440042/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0
- No view hierarchy in crash, is this expected behaviour? ❓
  - https://sentry-sdks.sentry.io/issues/3607568922/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=4

<img src="https://github.com/user-attachments/assets/a7bc4418-fe46-45e7-8bd2-29894413de03" width="700">

## Auto-generated breadcrumbs ✅

- Works as expected
  - https://sentry-sdks.sentry.io/issues/3607568922/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=4

## Attachments ✅

- All issues have attachments added though their initial scope setup
 - tongario.jpg https://sentry-sdks.sentry.io/api/0/projects/sentry-sdks/sentry-cocoa/events/edead652a4b442cdae42ff2db727be5e/attachments/11464150437/?download=1
 - log.txt https://sentry-sdks.sentry.io/api/0/projects/sentry-sdks/sentry-cocoa/events/edead652a4b442cdae42ff2db727be5e/attachments/11464150436/?download=1

## App start ✅

- App start metrics are available on sentry.io
  - https://sentry-sdks.sentry.io/insights/mobile/app-startup/?project=5428557&statsPeriod=1h
  - https://sentry-sdks.sentry.io/performance/trace/f931ab2830e54ee6b3e241110d5349b8/?app_start_type=cold&eventId=72667ba90788435b92639c41d0b52c27&groupId=7b81f5a5b2c6aa09&node=span-a4ab8f10f7f04876&node=txn-72667ba90788435b92639c41d0b52c27&primaryRelease=io.sentry.sample.iOS-Swift%408.35.1%2B1&project=5428557&secondaryRelease=io.sentry.sample.iOS-Swift%408.36.0%2B1716&source=app_starts_module&spanDescription=loadView&spanGroup=7b81f5a5b2c6aa09&spanOp=ui.load&statsPeriod=1h&timestamp=1725442353&transaction=ErrorsViewController
 
<img src="https://github.com/user-attachments/assets/009d4447-562d-4d66-9072-dec130c8b5e0" width="700">

## Slow & frozen frames ✅ 

- Pressed "Cause frozen frames"
- Can see "Most Frozen Frames" in dashboard in the `Extra` screen

<img src="https://github.com/user-attachments/assets/6a6b155e-4f6e-4b09-b4c3-293fca785212" width="700">

- Can see frozen frames in trace view

<img src="https://github.com/user-attachments/assets/5e089626-4cee-4edf-8f27-d0e25ec4f3dd" width="700">

## UIViewController tracking ✅

- Can see view different opened controllers in breadcrumbs of error message (Ui Lifecycle)

## TTID/TTFD ✅ 

- Works as expected

<img src="https://github.com/user-attachments/assets/3d10f93c-678a-4b6c-ad18-2e3b0ff670e1" width="700">

## Network tracking ✅ 

- Can see network breadcrumbs (HTTP)

## Core data tracking ✅ / ❓
  - Can see some file spans in 'traces' view
  - Are there supposed to be spans for record creation/deletion? ❓

<img src="https://github.com/user-attachments/assets/be4509b2-ce32-40d2-976d-a7f7a28d9aac" width="700">

## User interaction tracking ✅

 - Issues have breadcrumbs of button presses and session replay
   - https://sentry-sdks.sentry.io/issues/2862440042/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

<img src="https://github.com/user-attachments/assets/723d09aa-bdc7-4d48-a7cd-a1f2c076b46b" width="700">

## Swift UI tracking ❓

- Could not check, as `captureMessage` crashes in `iOS13-Swift` target

<img src="https://github.com/user-attachments/assets/69f10800-9977-48b5-9185-40149f5b325a" width="700">

- Looks like we are using a `captureMessage` unrecognised selector

## MetricKit ❓
 - MetricKit is added as an integration.
 - Tried to provoke data from metricKit with app hanging, but did not get any `mx_` data in AppHang events

## Profiling ❌

- Could not check, as the sample app crashes when trying to view profile data.
    - https://sentry-sdks.sentry.io/issues/5795748619/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0
    
<img src="https://github.com/user-attachments/assets/cf5e009d-c707-442a-a385-07c3c9111209" width="700">

- ProfilesViewController shown with count 3, but there is no Flamegraph/Call Tree
  - https://sentry-sdks.sentry.io/performance/summary/profiles/?project=5428557&statsPeriod=1h&transaction=ProfilingViewController

<img src="https://github.com/user-attachments/assets/8f7bac4f-0a9f-4ebb-8491-c608a753db7c" width="700">

# Other

- Device orientation seems to be incorrect
 - https://sentry-sdks.sentry.io/issues/2862440042/events/d8050b41d5864f05af59d974be6ec7b4/?project=5428557&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=next-event&statsPeriod=1h&stream_index=0

<img src="https://github.com/user-attachments/assets/0e160ae0-5805-472d-8063-dcb29ed5f91f" width="700">

**Comment by denrase** [comment] 2024-09-04 13:21
# MacOS

## MacOS (Catalyst) ❌

Cannot run Sample application because Sentry is not found.

![Image](https://github.com/user-attachments/assets/cb5612a0-b3cf-494f-90d3-a4a7471476d5)

**Comment by denrase** [comment] 2024-09-05 13:34
# watchOS 

## Setup

watchOS 11 (22R5348a)
Apple Watch Ultra 2 
Version 16.0 beta 6 (16A5230g)
Runing in debug mode.

## Results

| Test | Result  | Notes |
| :---:   | :---: | :---: |
| captureMessage | ✅ | --  |
| captureError | ✅ | --  |
| captureException | ❌ | Not showing up on sentry.io. According to logs, envelope sent successfully.    |
| crash | ❌ | Not showing up on sentry.io. According to logs, envelope sent successfully.   |
| auto breadcrumbs | ✅ | --  |
| attachments | ✅ | --  |

![Image](https://github.com/user-attachments/assets/0460b1a8-f592-49fe-aab7-18bd6e018551)

@kahest Could not get `captureException` and `SentrySDK.crash()` to show up on `sentry.io` .

**Comment by denrase** [comment] 2024-09-05 14:03
# macOS 

## Setup

macOS Sequia 15.0 Beta (24A5331b)
MacBook Pro 15-inch 2019 (Intel)

Xcode Version 16.0 beta 6 (16A5230g)
Runing in debug mode.

## Results

| Test | Result  | Notes |
| :---:   | :---: | :---: |
| captureMessage | ✅ | -- |
| captureError | ✅ | --  |
| captureException | ✅ | -- |
| crash | ✅ | -- |
| auto breadcrumbs | ✅ | -- |
| attachments | ✅ | --  |

![Image](https://github.com/user-attachments/assets/0460b1a8-f592-49fe-aab7-18bd6e018551)

@kahest Could not get `captureException` and `SentrySDK.crash()` to show up on `sentry.io` .

**Comment by denrase** [comment] 2024-09-05 15:26
# macOS 

## Setup

macOS Sequia 15.0 Beta (24A5331b)
MacBook Pro 15-inch 2019 (Intel)

Xcode Version 16.0 beta 6 (16A5230g)
Runing in debug mode.

## Results

| Feature | Status | Notes |
| :---: | :---: | :---: |
| Crashes with symbolication      | | -- |
| Error events with symbolication | | -- |
| App hangs                       | | -- |
| Release health                  | | -- |
| View hierarchy                  | | -- |
| Screenshots                     | | -- |
| Auto-generated breadcrumbs      | | -- |
| Attachments                     | | -- |
| App start                       | | -- |
| Slow & frozen frames            | | -- |
| UIViewController tracking       | | -- |
| TTID/TTFD                       | | -- |
| Network tracking                | | -- |
| File I/O tracking               | | -- |
| Core data tracking              | | -- |
| User interaction tracking       | | -- |
| Swift UI tracking               | | -- |
| MetricKit                       | | -- |
| Profiling                       | | -- |

**Comment by philipphofmann** [comment] 2024-10-02 12:08
All major OS versions have already been released. If there would be major issues, people would have reported these already. As almost everything was tested we can close this.

**Closed by philipphofmann** 2024-10-02 12:08 UTC
Labels: Platform: Cocoa
