### ISSUE TITLE
"Implicit conversion loses integer precision" warning

### ISSUE THREAD

**Issue by benguild** [getsentry/sentry-cocoa#356] opened 2019-12-11 22:47 UTC
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_sentry-cocoa installed with:_
- [X] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
4.4.1 or 4.4.3

---
I have following issue:

<img width="266" alt="Screen Shot 2019-12-11 at 17 45 38" src="https://user-images.githubusercontent.com/1185659/70667151-3458b400-1c3e-11ea-9614-33bfb4e79060.png">

**Comment by fetzig** [comment] 2019-12-12 18:03
Hi @benguild, can you elaborate on that. The most obvious question that comes to my mind: Why is what seems to be a build warning an issue?

**Comment by benguild** [comment] 2019-12-12 18:27
Why isn’t it an issue? Haha, warnings are warnings that should be fixed 💯 😆

**Comment by benguild** [comment] 2020-01-09 15:19
@fetzig which version fixes this? will update our pod

**Comment by fetzig** [comment] 2020-01-09 16:26
Wontfix

**Comment by benguild** [comment] 2020-01-12 17:27
Why? It seems like it's a quick fix, no?

**Comment by fetzig** [comment] 2020-01-12 22:22
Feel free to send a PR.

**Comment by fetzig** [comment] 2020-01-13 15:23
forgot to put my notes in here. they might help is somebody is considerin to contribute a PR for this:

 * can't reproduce the warning (not when building sentry or a project that uses sentry via cocoapods).  not with 4.4.1 or 4.4.3. most likely a configuration issue.
 * we would need additional error handling. examples: https://stackoverflow.com/questions/10615950/implicit-conversion-loses-integer-precision-long-long-to-nsinteger-aka-in
 * it's not clear where `NSString.unsignedLongLongValue` is used since SentryCrash calls `unsignedLongLongValue` on dict values (NSString, NSInteger,....?).

**Comment by benguild** [comment] 2020-01-20 00:10
> * Can't reproduce the warning (not when building sentry or a project that uses sentry via cocoapods).  not with 4.4.1 or 4.4.3. most likely a configuration issue. Clarification on how to get to this warning would be required.

Have you tried shipping an app? Here's a sample `Podfile`:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'test' do
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.4.3'
end
```

Steps to reproduce in Xcode 11.3 (11C29):
1. Create a project in Xcode ("Single View App" etc.), no source code or configuration changes are necessary the defaults are fine.
2. Run `pod install` with that "Podfile" in the root of the project folder.
3. Open `.xcworkspace` and go to `Product > Archive` in the menus.
4. The warning should appear during the build process.

Are you still not seeing this? The issue should be reopened, not dismissed by default and blaming someone who reports it.

**Comment by fetzig** [comment] 2020-01-21 11:42
The only warning I get is "Pods.xcodeproj Enable Base Internationalization". 

I know the warning, but not form the file you got it from, which makes this interesting. Since this is an Issue about a build warning (get 0 to ~100 build warnings depending on build settings), and I got no repo-steps for some time for this one, I closed the issue. Thanks for sending them now, but sadly they don't work.

The only way to produce this warning (on other files, not `NSString+SentryNSUIntegerValue.m`) is by not adding `inhibit_all_warnings!` (like the Podfile you posted now), **and** turn on implicit conversion warnings in Xcode build settings. Yet that doesn't change the nature of this issue: It might be a trivial fix, but it needs investigation and proper testing.

Since I can't put my efforts towards this in the foreseeable future, it's up to the community (i.e. you) to drive this further.

Until then, I can only suggest anybody who is using cocoapods to use `inhibit_all_warnings!`. This most definitely doesn't fix any warnings but helps developers to focus on their codebase and gives the freedom to execute any (code style, warning, linting, testing) policy for there own codebase without being spammed warnings/errors from third-party code.

**Comment by benguild** [comment] 2020-01-22 07:10
> Until then, I can only suggest anybody who is using cocoapods to use inhibit_all_warnings!.

![image](https://user-images.githubusercontent.com/1185659/72872823-1baed580-3ca3-11ea-8b8a-f278d8b2d7c8.png)

**Comment by mitjans** [comment] 2020-02-19 20:33
Getting the same warning on Xcode 11.3.1, Swift 5.1.3 and Sentry 4.4.1/4.4.3

Will this be fixed in future versions?

**Comment by philipphofmann** [comment] 2020-08-28 08:37
Those warnings were fixed with https://github.com/getsentry/sentry-cocoa/pull/654 and https://github.com/getsentry/sentry-cocoa/pull/633.

**Closed by philipphofmann** 2020-08-28 08:37 UTC
