### ISSUE TITLE
Crash in +[SentryProfiler slicedSamples:transaction:] with 8.3.0

### ISSUE THREAD

**Issue by FelixHerrmann** [getsentry/sentry-cocoa#2797] opened 2023-03-14 17:02 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.3.0

### Steps to Reproduce

1. Integrate Sentry with the following configuration:
```swift
SentrySDK.start { options in
    options.dsn = "1234567890"
    options.tracesSampleRate = 0.2
    options.profilesSampleRate = 1.0
}
```
2. Present view controllers with `UIViewController.present(_:animated:completion:)` or make request with `URLSession` until Sentry crashes

### Expected Result

No crash

### Actual Result

Crash from `viewDidAppear` swizzle:
<img width="2614" alt="Screenshot 2023-03-14 at 17 47 45" src="https://user-images.githubusercontent.com/42500484/225081082-220b8c3f-65c8-4294-be92-2f6274e34dd7.png">

Crash from `URLSessionTask` swizzle:
<img width="2614" alt="Screenshot 2023-03-14 at 17 53 18" src="https://user-images.githubusercontent.com/42500484/225081119-d6287b5f-730d-42fb-bd73-06721cb1cbfe.png">

**Comment by FelixHerrmann** [comment] 2023-03-14 17:09
It is not crashing with 8.2.0, @armcknight I think you made the relevant change [here](https://github.com/getsentry/sentry-cocoa/blob/c85564d7c92adb28f7ee15e2d758b67d7bfd06bd/Sources/Sentry/SentryProfiler.mm#L500) in dbc67d2

**Comment by kahest** [comment] 2023-03-14 17:09
Thanks for reporting! This is most likely a duplicate of https://github.com/getsentry/sentry-cocoa/issues/2797. Closing this issue in favor of the existing one.

**Closed by kahest** 2023-03-14 17:09 UTC
Labels: Type: Bug, Platform: Cocoa, Status: Untriaged

**Comment by FelixHerrmann** [comment] 2023-03-14 17:14
It is indeed, didn't saw it, my bad!
