### ISSUE TITLE
"Validate Podspec" workflow failure

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-cocoa#2245] opened 2022-10-03 13:20 UTC
### Description

```
    xcodebuild: error: Unable to find a destination matching the provided destination specifier:
    		{ id:D7122A47-E6A2-4B0C-A69A-A98948C52CE0 }

    	The requested device could not be found because no available devices matched the request.

    	Available destinations for the "App" scheme:
    		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
    		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Any watchOS Simulator Device }
    		{ platform:watchOS Simulator, id:D7122A47-E6A2-4B0C-A69A-A98948C52CE0, OS:9.0, name:Apple Watch SE (44mm) (2nd generation) }
    		{ platform:watchOS Simulator, id:79155BFD-8150-49E4-8311-90285371C5F9, OS:9.0, name:Apple Watch Series 5 (40mm) }
    		{ platform:watchOS Simulator, id:C8E72EBF-9F36-4D41-B335-C935D14BCAA7, OS:9.0, name:Apple Watch Series 5 (44mm) }
    		{ platform:watchOS Simulator, id:20C4A3FC-DC1B-4DD9-B4F6-27B8701A9895, OS:9.0, name:Apple Watch Series 6 (40mm) }
    		{ platform:watchOS Simulator, id:C65A58F0-131B-4FCA-AC4A-4B0E09C30026, OS:9.0, name:Apple Watch Series 6 (44mm) }
    		{ platform:watchOS Simulator, id:1A2DF0CA-4A21-4489-937F-BB64E38B7EEC, OS:9.0, name:Apple Watch Series 7 (41mm) }
    		{ platform:watchOS Simulator, id:19A9825D-7D30-4A4E-B0B4-2D47B6F8A1DC, OS:9.0, name:Apple Watch Series 7 (45mm) }
    		{ platform:watchOS Simulator, id:D7BC0E2B-0A1D-4844-BBE2-BCC157DFE660, OS:9.0, name:Apple Watch Series 8 (41mm) }
    		{ platform:watchOS Simulator, id:12ABFFA2-F4AC-4A66-8B3D-FA2E4DF12A6B, OS:9.0, name:Apple Watch Series 8 (45mm) }
    		{ platform:watchOS Simulator, id:92D74225-E6B4-42A0-ACA5-D39C1ED75DBE, OS:9.0, name:Apple Watch Ultra (49mm) }
    		{ platform:iOS Simulator, id:12BEEB64-BEC6-4808-9BD6-00CF8EF81372, OS:16.0, name:iPhone 14 }
    		{ platform:iOS Simulator, id:54DC36CA-3C71-462E-B4A9-6E1759B3DA28, OS:16.0, name:iPhone 14 Plus }
    		{ platform:iOS Simulator, id:8136591D-9B9A-4263-B279-3A9914DA39E7, OS:16.0, name:iPhone 14 Pro }
    		{ platform:iOS Simulator, id:D9CBC033-74BB-42BD-9314-E6AC4B89C9DB, OS:16.0, name:iPhone 14 Pro Max }
```

**Comment by kevinrenskers** [comment] 2022-10-03 13:39
I get the same when running the test locally: `pod lib lint --verbose` (on the master branch). And found this issue: https://github.com/CocoaPods/CocoaPods/issues/11558.

I think we might need to disable this workflow step for now, or we ignore this error?

**Comment by philipphofmann** [comment] 2022-10-04 14:55
Duplicate of https://github.com/getsentry/sentry-cocoa/issues/2254

**Closed by philipphofmann** 2022-10-04 14:55 UTC
Labels: Status: Backlog, Platform: Cocoa
