### ISSUE TITLE
iOS issue reported for "App Hanging" but it's just the app going to the background

### ISSUE THREAD

**Issue by acoutts** [getsentry/sentry-cocoa#2803] opened 2023-02-14 12:48 UTC
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel beta, 3.7.0-1.5.pre, on macOS 13.2 22D49 darwin-arm64, locale en-US)
    • Flutter version 3.7.0-1.5.pre on channel beta at /Users/andrew.coutts/Projects/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 099b3f4bf1 (3 weeks ago), 2023-01-20 18:35:12 -0800
    • Engine revision 45c5586f2a
    • Dart version 2.19.0 (build 2.19.0-444.6.beta)
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/andrew.coutts/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] VS Code (version 1.76.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • V2135 (mobile)             • 13755444730009Q                      • android-arm64  • Android 11 (API 30)
    • iPhone 14 Pro Max (mobile) • 3339E92F-270A-478D-B9E1-B5C143E3B6A4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:

I'm getting a lot of reports like this saying the app is hanging but I don't think actually is hanging, it's just the app going to the background and being cleaned up by the OS.

<img width="1090" alt="Screenshot 2023-02-14 at 7 45 41 AM" src="https://user-images.githubusercontent.com/9597207/218742646-794614e2-522b-4a90-b5d9-9401b919b6b9.png">

**Steps to reproduce:**
Unknown, came in via sentry.

**Actual result:**
Seeing false issues.

**Expected result:**
Should only report hangs when it actually hangs

**Comment by marandaneto** [comment] 2023-03-16 07:33
Transfering to Cocoa since it's not a Flutter-specific issue.

**Comment by cctv1005s** [comment] 2023-06-09 07:44
any updates?

**Comment by brustolin** [comment] 2023-06-12 09:20
Unfortunately no @cctv1005s.
I could not reproduce this to find the problem in Sentry SDK.

**Comment by cctv1005s** [comment] 2023-06-27 08:01
@brustolin  NP! The sentry sdk we're using is facing the same problem. I think the reason is the mechanism to keep the background active is completely different between iOS and Android, and the app will be hung quickly when there are still tasks left to be performed after entering the background.

**Comment by philipphofmann** [comment] 2024-01-03 13:02
Sorry, we couldn't reproduce this issue, it could also be that it's already solved. Therefore, we close it but feel free to reopen it with a repro.

**Closed by philipphofmann** 2024-01-03 13:02 UTC
Labels: Type: Enhancement, Platform: Cocoa, Waiting for: Community
