### ISSUE TITLE
73 warnings when installed via Carthage

### ISSUE THREAD

**Issue by mxcl** [getsentry/sentry-cocoa#213] opened 2017-09-25 21:29 UTC
_Platform:_ iOS
_Swift:_ 4.0
_sentry-cocoa installed with:_ Carthage
_Version of sentry-cocoa:_ **3.7.1**

---

With Xcode 9 GM, when installing via Carthage and following your instructions the framework causes 73 issues to generate:

<img width="299" alt="screen shot 2017-09-25 at 5 28 39 pm" src="https://user-images.githubusercontent.com/58962/30831841-fca9bb24-a216-11e7-99d6-5b965dd48a84.png">

I would use CocoaPods, but having switched to Carthage I am getting huge increases in compile times, so it just comes down to not having to ignore warnings.

**Comment by HazAT** [comment] 2017-09-26 07:51
Hey, I will look into this.

**Comment by HazAT** [comment] 2017-09-26 12:19
@mxcl I've just created a basic carthage example and do not have a single build warning.
https://github.com/getsentry/examples/tree/master/cocoa/sentry-ios-carthage
If you run `carthage update` and build the project, do you get any warnings?
Running Xcode 9

**Comment by HazAT** [comment] 2017-09-26 12:27
Btw. also make sure you are using the prebuilt framework from Github releases (which should be the default when using Carthage)

**Comment by mxcl** [comment] 2017-09-26 14:30
I see, well I guess not due to this Carthage error:

```
*** Skipped installing sentry-cocoa.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
```

Seems to be the latest Carthage:

```
$ carthage version
0.25.0
```

I've been getting these errors for a week. I'll check out their docs.

**Comment by mxcl** [comment] 2017-09-26 15:23
Referencing https://github.com/Carthage/Carthage/issues/2157

**Comment by HazAT** [comment] 2017-09-26 16:45
Right, I was using Carthage `0.24.0`

**Comment by HazAT** [comment] 2017-10-02 07:08
I will close this for now since there shouldn't be any warnings when using the pre-built version from Github.
Otherwise if you want to build it yourself you need to build the project in the `KSCrash` folder since this project has all the necessary header files.
See : https://github.com/getsentry/sentry-cocoa/blob/master/Makefile#L9-L12

**Comment by mxcl** [comment] 2017-10-05 13:15
Carthage fetched the prebuilt binary today, but I still get the warnings.

I'm using the preview build system, in case that matters.

**Comment by danj-stripe** [comment] 2017-10-05 17:19
I'm getting this intermittently. Sometimes a full clean makes them go away.

From what I understand, the public headers folder of Sentry.framework includes all of the KSCrash public headers. The Sentry.h umbrella header file *does not* include the KSCrash headers. This triggers the `-Wincomplete-umbrella` warnings.

Solutions seem to be to remove the KSCrash headers from the public headers directory, add the KSCrash headers to the umbrella header, or turn off the warning.

I'm experimenting with adding `-Wno-incomplete-umbrella` to my build settings, but the fact these warnings aren't 100% reproducible means I'm not positive it's the right change to make.

https://stackoverflow.com/a/45107213/1196205

**Comment by hannseman** [comment] 2017-10-09 08:14
Platform: iOS
Swift: 4.0
Xcode: 9.0
sentry-cocoa installed with: Carthage
Version of sentry-cocoa: 3.8.2

I'm also getting these warnings. Both when using the pre-build version and one built with Carthage. I've tried both the new build system and the old with no difference.

**Comment by mxcl** [comment] 2017-10-31 20:04
This needs reopening.

**Closed** 2017-11-02 12:35 UTC

**Comment by mxcl** [comment] 2017-11-02 13:49
Confirmed: works!

Clearing these warnings also revealed 9 other warnings in my own code I had been overlooking, so much appreciated!

💋

**Comment by HazAT** [comment] 2017-11-02 14:19
Sorry for that fiasco, I am not really sure what caused this in the first place.
But `3.9.1` should resolve.
