### ISSUE TITLE
swizzleURLSessionTask crash: EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x7eab55f60

### ISSUE THREAD

**Issue by MilosStanojcic-TomTom** [getsentry/sentry-cocoa#3341] opened 2023-10-12 12:35 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.11.0

### Steps to Reproduce

Detected on Sentry dashboard. 24 events from 24 users.
EXC_BAD_ACCESS __57+[SentryNetworkTrackingIntegration swizzleURLSessionTask]_block_invoke_2.29
Unhandled count > KERN_INVALID_ADDRESS at 0x7eab55f60.

```
Crashed in non-app
libobjc.A           +0x0032f8   objc_release                                                                                                                Hide 6 more frames
CoreFoundation      +0x039404   -[__NSArrayM removeObjectsInRange:]
[Our App]           +0x6432e8   -[SentryScope addBreadcrumb:] (SentryScope.m:126)
[Our App]           +0x626e10   -[SentryHub addBreadcrumb:] (SentryHub.m:488)
[Our App]           +0x641498   +[SentrySDK addBreadcrumb:] (SentrySDK.m:310)
[Our App]           +0x633778   -[SentryNetworkTracker addBreadcrumbForSessionTask:] (SentryNetworkTracker.m:487)
[Our App]           +0x632684   -[SentryNetworkTracker urlSessionTask:setState:] (SentryNetworkTracker.m:312)
[Our App]           +0x633fa0   __57+[SentryNetworkTrackingIntegration swizzleURLSessionTask]_block_invoke_2.29 (SentryNetworkTrackingIntegration.m:72)     In App
Called from
CFNetwork           +0x02ca38   CFHTTPMessageCopySerializedMessage                                                                                          Hide 15 more frames
CFNetwork           +0x02a7a4   CFHTTPMessageCopySerializedMessage
CFNetwork           +0x02b6bc   CFHTTPMessageCopySerializedMessage
CFNetwork           +0x02b5e8   CFHTTPMessageCopySerializedMessage
CFNetwork           +0x0a51d8   CFURLDownloadStart
CFNetwork           +0x0a251c   CFURLDownloadStart
CFNetwork           +0x0a5100   CFURLDownloadStart
CFNetwork           +0x1a78ac   _CFStreamErrorFromCFError
CFNetwork           +0x0a6db0   CFURLDownloadStart
libdispatch         +0x01324c   _dispatch_block_async_invoke2
libdispatch         +0x0042fc   _dispatch_client_callout
libdispatch         +0x00b890   _dispatch_lane_serial_drain
libdispatch         +0x00c3f4   _dispatch_lane_invoke
libdispatch         +0x017000   _dispatch_root_queue_drain_deferred_wlh
libdispatch         +0x016874   _dispatch_workloop_worker_thread
libsystem_pthread   +0x001960   _pthread_wqthread
```

### Expected Result

No crash

### Actual Result

Crash

**Comment by philipphofmann** [comment] 2023-10-12 13:50
I see a couple of similar crashes in our [internal SDK crash detection project](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+addBreadcrumbForSessionTask&referrer=issue-list&sort=user&statsPeriod=30d). I @MilosStanojcic-TomTom, do you by any chance, have a way to reproduce this?

**Comment by MilosStanojcic-TomTom** [comment] 2023-10-12 17:41
Sadly I don't. It is all from the dashboard and none hands on. All i can do is add more similar stack traces from other similar occurrences.

**Comment by philipphofmann** [comment] 2023-10-13 07:28
Thanks for the update @MilosStanojcic-TomTom.

**Comment by zeqinjie** [comment] 2023-10-22 02:21
@philipphofmann swizzleURLSessionTask crash look like this [issue](https://github.com/getsentry/sentry-dart/issues/1662#issuecomment-1757077628) ?

**Comment by philipphofmann** [comment] 2023-10-23 14:29
Yes, that could be related @zeqinjie. Thanks for the update.

**Comment by JoeFerrucci** [comment] 2024-05-29 19:57
Still an issue today, Sentry iOS SDK v8.24.0

**Comment by philipphofmann** [comment] 2024-05-31 10:11
Thanks for the update @JoeFerrucci.

**Comment by philipphofmann** [comment] 2024-06-03 09:48
I checked some internal SDK crashes and identified two issues that can cause crashes like this. Many crashes happen due to insufficient memory when adding breadcrumbs, either by the SDK trying to increase the size of the breadcrumbs array or when trying to allocate memory for a debug log message. We fix the first issue with https://github.com/getsentry/sentry-cocoa/pull/4029 by using a ring buffer to avoid allocating extra memory when adding breadcrumbs. #4028 fixes the second problem. These two improvements should fix most of these crashes, but I'm not 100% sure. We are going to close this issue after we merged the two PRs. Please reopen if the problem persists in future versions.

**Closed** 2024-06-04 04:21 UTC
Labels: Type: Bug, Platform: Cocoa
