### ISSUE TITLE
Compile error when running UI Tests with fastlane

### ISSUE THREAD

**Issue by palla89** [getsentry/sentry-cocoa#362] opened 2020-01-07 11:24 UTC
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> Swift 5
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually
- [x] SPM

Version of sentry-cocoa:
**4.4.1**

---
I have following issue:

When running UITests from fastlane's snapshot tool, I get the error "no such module 'Sentry'" on the import line

**Steps to reproduce:**
- Write XCode UI Tests, then run fastlane snapshot from command line

**Actual result:**
- Error, can't compile and execute tests. It could be a fastlane issue but with other spm packages I get no error.

**Expected result:**
- It should find the Sentry library and compile it successfully

**Comment by fetzig** [comment] 2020-01-07 13:10
Hi @palla89,

Could you provide some context? Most obviously the fastlane log.

I tried to reproduce this by creating a new ios project in xcode (single view, ios, swift, + ui testing), added sentry-cocoa via SPM and ran the UI tests. => No errors.

also added a ui test target and scheme like needed for fastlane snapshot, but didn't test with fastlane. Worked in xcode well (build, test and run).

Please provide more info.

P.S.: `no such module 'Somemodule'` is sadly a very common error in xcode projects. I had to tackle this multiple times myself in iOS App projects. Mostly that happened in CI/CD pipelines, while the build/test worked perfectly in some environments. Fixes vary from deleting derived data/restart xcode to errors in the build config and last but not least signing issues :(

**Comment by palla89** [comment] 2020-01-07 13:58
Hi!! Thank you for your fast and kind response, amazing!

I'm attaching you a quick log in png just because the readability is much better: 
![Schermata 2020-01-07 alle 14 48 56](https://user-images.githubusercontent.com/12301205/71899867-f11a3400-315c-11ea-9c16-a72345312317.png)

I'll try with verbose mode on so that we could have some more data. 
By the way if I run the tests directly from XCode as you do, it works fine for me too.
I also tried cleaning and reopening XCode but nothing changed, so it seems something regarding CI pipelines as you say.

I'll do some other tests in the next days and report here :) Many thanks again!

**Comment by fetzig** [comment] 2020-01-09 14:38
I am closing this issue since it's not sentry related.

Found a list I created last year with notes about fixing a similar issue. findings there include:
 * `use_frameworks!` in Podfile
 * run `pod update` again to rebuild the workspace
 * use `inherit! :search_paths` in Podfile
 *  disabled "find implicit dependencies" in my scheme build settings. 
 * make sure xcode workspace is used an not the project
 * (unlikely but still) defining the Framework Search Paths to a folder which contains the frameworks in question
 * Be sure that Find implicit Dependencies in Build options in Scheme is on!
 * (unlikely) requirements of the target platform are higher than the app requirements
 * use the legacy build system
 * Pods "Build Settings" > Build Active Architecture Only: No

**Closed by fetzig** 2020-01-09 14:38 UTC
