### ISSUE TITLE
No type named 'terminate_handler' in namespace 'std'

### ISSUE THREAD

**Issue by longlz19** [getsentry/sentry-cocoa#4354] opened 2024-09-20 01:43 UTC
### Platform

iOS

### Environment

Production, Develop, TestFlight

### Installed

CocoaPods

### Version

7.21.0

### Xcode Version

16

### Did it work on previous versions?

xcode 15 is ok.

### Steps to Reproduce

Upgrade xcode 16， build

### Expected Result

build success

### Actual Result

error

**Comment by brustolin** [comment] 2024-09-20 07:54
This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/4050 and was solved in [8.35.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.35.0).

Lets us know if the error persists.

**Closed by brustolin** 2024-09-20 07:54 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
