### ISSUE TITLE
Error message is not included for Swift errors

### ISSUE THREAD

**Issue by sindresorhus** [getsentry/sentry-cocoa#1442] opened 2021-11-03 05:28 UTC
### Environment

How do you use Sentry?

SaaS

Which SDK and version?

Sentry Cocoa 7.5.0

### Steps to Reproduce

For example, I have this error:

```swift
struct UnexpectedNilError: LocalizedError {
	let message: String?
	let file: String
	let line: Int

	init(
		_ message: String?,
		file: String = #fileID,
		line: Int = #line
	) {
		self.message = message
		self.file = file
		self.line = line

		#if canImport(Sentry)
		SentrySDK.capture(error: self)
		#endif
	}

	var errorDescription: String { message }

	var failureReason: String {
		"Unexpected nil encountered at \(file):\(line)"
	}
}
```

If I throw it, it ends up in Sentry as:

<img width="294" alt="Screen Shot 2021-11-03 at 12 20 09" src="https://user-images.githubusercontent.com/170270/140013108-29be0b4f-b59b-47aa-82dd-87d47c980998.png">

Notice how the subtitle is just `Code: 1` and the error message and failure reason are nowhere to be seen in the report details.

Example event: https://sentry.io/organizations/sindresorhus/issues/2765092409/events/aacc22d1335443f18d7453315c076f7a/ (Not sure if you can access it?)

However, if I send an `NSError`, I get the correct details, where I can see a `NSLocalizedDescription` key in the report details.

### Expected Result

I expected to see the error message and failure reason in the report.

### Actual Result

The report is missing key details.

**Comment by philipphofmann** [comment] 2021-11-03 16:21
Thanks, @sindresorhus for opening this issue. We put the description of the NSError into the mechanism in the SentryClient

https://github.com/getsentry/sentry-cocoa/blob/cfe8e2432ed75d9986c832d401bb16d5203e8768/Sources/Sentry/SentryClient.m#L193-L195

It ends up in the JSON of the event, but I don't see it in the Sentry UI.

```JSON
"mechanism": {
  "type": "NSError",
  "description": "iOS_Swift.MyError(errorDescription: \"errorDescription\", failureReason: \"failureReason\", helpAnchor: \"helpAnchor\", recoverySuggestion: \"recoverySuggestion\")",
  "meta": {
    "ns_error": {
      "code": 1,
      "domain": "iOS_Swift.MyError"
    }
  }
```

I will investigate where to put the error message so you can see it, but that needs some further investigation. I will get back to you and can't give you an ETA at the moment.

**Comment by sindresorhus** [comment] 2021-11-24 18:32
.

**Comment by sindresorhus** [comment] 2021-11-24 18:32
Please keep open.

**Comment by lukeredpath** [comment] 2021-11-30 14:39
Is there any plans to make it possible to customise this? Only being able to see "Code: X" makes it very difficult to scan through a long list of errors, I'd much rather it showed the error description if one is available, or both, e.g. "Some important error (code: 1)".

**Comment by philipphofmann** [comment] 2021-11-30 16:38
Thanks for opening #1496 for trying to fix this issue, @lukeredpath. Unfortunately, I think we can't go forward with your PR, and we might have to close it. Here is why.

Before 6.0.0, the SDK used the localized description for the event message. With #750 in [6.0.0](https://github.com/getsentry/sentry-cocoa/releases/tag/6.0.0) we started to use the error domain and code for the event message. We did this because the `localizedDescription` as its name states is localized. So before 6.0.0, you got different issues in Sentry for the same error if the errors were coming from devices with different locales. 

In [6.2.0 ](https://github.com/getsentry/sentry-cocoa/releases/tag/6.2.0), we started grouping by domain and error code, because after some research and validation with some of our customers this seems to be the right thing to do.

Most of our customers told us that they only care about domain and error code. Of course, the `localizedDescription` can help to get more insight to help you fix an issue. The problem with the `localizedDescription` is that it could be English, Chinese, Spanish, German, whatever. Therefore, we don't put it in the event message, because it can be confusing. Instead, we also put it into the user info so see it in the event:

<img width="455" alt="Screen Shot 2021-11-30 at 17 30 28" src="https://user-images.githubusercontent.com/2443292/144087672-210b33aa-ad97-4941-84cc-b68be4d93812.png">

I think instead of changing the error message or the exception value, we should put errorDescription, failureReason, helpAnchor, and recoverySuggestion into user info. Would that work for you @lukeredpath and @sindresorhus?

**Comment by lukeredpath** [comment] 2021-11-30 16:53
@philipphofmann unfortunately what you propose isn't really a solution to the problem at hand. We already inject all of that additional user info data into a context. 

The problem is easily identifying errors from the error/issue list - "Code: x" just isn't that helpful as it requires you to cross-reference with your source code - even worse, unless you explicitly define the error codes for your custom error type, Swift enums that conform to `Error` do not have a deterministic error number.

Your point about using the localized description is valid, so I propose an alternative solution. The Sentry SDK should define its own user info key constant (e.g. `SentryEventValueUserInfoKey`) which users can use to set a custom error description/value in the error's `userInfo` dictionary. If a value is found for that key, it will be used as the event value.

This would be a fairly simple change to my existing PR and would be opt-in too.

**Comment by sindresorhus** [comment] 2021-11-30 17:16
Using `.code` makes sense for actual `NSError`'s coming from the system, but it's meaningless for Swift errors where it's always `1`:

```swift
struct Foo: Error {}
struct Bar: Error {}

print((Foo() as NSError).code)
//=> 1

print((Bar() as NSError).code)
//=> 1
```

**Comment by lukeredpath** [comment] 2021-11-30 17:25
Just experimenting with this a bit more and I wonder if it might make more sense to use an existing Foundation key - `NSDebugDescriptionErrorKey` - instead of a custom key. Semantically this feels like the appropriate thing to use and should also mean any system errors that set this will get a more meaningful (non-localized) description and its easy for users to conform their existing errors to provide this (in Swift, you can conform to `CustomNSError` and return your own `errorUserInfo`).

**Comment by philipphofmann** [comment] 2021-12-01 13:53
Thanks, @lukeredpath, and @sindresorhus, for your input. I think we have a few problems to solve here.

1. Swift enums that conform to Error do not have a deterministic error number. Are you sure about that? If so, you get different issues for different builds, which would be bad.
2. Cross-referencing with your source code is annoying, and we should improve it.

While `NSDebugDescriptionErrorKey` or another foundation key seems like a good solution, it would be nice to come up with a solution that doesn't require extra work for you as a developer. We have to keep in mind that changes in that area of the code can easily mess up our error grouping. 

We have to do some further investigations on how to solve these problems and will get back to you.

**Comment by lukeredpath** [comment] 2021-12-02 08:06
@philipphofmann thanks for the quick reply. I’d love to explore a solution for this. As it is, we are going to integrate my fork into our app and see how it goes. 

The use of a userInfo key wasn’t too difficult to implement but the ergonomics could definitely be better, for example, because userInfo is read only once set, it’s not possible to add this key for all errors in a single beforeSend hook and if you’re using a custom error type in Swift it requires conforming to CustomNSError. 

IIRC the problem with enum error codes arises when you have cases with associated values - the code doesn’t change between builds but it isn’t necessarily in source order which is why we have to define explicit error codes for each case. This might not be the case with a basic enum with an Int raw value.

**Comment by khoi** [comment] 2022-07-07 03:25
Came across this 🧵 after trying to find a way to customize our error reports on Sentry. 

>  enum error codes arises when you have cases with associated values - the code doesn’t change between builds but it isn’t necessarily in source order

This is true and it's really difficult to just look at Sentry dashboard and figure out which is which. 

<img width="446" alt="CleanShot 2022-07-07 at 10 24 16@2x" src="https://user-images.githubusercontent.com/6994441/177684045-4f3e7f16-1ba8-4863-b80b-f24b18aeadb6.png">

**Comment by lukeredpath** [comment] 2022-07-21 11:13
@philipphofmann is there any plans to revisit this, or my PR? To this day we are having to run a fork of the SDK with my changes because if this issue which is a maintenance headache I'd rather not have.

**Comment by RobinDaugherty** [comment] 2022-08-22 16:24
So an `Error`'s description is missing from the Sentry UI. Both localized and debug descriptions are ignored. And still, no plans and no documentation explaining how Sentry expects errors to be reported in a way that provides meaningful information. #1496 fixes the issue, and it implemented the suggestions in this thread, but it was ignored and autoclosed. How does Sentry expect us to interpret this?

**Comment by bruno-garcia** [comment] 2022-08-24 13:53
Agree this should be fixed. We could set `attachStacktrace` to `true` by default or at least always do it if we're capturing an error, so events are grouped by stack trace. But we have to get this information in Sentry's UI for users to be able to understand what's going on

**Comment by lukeredpath** [comment] 2022-09-01 12:55
@philipphofmann how would this affect grouping?

**Comment by philipphofmann** [comment] 2022-09-01 14:38
Ups sorry, my mistake. Your PR #1496 doesn't have an impact on grouping because we group by domain and error code https://github.com/getsentry/sentry-cocoa/blob/a06565c2a78dcda8b12c677761ca83cceb136067/Sources/Sentry/SentryClient.m#L228-L232.

I'm going to reopen #1496

**Closed** 2022-09-07 07:00 UTC
Labels: Type: Enhancement, Status: Needs Investigation, Impact: Large, Effort: Small, Status: Backlog, Platform: Cocoa
