### ISSUE TITLE
SentryOutOfMemoryScopeObserver app crashes

### ISSUE THREAD

**Issue by chaseklingelzen** [getsentry/sentry-cocoa#2555] opened 2022-12-22 15:49 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.31.4

### Steps to Reproduce

We are unable to reproduce the crashes that we are seeing in production at this time. Below you can view the crash logs. When we run the app on a prod scheme through xcode on a physical device, we see no memory issues (i.e. tapping around several features of the app only leads to ~80 MB max of memory). 

```
Incident Identifier: 8E4EE038-4995-456F-A6E7-1F7894E5B7C5
Hardware Model:      iPhone13,2
Process:             Application [3842]
Path:                /private/var/containers/Bundle/Application/55921F66-6A8B-4523-AAB3-4B85715B90C4/Application.app/Application
Identifier:          com.Application.app
Version:             2022.13 (938)
AppStoreTools:       14B44
AppVariant:          1:iPhone13,2:15
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.Application.app [828]

Date/Time:           2022-12-16 02:18:26.3071 -0700
Launch Time:         2022-12-14 21:42:18.7547 -0700
OS Version:          iPhone OS 15.6.1 (19G82)
Release Type:        User
Baseband Version:    2.70.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x19390d288 __exceptionPreprocess + 220 (NSException.m:200)
1   libobjc.A.dylib               	0x1ac63d744 objc_exception_throw + 60 (objc-exception.mm:565)
2   Foundation                    	0x1951a0edc _NSFileHandleRaiseOperationExceptionWhileReading + 280 (NSFileHandle.m:71)
3   Foundation                    	0x1950cf8f8 -[NSConcreteFileHandle writeData:] + 312 (NSFileHandle.m:75)
4   Application                   	0x102a705f4 -[SentryOutOfMemoryScopeObserver store:] + 92 (SentryOutOfMemoryScopeObserver.m:79)
5   Application                   	0x102a707e0 -[SentryOutOfMemoryScopeObserver addSerializedBreadcrumb:] + 304 (SentryOutOfMemoryScopeObserver.m:100)
6   Application                   	0x102a7df10 -[SentryScope addBreadcrumb:] + 484 (SentryScope.m:137)
7   Application                   	0x102a64414 -[SentryHub addBreadcrumb:] + 200 (SentryHub.m:499)
8   Application                   	0x102a7bfe4 +[SentrySDK addBreadcrumb:] + 60 (SentrySDK.m:337)
9   Application                   	0x102a885a4 -[SentrySystemEventBreadcrumbs batteryStateChanged:] + 164 (SentrySystemEventBreadcrumbs.m:99)
10  CoreFoundation                	0x19389e834 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28 (CFNotificationCenter.c:652)
11  CoreFoundation                	0x19393afd4 ___CFXRegistrationPost_block_invoke + 52 (CFNotificationCenter.c:173)
12  CoreFoundation                	0x19390e1d0 _CFXRegistrationPost + 456 (CFNotificationCenter.c:199)
13  CoreFoundation                	0x1938b48ac _CFXNotificationPost + 728 (CFNotificationCenter.c:1147)
14  Foundation                    	0x195087734 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96 (NSNotification.m:560)
15  UIKitCore                     	0x195eea594 -[UIDevice(UIDevicePrivate) _setBatteryLevel:] + 144 (UIDevice.m:1369)
16  UIKitCore                     	0x195ee37d8 _updateBatteryStatusBasedOnProperties + 300 (UIDevice.m:284)
17  UIKitCore                     	0x1962c03e0 _3rdParty_batteryInformationChanged + 580 (UIDevice.m:439)
18  libsystem_notify.dylib        	0x1b3a1c3b0 ___notify_dispatch_local_notification_block_invoke + 72 (notify_client.c:2033)
19  libdispatch.dylib             	0x193583830 _dispatch_block_async_invoke2 + 148 (queue.c:560)
20  libdispatch.dylib             	0x193574a30 _dispatch_client_callout + 20 (object.m:560)
21  libdispatch.dylib             	0x193582f48 _dispatch_main_queue_drain + 928 (inline_internal.h:2622)
22  libdispatch.dylib             	0x193582b98 _dispatch_main_queue_callback_4CF + 44 (queue.c:7770)
23  CoreFoundation                	0x1938c5800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1795)
24  CoreFoundation                	0x19387f704 __CFRunLoopRun + 2532 (CFRunLoop.c:3144)
25  CoreFoundation                	0x193892bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
26  GraphicsServices              	0x1af9fe374 GSEventRunModal + 164 (GSEvent.c:2200)
27  UIKitCore                     	0x196206b58 -[UIApplication _run] + 1100 (UIApplication.m:3511)
28  UIKitCore                     	0x195f88090 UIApplicationMain + 364 (UIApplication.m:5064)
29  SwiftUI                       	0x19b6ecf24 closure #1 in KitRendererCommon(_:) + 164 (UIKitApp.swift:35)
30  SwiftUI                       	0x19b61ae08 runApp<A>(_:) + 252 (<compiler-generated>:0)
31  SwiftUI                       	0x19b5fc0f4 static App.main() + 128 (App.swift:114)
32  Application                   	0x10295a51c static ApplicationApp.$main() + 28 (ApplicationApp.swift:13)
33  Application                   	0x10295a51c main + 40 (AccessibleMessage+Extensions.swift:0)
34  dyld                          	0x102d6dda4 start + 520 (dyldMain.cpp:879)

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001cb509b38 __pthread_kill + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000002052773bc pthread_kill + 268 (pthread.c:1668)
2   libsystem_c.dylib             	0x000000019ea1f524 abort + 168 (abort.c:118)
3   libc++abi.dylib               	0x00000001ac748b7c abort_message + 132 (abort_message.cpp:78)
4   libc++abi.dylib               	0x00000001ac7389c4 demangling_terminate_handler() + 336 (cxa_default_handlers.cpp:71)
5   libobjc.A.dylib               	0x00000001ac643c68 _objc_terminate() + 144 (objc-exception.mm:701)
6   Application                   	0x0000000102a99020 CPPExceptionTerminate() + 132 (SentryCrashMonitor_CPPException.cpp:171)
7   libc++abi.dylib               	0x00000001ac747f18 std::__terminate(void (*)()) + 20 (cxa_handlers.cpp:59)
8   libc++abi.dylib               	0x00000001ac74ac1c __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 36 (cxa_exception.cpp:152)
9   libc++abi.dylib               	0x00000001ac74abc8 __cxa_throw + 140 (cxa_exception.cpp:283)
10  libobjc.A.dylib               	0x00000001ac63d8ac objc_exception_throw + 420 (objc-exception.mm:591)
11  Foundation                    	0x00000001951a0edc _NSFileHandleRaiseOperationExceptionWhileReading + 280 (NSFileHandle.m:71)
12  Foundation                    	0x00000001950cf8f8 -[NSConcreteFileHandle writeData:] + 312 (NSFileHandle.m:75)
13  Application                   	0x0000000102a705f4 -[SentryOutOfMemoryScopeObserver store:] + 92 (SentryOutOfMemoryScopeObserver.m:79)
14  Application                   	0x0000000102a707e0 -[SentryOutOfMemoryScopeObserver addSerializedBreadcrumb:] + 304 (SentryOutOfMemoryScopeObserver.m:100)
15  Application                   	0x0000000102a7df10 -[SentryScope addBreadcrumb:] + 484 (SentryScope.m:137)
16  Application                   	0x0000000102a64414 -[SentryHub addBreadcrumb:] + 200 (SentryHub.m:499)
17  Application                   	0x0000000102a7bfe4 +[SentrySDK addBreadcrumb:] + 60 (SentrySDK.m:337)
18  Application                   	0x0000000102a885a4 -[SentrySystemEventBreadcrumbs batteryStateChanged:] + 164 (SentrySystemEventBreadcrumbs.m:99)
19  CoreFoundation                	0x000000019389e834 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28 (CFNotificationCenter.c:652)
20  CoreFoundation                	0x000000019393afd4 ___CFXRegistrationPost_block_invoke + 52 (CFNotificationCenter.c:173)
21  CoreFoundation                	0x000000019390e1d0 _CFXRegistrationPost + 456 (CFNotificationCenter.c:199)
22  CoreFoundation                	0x00000001938b48ac _CFXNotificationPost + 728 (CFNotificationCenter.c:1147)
23  Foundation                    	0x0000000195087734 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96 (NSNotification.m:560)
24  UIKitCore                     	0x0000000195eea594 -[UIDevice(UIDevicePrivate) _setBatteryLevel:] + 144 (UIDevice.m:1369)
25  UIKitCore                     	0x0000000195ee37d8 _updateBatteryStatusBasedOnProperties + 300 (UIDevice.m:284)
26  UIKitCore                     	0x00000001962c03e0 _3rdParty_batteryInformationChanged + 580 (UIDevice.m:439)
27  libsystem_notify.dylib        	0x00000001b3a1c3b0 ___notify_dispatch_local_notification_block_invoke + 72 (notify_client.c:2033)
28  libdispatch.dylib             	0x0000000193583830 _dispatch_block_async_invoke2 + 148 (queue.c:560)
29  libdispatch.dylib             	0x0000000193574a30 _dispatch_client_callout + 20 (object.m:560)
30  libdispatch.dylib             	0x0000000193582f48 _dispatch_main_queue_drain + 928 (inline_internal.h:2622)
31  libdispatch.dylib             	0x0000000193582b98 _dispatch_main_queue_callback_4CF + 44 (queue.c:7770)
32  CoreFoundation                	0x00000001938c5800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1795)
33  CoreFoundation                	0x000000019387f704 __CFRunLoopRun + 2532 (CFRunLoop.c:3144)
34  CoreFoundation                	0x0000000193892bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
35  GraphicsServices              	0x00000001af9fe374 GSEventRunModal + 164 (GSEvent.c:2200)
36  UIKitCore                     	0x0000000196206b58 -[UIApplication _run] + 1100 (UIApplication.m:3511)
37  UIKitCore                     	0x0000000195f88090 UIApplicationMain + 364 (UIApplication.m:5064)
38  SwiftUI                       	0x000000019b6ecf24 closure #1 in KitRendererCommon(_:) + 164 (UIKitApp.swift:35)
39  SwiftUI                       	0x000000019b61ae08 runApp<A>(_:) + 252 (<compiler-generated>:0)
40  SwiftUI                       	0x000000019b5fc0f4 static App.main() + 128 (App.swift:114)
41  Application                   	0x000000010295a51c static ApplicationApp.$main() + 28 (ApplicationApp.swift:13)
42  Application                   	0x000000010295a51c main + 40 (AccessibleMessage+Extensions.swift:0)
43  dyld                          	0x0000000102d6dda4 start + 520 (dyldMain.cpp:879)

Thread 1:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001cb503a2c __semwait_signal + 8 (:-1)
1   libsystem_c.dylib             	0x000000019ea040e4 nanosleep + 220 (nanosleep.c:104)
2   libsystem_c.dylib             	0x000000019ea04e14 usleep + 68 (usleep.c:52)
3   Application                   	0x0000000102a37234 __40-[RSEventRepository __initiateProcessor]_block_invoke + 500 (RSEventRepository.m:0)
4   libdispatch.dylib             	0x0000000193572e6c _dispatch_call_block_and_release + 32 (init.c:1517)
5   libdispatch.dylib             	0x0000000193574a30 _dispatch_client_callout + 20 (object.m:560)
6   libdispatch.dylib             	0x0000000193577b44 _dispatch_queue_override_invoke + 784 (inline_internal.h:2622)
7   libdispatch.dylib             	0x0000000193586164 _dispatch_root_queue_drain + 396 (inline_internal.h:0)
8   libdispatch.dylib             	0x000000019358696c _dispatch_worker_thread2 + 164 (queue.c:6935)
9   libsystem_pthread.dylib       	0x0000000205271080 _pthread_wqthread + 228 (pthread.c:2612)
10  libsystem_pthread.dylib       	0x0000000205270e5c start_wqthread + 8 (:-1)

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib        	0x00000001cb5034a0 mach_msg_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001cb503ae4 mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x000000019387ad30 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x000000019387f1bc __CFRunLoopRun + 1180 (CFRunLoop.c:3000)
4   CoreFoundation                	0x0000000193892bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   Foundation                    	0x0000000195085444 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
6   Foundation                    	0x00000001950c6e0c -[NSRunLoop(NSRunLoop) runUntilDate:] + 92 (NSRunLoop.m:420)
7   UIKitCore                     	0x0000000196180cc4 -[UIEventFetcher threadMain] + 524 (UIEventFetcher.m:1167)
8   Foundation                    	0x00000001950d541c __NSThread__start__ + 808 (NSThread.m:972)
9   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
10  libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 4:
0   libsystem_kernel.dylib        	0x00000001cb503a2c __semwait_signal + 8 (:-1)
1   libsystem_c.dylib             	0x000000019ea040e4 nanosleep + 220 (nanosleep.c:104)
2   libsystem_c.dylib             	0x000000019ea18388 sleep + 52 (sleep.c:62)
3   Application                   	0x0000000102a9db74 monitorCachedData + 676 (SentryCrashCachedData.c:144)
4   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
5   libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001cb5034a0 mach_msg_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001cb503ae4 mach_msg + 76 (mach_msg.c:119)
2   libsystem_kernel.dylib        	0x00000001cb50fa44 thread_suspend + 96 (thread_actUser.c:1016)
3   Application                   	0x0000000102a99720 handleExceptions + 128 (SentryCrashMonitor_MachException.c:258)
4   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
5   libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 6 name:
Thread 6:
0   libsystem_kernel.dylib        	0x00000001cb5034a0 mach_msg_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001cb503b70 mach_msg + 216 (mach_msg.c:137)
2   Application                   	0x0000000102a9974c handleExceptions + 172 (SentryCrashMonitor_MachException.c:266)
3   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
4   libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 7 name:
Thread 7:
0   libsystem_kernel.dylib        	0x00000001cb503a2c __semwait_signal + 8 (:-1)
1   libsystem_c.dylib             	0x000000019ea040e4 nanosleep + 220 (nanosleep.c:104)
2   Foundation                    	0x00000001950e7ce8 +[NSThread sleepForTimeInterval:] + 160 (NSThread.m:504)
3   Application                   	0x0000000102a40220 -[SentryANRTracker detectANRs] + 448 (SentryANRTracker.m:75)
4   Foundation                    	0x00000001950d541c __NSThread__start__ + 808 (NSThread.m:972)
5   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
6   libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 8 name:
Thread 8:
0   libboringssl.dylib            	0x00000001adece2c0 bssl::ssl_send_alert_impl(ssl_st*, int, int) + 152 (s3_pkt.cc:417)
1   libboringssl.dylib            	0x00000001aded9ad8 SSL_shutdown + 204 (ssl_lib.cc:1152)
2   libboringssl.dylib            	0x00000001ade8bf5c boringssl_session_disconnect + 76 (boringssl_session.m:506)
3   libboringssl.dylib            	0x00000001ade94a88 nw_protocol_boringssl_disconnect + 96 (protocol_boringssl.m:1346)
4   libnetwork.dylib              	0x0000000194563020 -[NWConcrete_nw_endpoint_flow cancelWithHandler:forced:] + 304 (endpoint_flow.m:236)
5   libnetwork.dylib              	0x000000019469ff58 nw_endpoint_handler_cancel + 1108 (endpoint_handler.m:1042)
6   libnetwork.dylib              	0x000000019461ad74 __nw_connection_cancel_inner_block_invoke + 1168 (connection.m:2525)
7   libnetwork.dylib              	0x00000001946274c0 nw_connection_cancel + 296 (connection.m:167)
8   libquic.dylib                 	0x0000000204b62204 quic_drain_connection + 920 (protocol_quic.c:2441)
9   libquic.dylib                 	0x0000000204b8cb90 quic_idle_timeout_fired + 1492 (protocol_quic.c:2134)
10  libquic.dylib                 	0x0000000204b82e64 quic_timer_run + 220 (quic_timer.c:197)
11  libnetwork.dylib              	0x0000000194afe238 __nw_protocol_instance_schedule_wakeup_block_invoke + 64 (protocol_implementation.m:4770)
12  libnetwork.dylib              	0x00000001947749e0 __nw_context_reset_timer_block_with_time_block_invoke + 228 (context.m:1820)
13  libdispatch.dylib             	0x0000000193574a30 _dispatch_client_callout + 20 (object.m:560)
14  libdispatch.dylib             	0x0000000193577eec _dispatch_continuation_pop + 500 (inline_internal.h:2622)
15  libdispatch.dylib             	0x000000019358b13c _dispatch_source_invoke + 1596 (source.c:596)
16  libdispatch.dylib             	0x000000019357df80 _dispatch_workloop_invoke + 1784 (inline_internal.h:0)
17  libdispatch.dylib             	0x0000000193587500 _dispatch_workloop_worker_thread + 648 (queue.c:6732)
18  libsystem_pthread.dylib       	0x00000002052710bc _pthread_wqthread + 288 (pthread.c:2599)
19  libsystem_pthread.dylib       	0x0000000205270e5c start_wqthread + 8 (:-1)

Thread 9 name:
Thread 9:
0   libsystem_kernel.dylib        	0x00000001cb5034a0 mach_msg_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001cb503ae4 mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x000000019387ad30 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x000000019387f1bc __CFRunLoopRun + 1180 (CFRunLoop.c:3000)
4   CoreFoundation                	0x0000000193892bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   CFNetwork                     	0x000000019430f1dc +[__CFN_CoreSchedulingSetRunnable _run:] + 472 (CoreSchedulingSet.mm:1372)
6   Foundation                    	0x00000001950d541c __NSThread__start__ + 808 (NSThread.m:972)
7   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
8   libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 10 name:
Thread 10:
0   libsystem_kernel.dylib        	0x00000001cb5034a0 mach_msg_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001cb503ae4 mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x000000019387ad30 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x000000019387f1bc __CFRunLoopRun + 1180 (CFRunLoop.c:3000)
4   CoreFoundation                	0x0000000193892bc8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   Foundation                    	0x0000000195085444 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
6   Intercom                      	0x00000001041bc008 -[IntercomSDK__SRRunLoopThread main] + 252
7   Foundation                    	0x00000001950d541c __NSThread__start__ + 808 (NSThread.m:972)
8   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
9   libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 11 name:
Thread 11:
0   libsystem_kernel.dylib        	0x00000001cb504164 select$DARWIN_EXTSN + 8 (:-1)
1   CoreFoundation                	0x000000019391eb68 __CFSocketManager + 644 (CFSocket.c:1343)
2   libsystem_pthread.dylib       	0x00000002052719ac _pthread_start + 148 (pthread.c:891)
3   libsystem_pthread.dylib       	0x0000000205270e68 thread_start + 8 (:-1)

Thread 12:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 13:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 14:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 15:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 16:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 17:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 18:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 19:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 20:
0   libsystem_pthread.dylib       	0x0000000205270e54 start_wqthread + 0 (:-1)

Thread 21 name:
Thread 21:
0   libxpc.dylib                  	0x000000020529a828 _xpc_connection_call_event_handler + 136 (connection.c:810)
1   libxpc.dylib                  	0x0000000205296d0c do_mach_notify_port_destroyed + 144 (connection.c:1696)
2   libxpc.dylib                  	0x00000002052b8208 _Xmach_notify_port_destroyed + 84 (notifyServer.c:253)
3   libxpc.dylib                  	0x00000002052b83bc notify_server + 92 (notifyServer.c:516)
4   libxpc.dylib                  	0x0000000205299aec _xpc_connection_pass2mig + 172 (connection.c:1508)
5   libxpc.dylib                  	0x000000020529ac20 _xpc_connection_mach_event + 920 (connection.c:1547)
6   libdispatch.dylib             	0x0000000193574af0 _dispatch_client_callout4 + 20 (object.m:600)
7   libdispatch.dylib             	0x0000000193590b2c _dispatch_mach_msg_invoke + 464 (mach.c:2418)
8   libdispatch.dylib             	0x000000019357c000 _dispatch_lane_serial_drain + 376 (inline_internal.h:0)
9   libdispatch.dylib             	0x000000019359184c _dispatch_mach_invoke + 456 (mach.c:2740)
10  libdispatch.dylib             	0x000000019357c000 _dispatch_lane_serial_drain + 376 (inline_internal.h:0)
11  libdispatch.dylib             	0x000000019357cc80 _dispatch_lane_invoke + 392 (queue.c:3944)
12  libdispatch.dylib             	0x0000000193587500 _dispatch_workloop_worker_thread + 648 (queue.c:6732)
13  libsystem_pthread.dylib       	0x00000002052710bc _pthread_wqthread + 288 (pthread.c:2599)
14  libsystem_pthread.dylib       	0x0000000205270e5c start_wqthread + 8 (:-1)


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x00000001ac74c0f5   x5: 0x000000016d4a7f20   x6: 0x000000000000006e   x7: 0x0000000000000000
    x8: 0xc69fab57a3597269   x9: 0xc69fab56a18577e9  x10: 0x0000000000000200  x11: 0x000000000000000b
   x12: 0x000000000000000b  x13: 0x0000000193c4aa9f  x14: 0x00000001ac74c11b  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x0000000102dc0580  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x0000000102dc0660  x22: 0x00000002802d83e0  x23: 0x0000000103e5dee0
   x24: 0x0000000280eb5770  x25: 0x0000000200000003  x26: 0x0000000000000001  x27: 0x0000000000001400
   x28: 0x0000000000000000   fp: 0x000000016d4a7e90   lr: 0x00000002052773bc
    sp: 0x000000016d4a7e70   pc: 0x00000001cb509b38 cpsr: 0x40001000
   esr: 0x56000080  Address size fault


Binary Images:
0x102954000 - 0x102b67fff Application arm64  <b9ffb35526fd3bde9b43f1c80627ca6d> /private/var/containers/Bundle/Application/55921F66-6A8B-4523-AAB3-4B85715B90C4/Application.app/Application
0x102d54000 - 0x102dabfff dyld arm64e  <66e1fb2668f8379ba052eb8b8291b5e1> /usr/lib/dyld
0x10411c000 - 0x1043a3fff Intercom arm64  <97c5fb2d3c3d3fe5b90a2180a2c2ccbc> /private/var/containers/Bundle/Application/55921F66-6A8B-4523-AAB3-4B85715B90C4/Application.app/Frameworks/Intercom.framework/Intercom
0x193571000 - 0x1935b6fff libdispatch.dylib arm64e  <e3ea4f635d11342aaf199f58dbc8e259> /usr/lib/system/libdispatch.dylib
0x193874000 - 0x193cc9fff CoreFoundation arm64e  <6b22dd8135853be6bc77ba19810ec0f2> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x194097000 - 0x194558fff CFNetwork arm64e  <106410ffdd4f3527ad531980fe8b0ddd> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x194559000 - 0x194fedfff libnetwork.dylib arm64e  <0dbe8d5848823c66b0310239c020ee4c> /usr/lib/libnetwork.dylib
0x19506c000 - 0x195376fff Foundation arm64e  <ee1abaf23d7137fb906715aa79528619> /System/Library/Frameworks/Foundation.framework/Foundation
0x195cf2000 - 0x19758ffff UIKitCore arm64e  <137a95aada6d332cbc01e13bb9b6e317> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x19b4ad000 - 0x19c544fff SwiftUI arm64e  <6ab6407f39eb3fb393d55e0c55af3a2d> /System/Library/Frameworks/SwiftUI.framework/SwiftUI
0x19e9ff000 - 0x19ea7efff libsystem_c.dylib arm64e  <86a1a24ace353769ba6960f28353281e> /usr/lib/system/libsystem_c.dylib
0x1ac627000 - 0x1ac663fff libobjc.A.dylib arm64e  <f6368be9109b3405b282624040529afd> /usr/lib/libobjc.A.dylib
0x1ac737000 - 0x1ac74efff libc++abi.dylib arm64e  <d00067b20a7a3cb9b4d407b160da261b> /usr/lib/libc++abi.dylib
0x1ade86000 - 0x1adf47fff libboringssl.dylib arm64e  <d912c7bbbb13308cab0130c67ab254c9> /usr/lib/libboringssl.dylib
0x1af9fd000 - 0x1afa05fff GraphicsServices arm64e  <a094e7b51d4037c5902756d86988ec4b> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x1b3a19000 - 0x1b3a23fff libsystem_notify.dylib arm64e  <252db8f9aaef333ba181d492e14411b2> /usr/lib/system/libsystem_notify.dylib
0x1cb502000 - 0x1cb537fff libsystem_kernel.dylib arm64e  <1fb39303587b320eaeb8e51a54c8a4a9> /usr/lib/system/libsystem_kernel.dylib
0x204b4d000 - 0x204c0afff libquic.dylib arm64e  <852ce208b7dc3b72884bbc1f0a02c33d> /usr/lib/libquic.dylib
0x205270000 - 0x20527bfff libsystem_pthread.dylib arm64e  <adc41700002e3a2bb4a1eb5fbf575770> /usr/lib/system/libsystem_pthread.dylib
0x20528b000 - 0x2052c7fff libxpc.dylib arm64e  <b183213379dc3e42b704ef71f75a577e> /usr/lib/system/libxpc.dylib

EOF
```

<img width="1724" alt="Screen Shot 2022-12-22 at 7 46 36 AM" src="https://user-images.githubusercontent.com/94926620/209171154-8788b2a8-01ba-428f-9864-8bb47e50f8cd.png">

Seems that this executes in SentryOutOfMemoryScopeObserver right before the app terminates:

```
- (void)store:(NSData *)data
{
    [self.fileHandle seekToEndOfFile];
    [self.fileHandle writeData:data];
    [self.fileHandle writeData:[@"\n" dataUsingEncoding:NSASCIIStringEncoding]];

    self.breadcrumbCounter += 1;

    if (self.breadcrumbCounter >= self.maxBreadcrumbs) {
        [self switchFileHandle];
        self.breadcrumbCounter = 0;
    }
}
```

Termination details: 

<img width="1721" alt="Screen Shot 2022-12-22 at 7 47 50 AM" src="https://user-images.githubusercontent.com/94926620/209171342-9076467f-12f1-4d33-9685-0269b32a010c.png">

### Expected Result

Our app does not crash with references to SentryOutOfMemoryScopeObserver in the crash logs in production. 

### Actual Result

Our app continues to crash with out of memory crash logs at the moment. I'd like to see if you guys have any insight on whether this could be due to something in the Sentry SDK. Thanks in advance for any guidance here!

**Comment by philipphofmann** [comment] 2022-12-22 16:35
It could be related to https://github.com/getsentry/sentry-cocoa/issues/2548. Thanks for reporting this. We need to have a look, but I can't give you an ETA.

**Comment by chaseklingelzen** [comment] 2022-12-22 16:45
@philipphofmann thank you for the quick response. We will disable this flag for now. Will check back in after the new year to see what next steps are.

**Comment by philipphofmann** [comment] 2022-12-22 16:46
The fix should be easy https://github.com/getsentry/sentry-cocoa/issues/2548#issuecomment-1363082062, but I won't be able to push out a release before Christmas.

**Comment by chaseklingelzen** [comment] 2022-12-22 16:49
Totally understand. Good to hear its an easy update on your end. Thanks again @philipphofmann.

**Comment by chaseklingelzen** [comment] 2022-12-22 17:00
Just wanted to provide some extra data here. We have seen over 600 crashes in our production app with references to SentryOutOfMemoryScopeObserver.

**Comment by philipphofmann** [comment] 2022-12-22 17:49
This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/2548. Let's continue the discussion there, please.

**Closed by philipphofmann** 2022-12-22 17:49 UTC
Labels: Type: Bug, Platform: Cocoa, Status: Untriaged
