### ISSUE TITLE
test: Fix flaky testAsyncStacktraces

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1415] opened 2021-10-21 08:40 UTC
This test is disabled because it is flaky. We need to fix it, but as this is an experimental feature this has not a high priority.
https://github.com/getsentry/sentry-cocoa/blob/4dbf9c83da9fca185c58db6a6f121876465639e7/Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift#L70-L73

**Comment by armcknight** [comment] 2023-01-13 18:51
Dupe of https://github.com/getsentry/sentry-cocoa/issues/2259

**Closed by armcknight** 2023-01-13 18:51 UTC
Labels: Type: Testing, Status: Backlog, Platform: Cocoa, Type: Flaky Test
