### ISSUE TITLE
Repeated SentryDebugMeta name

### ISSUE THREAD

**Issue by ZeroOnet** [getsentry/sentry-cocoa#2039] opened 2022-08-04 09:43 UTC
### Platform

iOS

### Installed

CocoaPods

### Version

7.10.2 Self-hosting

### Steps to Reproduce

With the stacktrace as follows:

![image](https://user-images.githubusercontent.com/20768739/182817115-1fe7fb86-5f92-432a-8bbd-c0bc31afd084.png)

I customize my stacktrace to SentryEvent:

```swift
var toSentryDebugImage: DebugMeta {
    let result = DebugMeta()
    result.type = "apple"
    result.uuid = uuid
    result.name = name
    return result
}

var toSentryFrame: Frame {
    let result = Frame()
    result.package = name
    result.instructionAddress = toHex(with: address)
    result.symbolAddress = toHex(with: symbolAddress)

    return result
}

var toSentryStacktrace: Stacktrace {
    Stacktrace(frames: frames.map { $0.toSentryFrame }, registers: [:])
}

let event = Event(level: .error)
event.debugMeta = backtrace.callStacks.flatMap { $0.frames }.map { $0.toSentryDebugImage }
event.threads = backtrace.callStacks.enumerated().map {
    let result = Thread(threadId: $0.offset as NSNumber)
    result.crashed = ($0.element.threadAttributed ?? false) as NSNumber
    result.stacktrace = $0.element.toSentryStacktrace
    return result
}

SentrySDK.capture(event: event)

```

### Expected Result

Stacktrace of event is my custom with correct format.

### Actual Result

![image](https://user-images.githubusercontent.com/20768739/182816334-e184f16e-58e9-404a-8992-80cfc69bd87d.png)

The binary image name is repeated one of them.

**Comment by brustolin** [comment] 2022-08-04 13:41
Hey @ZeroOnet thanks for open this. We need to investigate it a little bit and then we get back to you. 

But first, have you tried to update the SDK?

**Comment by ZeroOnet** [comment] 2022-08-05 03:26
> Hey @ZeroOnet thanks for open this. We need to investigate it a little bit and then we get back to you.
> 
> But first, have you tried to update the SDK?

I tried to update SDK to 7.23.0, this problem is still here.

**Comment by brustolin** [comment] 2022-08-10 13:32
Hey @ZeroOnet, can you provide a repro? I could not reproduce this.

**Comment by ZeroOnet** [comment] 2022-08-11 02:40
Our sentry server is self-hosting with version 21.11.0. 

The json of event from sentry server: [demo.json.zip](https://github.com/getsentry/sentry-cocoa/files/9305653/demo.json.zip).

 Package of backtrace frame is always `libsystem_pthread.dylib`, but `code_file` of debug image is correct.

**Comment by ZeroOnet** [comment] 2022-08-11 02:55
> Hey @ZeroOnet, can you provide a repro? I could not reproduce this.

Our sentry server is self-hosting with version 21.11.0.

The json of event from sentry server: [demo.json.zip](https://github.com/getsentry/sentry-cocoa/files/9305653/demo.json.zip).

Package of backtrace frame is always libsystem_pthread.dylib, but code_file of debug image is correct. The reason of this issue may be sentry server sdk mistake rather than sentry cocoa sdk.

**Comment by ZeroOnet** [comment] 2022-08-11 10:36
> Hey @ZeroOnet, can you provide a repro? I could not reproduce this.

DemoCode:
```swift
    let event = Event(level: .error)

    let frame1 = Frame()
    frame1.instructionAddress = "0x0000000183078d90"
    frame1.symbolAddress = "0x0000000182de3000"
    frame1.package = "UIKitCore"

    let frame2 = Frame()
    frame2.instructionAddress = "0x000000019cabb374"
    frame2.symbolAddress = "0x000000019caba000"
    frame2.package = "GraphicsServices"

    let frame3 = Frame()
    frame3.instructionAddress = "0x00000001809ba800"
    frame3.symbolAddress = "0x0000000180969000"
    frame3.package = "CoreFoundation"

    let stackTrace = Stacktrace(frames: [frame1, frame2, frame3], registers: [:])
    let thread = Thread.init(threadId: 0 as NSNumber)
    thread.stacktrace = stackTrace

    let dm1 = DebugMeta()
    dm1.name = "UIKitCore"
    dm1.uuid = "3ed35565-456d-33cb-b554-6c567fa81585"
    dm1.type = "apple"

    let dm2 = DebugMeta()
    dm2.name = "GraphicsServices"
    dm2.uuid = "260f066e-c5de-3844-967e-483985448f21"
    dm2.type = "apple"

    let dm3 = DebugMeta()
    dm3.name = "CoreFoundation"
    dm3.uuid = "5198fb57-5645-3b34-a49f-f32b52256cf3"
    dm3.type = "apple"

    event.threads = [thread]
    event.debugMeta = [dm1, dm2, dm3]

    SentrySDK.capture(event: event)
```

SentrySDK console log: 
![image](https://user-images.githubusercontent.com/20768739/184115050-f30a1a3c-486a-42b6-9778-b27038accbfe.png)

Sentry server event:
![image](https://user-images.githubusercontent.com/20768739/184115129-1138df4b-b0ab-44e0-adf0-7500daf91a35.png)

Sentry server event json:

[demo.json.zip](https://github.com/getsentry/sentry-cocoa/files/9307990/demo.json.zip)

**Comment by ZeroOnet** [comment] 2022-08-16 02:32
@brustolin Any help? Should I commit an issue to「getsentry/sentry」？

**Comment by brustolin** [comment] 2022-08-16 08:17
Please do. I tried to contact someone from the server team but got no response.

**Comment by philipphofmann** [comment] 2022-08-31 05:57
Hey, @ZeroOnet, we had some dSYMs missing for iOS 15.5 simulators, which your screenshot above shows. I just uploaded them. Can you please retry?

**Comment by ZeroOnet** [comment] 2022-09-01 02:23
> Hey, @ZeroOnet, we had some dSYMs missing for iOS 15.5 simulators, which your screenshot above shows. I just uploaded them. Can you please retry?

The problem is repeated binary image name mistake rather than stacktrace symbolication. I committed an [issue](https://github.com/getsentry/sentry-cocoa/issues/2083) to getsentry/sentry but was closed.

**Comment by philipphofmann** [comment] 2022-09-01 06:05
I'm not sure what you mean by repeated binary image name, but the repeated UIKitCore should be there. This is the stacktrace and it tells you that you have three frames that are in UIKitCore. Next, you have the memory address, and then the function name, which is redacted because of the missing symbols.

<img width="479" alt="Screen Shot 2022-09-01 at 08 00 48" src="https://user-images.githubusercontent.com/2443292/187842535-e61b656a-af77-41e5-acff-81257ee029ce.png">

This is a normal stacktrace
<img width="636" alt="Screen Shot 2022-09-01 at 08 03 40" src="https://user-images.githubusercontent.com/2443292/187842983-e665c920-2ec2-4204-9524-86fbc5f62a48.png">

**Comment by ZeroOnet** [comment] 2022-09-01 06:19
> > Hey @ZeroOnet, can you provide a repro? I could not reproduce this.
> 
> DemoCode:
> 
> ```swift
>     let event = Event(level: .error)
> 
>     let frame1 = Frame()
>     frame1.instructionAddress = "0x0000000183078d90"
>     frame1.symbolAddress = "0x0000000182de3000"
>     frame1.package = "UIKitCore"
> 
>     let frame2 = Frame()
>     frame2.instructionAddress = "0x000000019cabb374"
>     frame2.symbolAddress = "0x000000019caba000"
>     frame2.package = "GraphicsServices"
> 
>     let frame3 = Frame()
>     frame3.instructionAddress = "0x00000001809ba800"
>     frame3.symbolAddress = "0x0000000180969000"
>     frame3.package = "CoreFoundation"
> 
>     let stackTrace = Stacktrace(frames: [frame1, frame2, frame3], registers: [:])
>     let thread = Thread.init(threadId: 0 as NSNumber)
>     thread.stacktrace = stackTrace
> 
>     let dm1 = DebugMeta()
>     dm1.name = "UIKitCore"
>     dm1.uuid = "3ed35565-456d-33cb-b554-6c567fa81585"
>     dm1.type = "apple"
> 
>     let dm2 = DebugMeta()
>     dm2.name = "GraphicsServices"
>     dm2.uuid = "260f066e-c5de-3844-967e-483985448f21"
>     dm2.type = "apple"
> 
>     let dm3 = DebugMeta()
>     dm3.name = "CoreFoundation"
>     dm3.uuid = "5198fb57-5645-3b34-a49f-f32b52256cf3"
>     dm3.type = "apple"
> 
>     event.threads = [thread]
>     event.debugMeta = [dm1, dm2, dm3]
> 
>     SentrySDK.capture(event: event)
> ```
> 
> SentrySDK console log: ![image](https://user-images.githubusercontent.com/20768739/184115050-f30a1a3c-486a-42b6-9778-b27038accbfe.png)
> 
> Sentry server event: ![image](https://user-images.githubusercontent.com/20768739/184115129-1138df4b-b0ab-44e0-adf0-7500daf91a35.png)
> 
> Sentry server event json:
> 
> [demo.json.zip](https://github.com/getsentry/sentry-cocoa/files/9307990/demo.json.zip)

@philipphofmann With this comment, I customized backtrace with deferent binary image name such as UIKitCore、GraphicsServices and so on. But the dashboard of event only gave me UIKitCore.

**Comment by philipphofmann** [comment] 2022-09-01 06:50
You find the images below the stacktrace. Click on show details and then they appear.

<img width="936" alt="Screen Shot 2022-09-01 at 08 49 23" src="https://user-images.githubusercontent.com/2443292/187850070-a4db5e60-3e07-4837-ad1e-2337d06f4b67.png">

Loaded images
<img width="939" alt="Screen Shot 2022-09-01 at 08 50 08" src="https://user-images.githubusercontent.com/2443292/187850172-36b075a7-6d7b-4591-b191-34fa34d1c0bb.png">

**Comment by ZeroOnet** [comment] 2022-09-02 02:20
> You find the images below the stacktrace. The stacktrace only shows the images in the stacktrace. Click on show details, and then they appear.
> 
> <img alt="Screen Shot 2022-09-01 at 08 49 23" width="936" src="https://user-images.githubusercontent.com/2443292/187850070-a4db5e60-3e07-4837-ad1e-2337d06f4b67.png">
> 
> Loaded images <img alt="Screen Shot 2022-09-01 at 08 50 08" width="939" src="https://user-images.githubusercontent.com/2443292/187850172-36b075a7-6d7b-4591-b191-34fa34d1c0bb.png">

I know this. The images list also missing:
![image](https://user-images.githubusercontent.com/20768739/188044810-a06845bf-a3c1-464d-a30b-7aafca61486e.png)

**Comment by philipphofmann** [comment] 2022-09-06 08:12
I think the root cause of the problem is that you are trying to customize the stacktrace, and something is going wrong. May I ask why do you have to customize your stacktrace, @ZeroOnet? Ideally, you shouldn't have to do this.

**Comment by ZeroOnet** [comment] 2022-09-06 08:35
> I think the root cause of the problem is that you are trying to customize the stacktrace, and something is going wrong. May I ask why do you have to customize your stacktrace, @ZeroOnet? Ideally, you shouldn't have to do this.

So if I want to customize stacktrace, What's should I notice? SentrySDK did not report any errors. I want to symbolicate stacktrace of Hangs which is my APM collected. Is DebugMeta any fields missing? eg: imageSize、imageAdress or imageVmAddress?

**Comment by philipphofmann** [comment] 2022-09-06 16:07
I'm a bit confused. Can you please answer the following questions?

1. What do you mean by your APM?
2. What are hangs? If you mean app hangs, we have an integration for that see https://docs.sentry.io/platforms/apple/configuration/app-hangs/.
3. Why do you want to customize your stacktrace? If you capture a message or an error, the SDK attaches the stacktrace for you.

**Comment by ZeroOnet** [comment] 2022-09-07 07:13
> I'm a bit confused. Can you please answer the following questions?
> 
> 1. What do you mean by your APM?
> 2. What are hangs? If you mean app hangs, we have an integration for that see https://docs.sentry.io/platforms/apple/configuration/app-hangs/.
> 3. Why do you want to customize your stacktrace? If you capture a message or an error, the SDK attaches the stacktrace for you.

I find the reason of this problem. If I filled imageSize、imageAddress and imageVmAddress of DebugMeta, Dashboard will display correct backtrace.

**Comment by philipphofmann** [comment] 2022-09-08 11:27
Oh, that's great news. Thanks for the update, @ZeroOnet. I'm going to close this now.

**Closed by philipphofmann** 2022-09-08 11:27 UTC
Labels: Type: Bug, Platform: Cocoa
