### ISSUE TITLE
macOS build fails for versions >= 5.0.3

### ISSUE THREAD

**Issue by fe9lix** [getsentry/sentry-cocoa#526] opened 2020-05-18 14:54 UTC
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [x] MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes: 5.2.2
- [ ]  No

_sentry-cocoa installed with:_
- [x] Swift Package Manager
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.0.3**

---
I have following issue:
The latest version of the Sentry SDK (installed with SPM) cannot be built in a macOS application.

**Steps to reproduce:**
- Create a new Xcode project for a macOS app with the current version of Xcode (11.4.1)
- Add the latest version of the Sentry package (>= 5.0.3) through Swift Package Manager (Xcode -> File -> Swift Packages -> Add package dependency...)
- Build the project

**Actual result:**
- A build error occurs: ".../Sources/Sentry/SentryCrashExceptionApplication.m:18:12: No visible @interface for 'NSObject' declares the selector 'reportException:'"

**Expected result:**
- No build error occurs

**Comment by philipphofmann** [comment] 2020-05-19 13:38
I can reproduce the issue. Thanks @fe9lix for reporting this. We have to fix this.

**Comment by bruno-garcia** [comment] 2020-05-19 17:35
[It was fixed on 5.0.4](https://github.com/getsentry/sentry-cocoa/pull/521). Could you please try that again?

**Comment by fe9lix** [comment] 2020-05-19 17:48
Just tested again with 5.0.4 (also after clean build, resetting SPM caches, etc.) – still same issue.

**Comment by philipphofmann** [comment] 2020-05-19 17:52
I can also reproduce the issue @bruno-garcia. I think we are missing the header `#import <AppKit/AppKit.h>` in `SentryCrashExceptionApplication.m`, but I'm not 100% sure yet.

**Comment by bruno-garcia** [comment] 2020-05-20 02:06
Thanks for testing it and raising this @fe9lix .

I assume this has been broken for a while then since nothing really changed here besides styling: https://github.com/getsentry/sentry-cocoa/commits/master/Sources/Sentry/SentryCrashExceptionApplication.m

@HazAT Any ideas why this code calls: `[super reportException:exception];` when no clear base type is defined for it? (error message even whines that `NSObject` doesn't have such method).

[This was actually added in 2017](https://github.com/getsentry/sentry-cocoa/commit/d96921ed8f5274ad5840ec1f278d28fb006fc5e8#diff-574976edac1f945f5fc7dddde02c06c9) so I'm lost here.

**Comment by philipphofmann** [comment] 2020-05-20 05:23
That also confused me when looking at it. Thanks @bruno-garcia for the nice summary.

**Closed** 2020-05-20 08:48 UTC
Labels: bug
