### ISSUE TITLE
Main thread deadlock when `tracesSampler` is enabled

### ISSUE THREAD

**Issue by jhurray** [getsentry/sentry-cocoa#3292] opened 2023-09-19 15:18 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.11.0

### Steps to Reproduce

- Turn on the `tracesSampler` sample rate to 1.0 (any amount will do it but this is the fastest repro
- Launch app
- App launch will nondeterministically hang 
- Stack trace points to a Sentry lock

![Screenshot 2023-09-15 at 10 07 40 AM](https://github.com/getsentry/sentry-cocoa/assets/2514882/728d79a1-e3fe-4e1f-8f1a-b91432c59088)

### Expected Result

.... no deadlock on main thread

### Actual Result

Deadlock on main thread

**Comment by brustolin** [comment] 2023-09-20 07:46
Duplicate of #3277.
Please follow the other issue for updates.

**Closed by brustolin** 2023-09-20 07:46 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
