### ISSUE TITLE
Dynamic xcframework crashes on load when running in Mac catalyst app

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#3770] opened 2024-03-20 04:43 UTC
### Platform

macOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.22.2

### Steps to Reproduce

Xcode 15.3
Integrate Sentry using SPM and select the Dynamic version
Run the app

### Expected Result

Expect the app to run

### Actual Result

App crashes with 

`dyld[31816]: Library not loaded: @rpath/Sentry.framework/Versions/A/Sentry Referenced from: <56C2FE8C-A226-3E73-8DF3-A69B2DE114BA> /Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/Frameworks/WBDKit.framework/Versions/A/WBDKit Reason: tried: '/Users/gabor/Library/Developer/Xcode/DerivedData/Screeners-fbzbdqgslszigydfrilfmdsrybwh/Build/Products/Debug-maccatalyst/Sentry.framework/Versions/A/Sentry' (code signature in <85240F3B-DDA3-3DE4-9F69-F1CB0CB9E3EE> `

**Comment by philipphofmann** [comment] 2024-03-20 07:59
@gabors, I just included the SDK to an empty project with SwiftUI for Mac Catalyst and couldn't reproduce the problem. Can you please provide a repro or share more information on your project setup so we can reproduce the issue?

**Comment by brustolin** [comment] 2024-03-21 07:30
Hello @gabors, can you try our new alpha release and let us know if the problem persist to you?
https://github.com/getsentry/sentry-cocoa/releases/tag/8.22.3-beta.0

**Comment by gabors** [comment] 2024-03-21 17:01
@brustolin will do thanks

**Comment by gabors** [comment] 2024-03-21 17:05
@philipphofmann TBH my project setup is somewhat more complex.  Sentry is added as a dependency to a dynamic framework in the same project as targets.  Then my dynamic framework is used  in several targets. Below is an illustration how this works with v 8.21

<img width="779" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/4fde47ae-42d0-46fc-863b-65d5acac2918">

**Comment by gabors** [comment] 2024-03-21 19:11
@brustolin same problem with the beta for me

<img width="1564" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/e8b0d2d1-e181-46cd-9a05-1e569d546ff5">
<img width="1564" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/e5238d22-9a2e-4835-b07d-e2fd1de19ef4">

**Comment by brustolin** [comment] 2024-03-22 10:44
Hello @gabors. Is this WBDKit library a static library?
I believe you will need to add Sentry dependency to your app, so it ensures the framework will be embedded in it.

Adding Sentry to a library or framework is not officially supported.

**Comment by gabors** [comment] 2024-03-22 12:41
That's not a viable real life suggestion @brustolin 
Logging to sentry happens in the shared code. 

Anyway this approach worked for years with original swift pm setup and with Carthage prior to that. 

And it still works today if using  your static libraries. 
But I wanted to use dynamic as your static libraries are making my apps bigger quite noticeably. 

It would be good if you added another target in the package file to allow integrating using source files rather than binaries. As before. 
Cc @philipphofmann

**Comment by brustolin** [comment] 2024-03-25 07:23
Thanks for the extra information @gabors 

By adding it to you app you guarantee that it will be shipped with the app, you dont need to add the log logic into the app, you can still using it the way you're doing right now.

We can't have a target that uses source code because SPM dont support multi-language projects, and we are introducing Swift into Sentry SDK alongside objc code.
Another alternative is cocoapods that still uses the source code. 

Im sorry for all the inconvenience.

**Comment by gabors** [comment] 2024-03-25 07:42
@brustolin I tried adding sentry dynamic to the app target in addition to the framework target. 
Unfortunately results were bad in both iOS and macOS catalyst builds. 
In one case AppStore connect rejected the binary in other there I think sentry didn't get included properly. 
I need to do it again to get the specifics. 

Tbh I don't like where this sdk is going and we may be forced to look for alternatives at WB. 

Swift only would be great but afaik that would not include crash detection and reporting so that's a non starter for us. 

Take a look at the Mux analytics iOS sdk. It also has binary targets from what I recall and integrates amazingly well.

**Comment by brustolin** [comment] 2024-03-25 08:17
> In one case AppStore connect rejected the binary 

This was really a problem, that we solved in the 8.22.3

> in other there I think sentry didn't get included properly.

Can you give us more information on this?

**Comment by brustolin** [comment] 2024-03-25 15:29
I checked the Mux analytics to understand if its possible to make it work, but I got the same error:

![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/d6b3a053-6f92-4f3b-86ca-7e698b6c54b6)

This is either an Xcode bug that is not including embedding nested dependencies into the final app, or its how Apple wants it to work, but as far as I know, its necessary to add the dependency to the main app so it gets in the bundle. 

I dont understand how can your app get bigger with static framework, I had the opposite result.
Linked with static:
![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/5e886a3c-f74f-4229-8180-83fbb9cf67c1)

Linked with dynamic:
![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/3271bdb6-ae83-427f-9385-041ae14ca1e7)

And this is indeed the expected outcome.

Im really sorry about all the trouble of the new changes.

**Comment by gabors** [comment] 2024-03-25 17:09
Hi @brustolin I just tried again to integrate Sentry using the latest tag of 8.22.4 as a static framework and indeed the file sizes did not go up this time for iOS, tvOS and macOS: :)
This looks good.

<img width="360" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/1b57ecac-7c6e-49bd-9dac-b614155a5d0a">

With one of the initial 8.22.x releases the iOS and tvOS sizes were same but macOS went up by 10% (~3MB)

**Comment by gabors** [comment] 2024-03-25 18:41
@brustolin I noticed these warnings during build, is it something to worry about / fix?

<img width="1199" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/563606f6-adc3-47eb-a33d-8413e10ddd4f">

**Comment by brustolin** [comment] 2024-03-26 07:59
>  I noticed these warnings during build, is it something to worry about / fix?

This Carthage folder is not part of the project. This is a cache folder that we use in CI to build the framework.
Have you ever run `make build-xcframework` by any chance?

You can delete this folder if you dont want to see this warnings.

> Hi @brustolin I just tried again to integrate Sentry using the latest tag of 8.22.4 as a static framework and indeed the file sizes did not go up this time for iOS, tvOS and macOS: :)

Can we close this issue then?

**Comment by gabors** [comment] 2024-03-26 08:12
@brustolin I did not run that script. 
Only added sentry via spm. 

That path is from your build system by the looks of it. 

Same warnings are thrown when I build my project on Xcode cloud. So definitely I did not run your build script. 

I opened a separate issue for this. It has more details so you can close this issue.

**Closed** 2024-03-26 08:15 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
