### ISSUE TITLE
Upload crashes using a background URLSession

### ISSUE THREAD

**Issue by CraigSiemens** [getsentry/sentry-cocoa#271] opened 2018-12-06 22:59 UTC
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 4.2.1
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.0**

---
I have following issue:
If the app is stuck in a state where it crashes on launch, the crashes are never sent to sentry. These types of crashes do appear on Crashlytics.

>  If your app is running on an OS that supports it (OS X 10.9+, iOS 7.0+), Crashlytics will submit most reports using out-of-process background networking operations. This results in a significant improvement in reliability of reporting, as well as power and performance wins for your users.

Source: Crashlytics.h

**Steps to reproduce:**
```
Client.shared = try Client(dsn: "...")
try Client.shared?.startCrashHandler()
Client.shared?.crash()
 ```
**Actual result:**
Crash logs never show up on sentry until the bug is fixed and deployed to the app that is crashing

**Expected result:**
Sentry should create the network request to upload the crash by using a background `URLSession`. This would allow the system to handle uploading the crash even if the app is unable to run.

**Comment by HazAT** [comment] 2018-12-07 08:54
Hmm, we are using `NSURLSession` but with `ephemeralSessionConfiguration`.
Not sure, maybe we want to switch to `backgroundSessionConfigurationWithIdentifier`.

https://github.com/getsentry/sentry-cocoa/blob/8e4791a770d725a7d95074a74ecb43001c0686ab/Sources/Sentry/SentryClient.m#L75-L76

**Comment by CraigSiemens** [comment] 2018-12-07 19:12
That would be part of the required change. Background session also don't support completion handlers or data tasks. It would need to be changed to use the URLSessionDelegate methods and upload/download tasks. Using delegate methods would be a bit of work since it's already using completion blocks but swiping to upload tasks should be easy sing your already writing a file to disk which is required for background uploads.

https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background
(Also applies to uploads)

**Comment by fetzig** [comment] 2020-01-09 13:43
> NOTE: crashlytics code https://github.com/firebase/firebase-ios-sdk/search?q=backgroundSessionConfigurationWithIdentifier&unscoped_q=backgroundSessionConfigurationWithIdentifier BOOOM!

**Comment by philipphofmann** [comment] 2020-12-29 16:08
This issue could be fixed with fixing https://github.com/getsentry/sentry-cocoa/issues/316

**Comment by philipphofmann** [comment] 2021-12-15 13:25
This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/316.

**Closed by philipphofmann** 2021-12-15 13:25 UTC
Labels: Effort: Medium, Status: Backlog, Component: Crashes
