### ISSUE TITLE
App getting crash due to sentry SDK>[SentryMetricProfiler clear]

### ISSUE THREAD

**Issue by arnavgupta180** [getsentry/sentry-cocoa#4615] opened 2024-12-10 11:42 UTC
### Platform

macOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.36

### Xcode Version

15.4

### Steps to Reproduce
```

Thread 0 Crashed:
0   libsystem_kernel.dylib               0x00007ff80fd09b52 __pthread_kill + 10
1   libsystem_pthread.dylib              0x00007ff80fd43f85 pthread_kill + 261
2   libsystem_c.dylib                    0x00007ff80fc64b19 abort + 125
3   libsystem_malloc.dylib               0x00007ff80fb63975 malloc_vreport + 856
4   libsystem_malloc.dylib               0x00007ff80fb8b3aa malloc_zone_error + 182
5   CoreFoundation                       0x00007ff80fdcd180 0x7ff80fdad000 + 131456
6   Sentry                               0x000000010c7a550c -[SentryMetricProfiler clear] (SentryMetricProfiler.mm:214)
7   Sentry                               0x000000010c75fe9c (anonymous namespace)::_sentry_threadUnsafe_transmitChunkEnvelope() (SentryContinuousProfiler.mm:54)
8   Sentry                               0x000000010c760342 +[SentryContinuousProfiler timerExpired] (SentryContinuousProfiler.mm:169)
9   Foundation                           0x00007ff810e8e830 __NSFireTimer + 66
10  CoreFoundation                       0x00007ff80fe41b3e 0x7ff80fdad000 + 609086
11  CoreFoundation                       0x00007ff80fe416ec 0x7ff80fdad000 + 607980
12  CoreFoundation                       0x00007ff80fe41318 0x7ff80fdad000 + 607000
13  CoreFoundation                       0x00007ff80fe27f93 0x7ff80fdad000 + 503699
14  CoreFoundation                       0x00007ff80fe2708e 0x7ff80fdad000 + 499854
15  HIToolbox                            0x00007ff81b540ec3 RunCurrentEventLoopInMode + 291
16  HIToolbox                            0x00007ff81b5468a4 ReceiveNextEventCommon + 645
17  HIToolbox                            0x00007ff81b546a42 _BlockUntilNextEventMatchingListInModeWithFilter + 65
18  AppKit                               0x00007ff813741b7f _DPSNextEvent + 901
19  AppKit                               0x00007ff8141766b4 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1289
20  AppKit                               0x00007ff813732c59 -[NSApplication run] + 609
21  AppKit                               0x00007ff813705f96 NSApplicationMain + 822
22  ???                                  0x00007ff80f9b62cd 0x0 + 0
```

### Expected Result

App should not crash

### Actual Result

App is crashing

**Comment by philipphofmann** [comment] 2024-12-11 16:10
Duplicate of https://github.com/getsentry/sentry-cocoa/issues/4607.

**Closed by philipphofmann** 2024-12-11 16:10 UTC
Labels: Type: Bug, Platform: Cocoa
