### ISSUE TITLE
SentryDispatchQueueWrapper.m - 第 66 行

### ISSUE THREAD

**Issue by shenyinghao** [getsentry/sentry-cocoa#2756] opened 2023-03-06 06:56 UTC
### Platform

iOS

### Installed

CocoaPods

### Version

8.1.0

### Steps to Reproduce

Crash平台统计的内容

SentryDispatchQueueWrapper.m - 第 66 行
__50-[SentryDispatchQueueWrapper dispatchAfter:block:]_block_invoke + 66

### Expected Result

不崩溃

### Actual Result

出现崩溃

**Comment by brustolin** [comment] 2023-03-06 09:32
Hi, can you share the crash message with us?

**Comment by shenyinghao** [comment] 2023-03-08 12:36
0
libobjc.A.dylib
objc_release_x0 + 16
1
libobjc.A.dylib
objc_release + 16
2
CIDER
SentryDispatchQueueWrapper.m - 第 68 行
-[SentryDispatchQueueWrapper dispatchAfter:block:] + 68
3
CIDER
SentryTracer.m - 第 223 行
-[SentryTracer dispatchIdleTimeout] + 223
4
CIDER
SentryTracer.m - 第 354 行
-[SentryTracer spanFinished:] + 354
5
CIDER
SentrySpan.m - 第 157 行
-[SentrySpan finishWithStatus:] + 157
6
CIDER
SentryNetworkTracker.m - 第 290 行
-[SentryNetworkTracker urlSessionTask:setState:] + 290
7
CIDER
SentryNetworkTrackingIntegration.m - 第 72 行
__57+[SentryNetworkTrackingIntegration swizzleURLSessionTask]_block_invoke_2.27 + 72

**Comment by philipphofmann** [comment] 2023-03-14 10:20
@shenyinghao, what's the error message / exception you get? Looking at the stacktrace, I believe #2697 released with 8.2.0 should fix this issue.

**Comment by brustolin** [comment] 2023-03-22 13:36
This is a duplicate of #2769

**Closed by brustolin** 2023-03-22 13:37 UTC
Labels: Type: Bug, Platform: Cocoa
