### ISSUE TITLE
Incorrect OS name (for macOS catalyst, tvOS) when sending a message.

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#361] opened 2020-01-05 05:51 UTC
_Platform:_
- [ ]  iOS
- [x]  tvOS
- [x]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes ->5.1
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually
- [x] SPM

Version of sentry-cocoa:
**4.4.3**

---
I have following issue:

When events are recorded for a tvOS app, some of the tags are reporting incorrect values (in **bold**):
app.device
343e50a9fc93094362b0d6b4449aff10aa982ecc
device
Apple TV 4K
device.family
tvOS
environment
TestFlight
level
error
os
**iOS 13.3**
os.name
**iOS**

Also it seems in the stack trace area the crashed value is always **yes**.  Even though the app never crashed.

Similarly for Mac Catalyst OS name is wrong:

device
x86_64
device.family
Mac
environment
AppStore
level
error
os
**iOS 10.15.2**
os.name
**iOS**

**Comment by fetzig** [comment] 2020-01-08 16:12
Hi @gabors 

TTBOMK this can't happen within the SDK. Additionally, I checked sentry events on the sentry.io dashboard last month (specifically to check if those values make sense). I could only find shortcomings if events are sent from the simulator. So I'm pretty confident I can't reproduce this or nail this bug down without your help.

The wrong values are from the sentry.io dashboard - correct? 

If so - to go further it would be great if you could send the verbose log (which contains the sent sentry event). Verbose logging can be activated like this:
```
do {
    Client.shared = try Client(dsn: "___PUBLIC_DSN___") // "https://<key>@sentry.io/<project>"
    try Client.shared?.startCrashHandler()

    // sets log level for console
    Client.logLevel = .verbose
} catch let error {
    print("\(error)")
    // Wrong DSN or KSCrash not installed
}
```

This way we could verify if the values are already wrong when sent by the SDK/client.

thx.

**Comment by gabors** [comment] 2020-01-08 16:42
@fetzig thanks for looking into this. Yes the incorrect values are showing in the events in the sentry dashboard. And they come from physical devices. Not simulator. 
I will enable verbose logging as per your instructions. Where can I send the output?

**Comment by fetzig** [comment] 2020-01-08 16:52
Great. 

If you don’t want to post it here, you can sent me an email (see GitHub profile @fetzig)

**Comment by gabors** [comment] 2020-01-08 16:59
`"platform" : "cocoa",
  "contexts" : {
    "os" : {
      "build" : "17K449",
      "rooted" : false,
      "kernel_version" : "Darwin Kernel Version 19.2.0: Mon Nov  4 17:09:53 PST 2019; root:xnu-6153.60.66~31\/RELEASE_ARM64_T8011",
      "name" : "iOS",
      "version" : "13.3"
    },
    "app" : {
      "app_id" : "456BD6B2-A1D0-36FD-8329-E0668DF2B3D9",
      "app_version" : "2020.1.0",
      "app_identifier" : "com.wbtvd.tvos-app",
      "app_start_time" : "2020-01-08T16:55:31Z",
      "device_app_hash" : "a9abc38f893f0a355c8058a165826de61af7079e",
      "app_build" : "0",
      "build_type" : "debug",
      "app_name" : "WBTVD"
    },
    "device" : {
      "free_memory" : 710164480,
      "model_id" : "J105aAP",
      "arch" : "arm64",
      "memory_size" : 3181379584,
      "family" : "tvOS",
      "model" : "AppleTV6,2",
      "storage_size" : 63842713600,
      "boot_time" : "2019-12-10T18:50:36Z",
      "timezone" : "MST",
      "usable_memory" : 2833268736
    }
  },
  "sdk" : {
    "name" : "sentry-cocoa",
    "version" : "4.4.3"
  },`

**Comment by gabors** [comment] 2020-01-08 17:01
@fetzig as you can see above the device data seems correct, but the os data refers to iOS :)

**Comment by gabors** [comment] 2020-01-08 17:07
@fetzig 

I believe this json is reporting the error log event as a crash, even though it was not a crash, just a normal log of an error


```"level" : "error",
  "threads" : {
    "values" : [
      {
        "id" : 0,
        "current" : true,
        "crashed" : true,
        "stacktrace" : {
          "frames" : [
            {
              "package" : "\/usr\/lib\/system\/libdyld.dylib",
              "symbol_addr" : "0x00000001bf52e5f4",
              "image_addr" : "0x00000001bf52b000",
              "function" : "<redacted>",
              "instruction_addr" : "0x00000001bf52e5f8"
            },
            {
              "package" : "\/private\/var\/containers\/Bundle\/Application\/E5330849-D036-4AC0-BAB3-37B14CEE2F8C\/WBTVD.app\/WBTVD",
              "symbol_addr" : "0x0000000100477d28",
              "image_addr" : "0x00000001003ec000",
              "function" : "main",
              "instruction_addr" : "0x0000000100477d74"
            },```

**Comment by fetzig** [comment] 2020-01-10 09:16
thx for the data. I will try to check this out next week, but can't give any guarantees. everybody is invited to make PRs :)

**Comment by gabors** [comment] 2020-01-12 07:01
@fetzig 
Interesting that you have this code, which looks correct 

from SentryContext.m

```- (NSDictionary<NSString *, id> *)generatedOsContext {
    NSMutableDictionary *serializedData = [NSMutableDictionary new];

#if TARGET_OS_IPHONE
    [serializedData setValue:@"iOS" forKey:@"name"];
#elif TARGET_OS_OSX
    [serializedData setValue:@"macOS" forKey:@"name"];
#elif TARGET_OS_TV
    [serializedData setValue:@"tvOS" forKey:@"name"];
#elif TARGET_OS_WATCH
    [serializedData setValue:@"watchOS" forKey:@"name"];
#endif

**Comment by gabors** [comment] 2020-01-12 07:15
@fetzig 

I think I found the issue, in SentryContext.m we have

```#if TARGET_OS_IPHONE
    [serializedData setValue:@"iOS" forKey:@"name"];
#elif TARGET_OS_OSX
    [serializedData setValue:@"macOS" forKey:@"name"];
#elif TARGET_OS_TV
    [serializedData setValue:@"tvOS" forKey:@"name"];
#elif TARGET_OS_WATCH
    [serializedData setValue:@"watchOS" forKey:@"name"];
#endif```

but `TARGET_OS_IPHONE` macro is also defined when running tvOS, as per this:
https://stackoverflow.com/questions/12132933/preprocessor-macro-for-os-x-targets

So to me it seems that the correct way would be

```#if TARGET_OS_IOS
    [serializedData setValue:@"iOS" forKey:@"name"];
#elif TARGET_OS_OSX || TARGET_OS_MACCATALYST
    [serializedData setValue:@"macOS" forKey:@"name"];
#elif TARGET_OS_TV
    [serializedData setValue:@"tvOS" forKey:@"name"];
#elif TARGET_OS_WATCH
    [serializedData setValue:@"watchOS" forKey:@"name"];
#endif```

**Comment by fetzig** [comment] 2020-01-13 14:03
> @fetzig
> 
> I believe this json is reporting the error log event as a crash, even though it was not a crash, just a normal log of an error
> ...

@gabors was unable to reproduce this since I was always testing with actual crashes. which works fine (os.name=tvOS). rereading your comments, I realized this happens when sending events/messages manually. Now I finally got it reproduced and verified.

But to figure out what's wrong with the crash:true value, we have to dig deeper.

Can you create a new ticket for this and add the code responsible for creating the event (error log) you want to send?

Thanks for your contributions so far.

**Comment by fetzig** [comment] 2020-01-14 14:53
@gabors thx for your contribution. just merged the changes to `master`. I will close this issue now and expect to release `4.4.4` by the end of the week.

**Closed by fetzig** 2020-01-14 14:53 UTC

**Comment by gabors** [comment] 2020-01-14 18:18
Perfect, thanks for having the SDK source available @fetzig
