### ISSUE TITLE
sentry-cocoa is causing "App Hanging"

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#2791] opened 2023-03-14 01:28 UTC
### Platform

iOS

### Installed

CocoaPods

### Version

8.2.0

### Steps to Reproduce

1. Use the app
2. Wait for App Hang

### Expected Result

Not to hang

### Actual Result

<img width="984" alt="screenshot-2023-03-13-18 27 13@2x" src="https://user-images.githubusercontent.com/470/224868738-9527f2bf-1fb9-407c-bd0c-d06ba0e160b5.png">

**Comment by brustolin** [comment] 2023-03-14 08:03
Hello @eric, with only the stacktrace is hard to tell what's going on.
What is the error message of this event?
Do you mind sharing the json of this event?

**Comment by philipphofmann** [comment] 2023-03-14 08:50
Thanks for reporting this, @eric. How often do you see this?

It could be that the Sentry SDK is not causing the app hangs if it's actually an app hang, but our logic might fire too late, and the SDK could attach a stacktrace that doesn't map to the root cause of the app hang, see https://github.com/getsentry/sentry-cocoa/discussions/2715#discussioncomment-5091072.

Either we improve our app hang logic to collect the correct stack or change it to only report app hangs when we can collect the proper stack trace.

**Comment by philipphofmann** [comment] 2023-03-14 09:30
We moved updating the app state to a background thread with https://github.com/getsentry/sentry-cocoa/pull/2793, so the SDK won't report AppHangs with the stack trace pointing to the sentry-cocoa SDK as you pointed out above, @eric. Before closing this issue I would like to ensure that our SDK is not causing app hangs, but instead attaching wrong stack traces to app hangs.

**Comment by eric** [comment] 2023-03-14 18:51
> How often do you see this?

It's hard to say how often, because these traces have been grouped in an "App Hanging" issue that contains 120 events all of which contain no app stack frames beyond `main()`. I saw it at least a few times when I was looking.

**Closed** 2023-03-15 15:47 UTC
Labels: Type: Bug, Platform: Cocoa
