### ISSUE TITLE
Could not decode report: Incomplete data

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cocoa#369] opened 2020-01-08 20:15 UTC
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.2**

---
I have following issue:

```
2020-01-08 15:11:17.622466-0500 Volto[10439:3733015] Sentry Started -- Version: 4.4.2
2020-01-08 15:11:17.624244-0500 Volto[10439:3733015] Sentry - Debug:: Add breadcrumb: <SentryBreadcrumb: 0x1651a2c20>
2020-01-08 15:11:17.626509-0500 Volto[10439:3733015] Sentry - Debug:: Writing to file: /var/mobile/Containers/Data/Application/6D4AE964-3FB7-46EF-AB68-574C6B41585D/Library/Caches/io.sentry/fd242f552f8fc4049873fdb8391a76a1ae0ddcc9/breadcrumbs/1578514277.626455-0-533F16E4-447F-41E5-B0AB-7CAEEF0D644A.json
2020-01-08 15:11:17.659920-0500 Volto[10439:3733015] Sentry - Debug:: Removed 1 file(s) from <breadcrumbs>
2020-01-08 15:11:17.670994-0500 Volto[10439:3733015] Sentry - Debug:: SentryCrashHandler started
ERROR: SentryCrashReportFixer.c (272): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Incomplete data
ERROR: SentryCrashC.c (281): char *sentrycrash_readReport(int64_t): Failed to fixup report ID 2e000000
2020-01-08 15:11:17.698515-0500 Volto[10439:3733015] Sentry - Debug:: Sent 0 crash report(s)
```

**Steps to reproduce:**
- Without the debugger attached, force a crash using `fatalError( "Forced Crash" )`

**Actual result:**
Sentry is unable to decode the crash report and submits nothing - logs provide no useful route to understanding what's gone wrong.

**Expected result:**
The crash report is submitted to sentry.io

**Comment by lhunath** [comment] 2020-01-08 20:20
Sentry is initialized in `func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool`

App is crashed in:
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        fatalError( "Forced Crash" )
    }
```

**Comment by fetzig** [comment] 2020-01-09 12:08
(guess this is without bugsnag installed as well, correct?)

The supported/correct way would be to put the sentry install/init code in `didFinishLaunchingWithOptions`. Guess `willFinishLaunchingWithOptions` is ok.

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    
    ...
    
    Sentry.Client.logLevel = .verbose
    Sentry.Client.shared = try? Sentry.Client( dsn: "<private>" )
    try? Sentry.Client.shared?.startCrashHandler()

    fatalError( "Forced Crash" )
    return true
}
```

In some cases, crashes that happen very early in the app lifecycle, can't be caught (and sent to the server). That's not great at all, but it doesn't work when the crash happens so soon (first line in `didFinishLaunchingWithOptions`).

yet I couldn't reproduce your error message `Could not decode report: Incomplete data`.

**Comment by fetzig** [comment] 2020-01-09 14:42
is it possible that your event has a relatively big payload? if so. possible duplicate of #327

**Comment by lhunath** [comment] 2020-01-09 15:10
I was unable to reproduce this in a test project.

After much work of slowly reducing my app down bit-by-bit to a copy of the test project, I finally discovered the two ingredients necessary to make this issue reproducible:

You must have both the Address Sanitizer AND Undefined Behavior Sanitizer enabled.  Note that the latter needs to be enabled EVEN when your project is Swift-only (meaning it will be grayed out in Xcode - you'll need to enable it in the xcscheme file itself).

**Comment by fetzig** [comment] 2020-01-09 16:05
Thanks for clearing that up.

**Comment by lhunath** [comment] 2020-01-09 16:16
With this issue closed, can I expect the next version of Sentry to work reliably with the sanitizers enabled?

**Comment by fetzig** [comment] 2020-01-09 19:04
Oh sorry. Thought we were on the same page. 

Diagnostic/debug/profiling features don’t play well with sentry(-cocoa). Same with debugger or running it in simulator. Since sentry is intended for production envs (no debugger, diagnostics a.s.o), this is nothing we have on our radar. 

Thought you realized that as well. That’s why I closed the issue. (Even though it might be possible to add this as a feature. )

Happy to take PRs for that, but from my current perspective it’s no issue I can or will jump on myself.

**Comment by lhunath** [comment] 2020-01-09 19:48
I suppose that's fair reasoning.  Though I'd worry a tiny bit about whether this is a red flag suggesting that there might be a fragility in the stack resolution / report generation code that might get triggered by other situations as well.  Up to you - unfortunately I haven't the resources to chase this rabbit to the end.

**Closed** 2020-01-09 19:57 UTC
