### ISSUE TITLE
Crash when upgrading from SDK version 6.0.9 to 6.2.1

### ISSUE THREAD

**Issue by NeilJaphtha** [getsentry/sentry-cocoa#1049] opened 2021-04-13 10:41 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
6.2.1

### Steps to Reproduce

1. Use the `sentry-cocoa` version **6.0.9** in an app, extensively.
2. Upgrade to **6.2.1** using cocoapods and update application

### Expected Result
1. App starts without crashing

### Actual Result
1. App starts and crashes with the following message
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'`

### Additional information
1. I can't recreate this simply using these steps.  I experienced this on a couple of simulators where I had used the prior framework extensively.  Based on the error messaging this is related to persistence and underlying model changes.
2. I believe this is something caused by persistence that the SDK does.

**Comment by bruno-garcia** [comment] 2021-04-13 15:06
@NeilJaphtha could you please share the stack trace? Where is this happening?

**Comment by NeilJaphtha** [comment] 2021-04-13 15:58
`2021-04-13 16:42:37.370421+0100 Zego[90526:22031879] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2049e77f _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff204a9ec4 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5 + 0
	4   CoreFoundation                      0x00007fff2048ccb7 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 235
	5   CoreFoundation                      0x00007fff20420773 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
	6   Sentry                              0x00000001082b3fbd -[SentrySession serialize] + 229
	7   Sentry                              0x00000001082a0a26 -[SentryEnvelopeItem initWithSession:] + 51
	8   Sentry                              0x00000001082a0c93 -[SentryEnvelope initWithSession:] + 74
	9   Sentry                              0x00000001082788e9 -[SentryClient captureSession:] + 188
	10  Sentry                              0x00000001082a7ba9 -[SentryHub closeCachedSessionWithTimestamp:] + 649
	11  Sentry                              0x00000001082b4b55 -[SentrySessionTracker endCachedSession] + 263
	12  Sentry                              0x00000001082b491e -[SentrySessionTracker start] + 82
	13  Sentry                              0x0000000108275791 -[SentryAutoSessionTrackingIntegration installWithOptions:] + 145
	14  Sentry                              0x00000001082b1d39 +[SentrySDK installIntegrations] + 853
	15  Sentry                              0x00000001082b0cf6 +[SentrySDK startWithOptionsObject:] + 318
	16  Sentry                              0x00000001082b0d80 +[SentrySDK startWithConfigureOptions:] + 111`

**Comment by bruno-garcia** [comment] 2021-04-13 17:13
Thanks you for raising this @NeilJaphtha.
We'll take a look asap

**Comment by bruno-garcia** [comment] 2021-04-13 17:14
Meanwhile do you mind trying to reproduce it with our latest beta? `7.0.0-beta.0`: https://github.com/getsentry/sentry-cocoa/releases/tag/7.0.0-beta.0

**Comment by NeilJaphtha** [comment] 2021-04-21 09:10
Hey Bruno, thanks for this.  Will check out the new beta and get back to you!

**Comment by bruno-garcia** [comment] 2021-04-27 22:12
We just released 7.0.0 today. Let us know if this helps

**Comment by philipphofmann** [comment] 2021-04-28 13:05
It seems like we are trying to insert `nil` into a dictionary literal in [SentrySession](https://github.com/getsentry/sentry-cocoa/blob/6.2.1/Sources/Sentry/SentrySession.m#L180-L185). 
```Objective-C
NSMutableDictionary *serializedData = @{
    @"sid" : _sessionId.UUIDString,
    @"errors" : @(_errors),
    @"started" : [_started sentry_toIso8601String],
}
                                          .mutableCopy;
```

`[__NSPlaceholderDictionary initWithObjects:forKeys:count:]` I think is called when creating a dictionary like this. You get the exact error when you try to insert `nil`. What I don't understand is how one of the above values can be `nil` as in 6.2.0 we pushed a fix for this https://github.com/getsentry/sentry-cocoa/pull/939.

Need to take a closer look again.

**Comment by NeilJaphtha** [comment] 2021-05-05 10:24
Sweet thanks team!  I'm updating the SDK today and I'll get back to you in the next wee If I have any reoccurring issues. 👍

**Comment by philipphofmann** [comment] 2021-07-19 07:03
I'm closing this due to inactivity. Feel free to open it again.

**Closed by philipphofmann** 2021-07-19 07:03 UTC
Labels: bug
