### ISSUE TITLE
Sentry crashes on Launch, trying to serialize a broken session object

### ISSUE THREAD

**Issue by diederich** [getsentry/sentry-cocoa#937] opened 2021-02-08 12:26 UTC
### Environment

* How do you use Sentry: Sentry SaaS (sentry.io)
* Which SDK and version: 6.1.4 - macOS

### Steps to Reproduce

* (unknown: app crashes / closed in a weird state - )
* launch app & initialize sentry

### Expected Result

* SDK should not crash the app

### Actual Result

* crashes trying to create Session object from a broken dictionary on disc

----

While we haven't figured out how the broken dictionary lands on disc, we can see the crash happening on app launch.
Here's the relevant backtrace:

```
#5	0x00000001025be812 in -[SentrySession serialize] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentrySession.m:129
#6	0x000000010259f726 in -[SentryEnvelopeItem initWithSession:] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryEnvelope.m:122
#7	0x000000010259fb2a in -[SentryEnvelope initWithSession:] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryEnvelope.m:158
#8	0x000000010258fe22 in -[SentryClient captureSession:] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryClient.m:258
#9	0x00000001025aafd7 in -[SentryHub closeCachedSessionWithTimestamp:] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryHub.m:147
#10	0x00000001025bfc8d in -[SentrySessionTracker endCachedSession] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentrySessionTracker.m:110
#11	0x00000001025bf979 in -[SentrySessionTracker start] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentrySessionTracker.m:70
#12	0x000000010258bff5 in -[SentryAutoSessionTrackingIntegration installWithOptions:] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentryAutoSessionTrackingIntegration.m:27
#13	0x00000001025b646c in +[SentrySDK installIntegrations] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentrySDK.m:241
#14	0x00000001025b4e0f in +[SentrySDK startWithOptionsObject:] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentrySDK.m:82
#15	0x00000001025b4eb6 in +[SentrySDK startWithConfigureOptions:] at /<derived-data-and-app>/SourcePackages/checkouts/sentry-cocoa/Sources/Sentry/SentrySDK.m:89
[...]
```

The crash itself is happening in the serialize method:
```
- (NSDictionary<NSString *, id> *)serialize
{
    @synchronized(self) {
        NSMutableDictionary *serializedData = @{
            @"sid" : _sessionId.UUIDString,
            @"errors" : @(_errors),
            @"started" : [_started sentry_toIso8601String],
        }
                                                  .mutableCopy;
```

trying to insert a nil value into the dictionary. `_started` is nil in case of the broken cached Session dictionary on disc.
I haven't dug any deeper, but it feels like the SDK could be more robust in case of broken cached data on disc.  
(We haven't been able to figure out *why* there's the broken dictionary on disc though..).

Is there anything else we can provide? 
Thanks for looking into this!

**Comment by diederich** [comment] 2021-02-08 12:27
There's a similar (but different) issue regarding a crash on startup here: https://github.com/getsentry/sentry-cocoa/issues/738

**Comment by philipphofmann** [comment] 2021-02-08 15:58
Thanks for reporting this, @diederich. This should be an easy fix. I already opened up a PR for this https://github.com/getsentry/sentry-cocoa/pull/939.

**Comment by diederich** [comment] 2021-02-08 16:06
@philipphofmann Thanks for looking into this!
For us, `_startedDate` was nil already, it wasn't present in the stored JSON, so I *think* the PR would not fix it.

It looks like `Session` expects `_startedDate` is required to be non-nil, otherwise `- (NSDictionary*) serialize` will still crash?

**Comment by philipphofmann** [comment] 2021-02-08 16:23
Yes, `_started` is `nonnull` and gets initialized in `initDefault`. We only write to the property in `initWithJSONObject`. If the JSON contains some garbage like `"started": "20"` the SDK set `_started` to `nil`. This is fixed now. 

If the JSON doesn't contain a `"started"` we set it to the current date anyway, but this was already the case, see 
https://github.com/getsentry/sentry-cocoa/blob/1354752dccabb270543311d544d9a35f16f1123d/Tests/SentryTests/SentrySessionTests.swift#L52-L72

Does this make sense or do you think that this still won't save your problem?

**Comment by diederich** [comment] 2021-02-08 16:39
Ohhh, good call. Thanks for the explanation. Yes, that makes all sense, and yes, it should be fixed with the PR! 🙏

**Comment by philipphofmann** [comment] 2021-02-09 11:52
> Steps to Reproduce
> (unknown: app crashes / closed in a weird state - )
> launch app & initialize sentry

How often did you encounter this issue @diederich? Can you maybe give us more detail, so we can fix the root cause of this?

**Comment by diederich** [comment] 2021-02-09 12:45
We haven't been able to clearly repro this, but we'll try. My hunch right now is, that this happens in debug sessions, when we kill the process "at the wrong moment".

**Comment by philipphofmann** [comment] 2021-02-09 16:31
Thanks for the input, @diederich. In such a case, I think it is acceptable to go with our current approach. In the next major, we plan on discarding such sessions as there is not much we can do. See https://github.com/getsentry/sentry-cocoa/discussions/877#discussioncomment-207809.

**Comment by diederich** [comment] 2021-02-09 18:33
Agreed, again - thank you for looking into this!

**Closed** 2021-02-10 10:58 UTC
Labels: bug
