### ISSUE TITLE
Sentry crashed in sentry::profiling::backtrace

### ISSUE THREAD

**Issue by dfed** [getsentry/sentry-cocoa#4148] opened 2024-07-07 14:38 UTC
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.30.0

### Xcode Version

15.4

### Did it work on previous versions?

Unknown

### Steps to Reproduce

Unknown

### Expected Result

Sentry does not crash

### Actual Result

Sentry crashed: https://portola.sentry.io/issues/5579671605/events/58e2d5a68b1044e09953922e2f46dec9/?project=4506735735865344

### Are you willing to submit a PR?

Way out of my depth here

**Comment by kahest** [comment] 2024-07-09 13:39
This is most likely a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3997 - please add additional context you might have there 🙏

**Closed by kahest** 2024-07-09 13:39 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
