### ISSUE TITLE
App crash in the `sliceGPUData`

### ISSUE THREAD

**Issue by anton-plebanovich** [getsentry/sentry-cocoa#3082] opened 2023-06-06 14:28 UTC
### Platform

iOS

### Installed

CocoaPods

### Version

8.6.0

### Steps to Reproduce

The actual steps are unknown but I hope the crash stack trace should be enough. We started to receive a lot of those after we updated from the `8.1.0` version to the `8.6.0` version. It looks like `nearestPredecessorValue` might be `nil` in some cases when an object for `slicedGPUEntries` is created in the `sliceGPUData` function.

```
OS Version: iOS 16.5 (20F66)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 0

Application Specific Information:
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

Thread 0 Crashed:
0   CoreFoundation                  0x32f1f3cb4         __exceptionPreprocess
1   libobjc.A.dylib                 0x32131c3cc         objc_exception_throw
2   CoreFoundation                  0x32f399f80         _CFThrowFormattedException
3   CoreFoundation                  0x32f3a54a8         -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5
4   CoreFoundation                  0x32f20f458         -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5   CoreFoundation                  0x32f20f2f8         +[NSDictionary dictionaryWithObjects:forKeys:count:]
6   Sentry                          0x10473ab2c         sliceGPUData (SentryProfiler.mm:228)
7   Sentry                          0x10473c5a4         +[SentryProfiler createProfilingEnvelopeItemForTransaction:] (SentryProfiler.mm:417)
8   Sentry                          0x104756918         -[SentryTracer captureTransactionWithProfile:] (SentryTracer.m:511)
9   Sentry                          0x1047566ec         -[SentryTracer finishInternal] (SentryTracer.m:499)
10  Sentry                          0x10475502c         -[SentryTracer deadlineTimerFired] (SentryTracer.m:238)
11  Sentry                          0x104754e10         __34-[SentryTracer startDeadlineTimer]_block_invoke (SentryTracer.m:217)
12  Foundation                      0x3237e119c         __NSFireTimer
13  CoreFoundation                  0x32f2b5620         __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
14  CoreFoundation                  0x32f272f48         __CFRunLoopDoTimer
15  CoreFoundation                  0x32f218718         __CFRunLoopDoTimers
16  CoreFoundation                  0x32f2644d0         __CFRunLoopRun
17  CoreFoundation                  0x32f2693e8         CFRunLoopRunSpecific
18  GraphicsServices                0x3a5c71358         GSEventRunModal
19  UIKitCore                       0x3336656e4         -[UIApplication _run]
20  UIKitCore                       0x333665348         UIApplicationMain
21  MyApp                          0x2009c25ec         main (AppDelegate.swift:22)
22  <unknown>                       0x1c773edec         <redacted>
```

### Expected Result

Sentry should not crash the app

### Actual Result

Sentry crashed the app

### Are you willing to submit a PR?

I may try but it will be just a naive check for `nearestPredecessorValue` nullability which might be not good enough

**Comment by brustolin** [comment] 2023-06-07 06:06
Hello @anton-plebanovich, thanks for reaching out. We will investigate this.

**Comment by brustolin** [comment] 2023-06-07 12:17
Meanwhile I would suggest you to try our latest version, we had some bugs fixed for profiling and SentryTracer, maybe they are related.

**Comment by anton-plebanovich** [comment] 2023-06-07 12:22
I checked the latest commit but it looks like the issue might still be there so I decided to postpone my update until better times

**Comment by armcknight** [comment] 2023-06-08 00:17
Hi @anton-plebanovich, thanks for the report, I'm taking a look into the issue now. You're right that the bug is still present and that a simple nil check won't be enough. I'm working to find the cause, stay tuned.

**Comment by armcknight** [comment] 2023-06-08 02:42
Unfortunately I was unable to reproduce it, but I did add some checks that will at least avoid the crash. I'm going to ask for a second pair of eyes on it before merging.

**Comment by armcknight** [comment] 2023-06-23 20:45
@anton-plebanovich , just wanted to update you on progress. We merged a fix that will avoid the crash, but are still investigating how to refactor the implementation to avoid the situation in the first place. The stability issue is resolved, at least!

**Comment by anton-plebanovich** [comment] 2023-06-24 08:47
Thanks 🎉

**Comment by armcknight** [comment] 2023-07-26 17:58
@anton-plebanovich One last update here, we were able to ship the refactor that fixed the threading issues that were the underlying cause. 8.9.3 is the latest stable release with the fixes. Hope things are looking better on your end!

**Closed by armcknight** 2023-07-26 17:58 UTC
Labels: Type: Bug, Platform: Cocoa
