### ISSUE TITLE
Unknown releases in panel

### ISSUE THREAD

**Issue by ialimz** [getsentry/sentry-cocoa#3125] opened 2023-06-29 21:40 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.31.5

### Steps to Reproduce

1. Go to the Releases panel
2. There are unknown releases

### Expected Result

There should be only releases that have been created manually(or after the user launched the app for the first time).

### Actual Result

There are unknown issues with strange bundle identifiers. Each only has one user
<img width="1187" alt="Screenshot 2023-06-30 at 1 01 25 AM" src="https://github.com/getsentry/sentry-cocoa/assets/17988710/514a588f-e9e2-44de-b371-c6badcd4eb89">

**Comment by brustolin** [comment] 2023-06-30 07:25
Hello @ialimz, thanks for reaching out.
This is a duplicate of https://github.com/getsentry/sentry/issues/49071 and you can track the progress there.

If I understood the issue wrong let me know and I reopen this one.

**Closed by brustolin** 2023-06-30 07:25 UTC
Labels: Type: Bug, Platform: Cocoa, Status: Untriaged, Waiting for: Product Owner
