### ISSUE TITLE
tvOS is only reporting the crashes when rebooting the app.

### ISSUE THREAD

**Issue by gholias** [getsentry/sentry-cocoa#1006] opened 2021-03-19 13:45 UTC
### Environment

We are using Sentry in our tvOS app and we can see the custom events in the dashboard, but they are only submitted if we force close the tvOS app and reopen it.
We are using Sentry to notify when the user is having issues with our video streaming. Those events are only sent when `  application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {` is called in the AppDelegate during a cold boot of the app.

Do I need to manually force SentrySDK to push the the events? I could not find anything for this in the docs.

Which SDK and version?
Sentry 6.2.0

### Steps to Reproduce

1 - Open the app, the streaming will start
2 - Cut the internet of the tvOS device
3 - The streaming will stop and we capture the event with `SentrySDK.capture`
4 - Resume the internet in the device

What is happening: 
### Expected Result
 The Capture events are submitted to the Sentry Dashboard as soon as the internet is back.

### Actual Result
The events are not submitted until we force close the app and reopen it

**Comment by philipphofmann** [comment] 2021-03-19 14:16
Hi @gholias., 
After you initialized the SDK and the device is only, it should immediately send an event to Sentry after you call, for example, `Sentry.captureMessage`. Can you maybe share how you configure the SDK without the DSN, of course, and let me know where in your code you initialize the SDK?

Maybe the problem is that we currently don't check when a device gets online again and then try to send the cached events. We wait until we have another event to send and then send all cached events.

**Comment by gholias** [comment] 2021-03-19 14:35
@philipphofmann We are getting the crashes, but only when the app is cold booted. If we call `capture` without internet access, that event is not submitted until we close and reopen the app.

As a workaround, I'm calling `Sentry.start` on `applicationWillEnterForeground` and that is sending the crash events when returning from the background.

This is how Im starting it:
```
// Sentry setup
    SentrySDK.start { options in
      options.dsn = "--DSN--"
         
      #if DEBUG
      options.debug = true
      #endif

      options.beforeSend = { event in
                
        guard let tags = event.tags, tags["MY_CUSTOM_TAG"] != nil else {
          return nil
        }
        return event
      }
      Log.info("Sentry SDK was started")
    }
    ```

**Comment by philipphofmann** [comment] 2021-03-22 10:38
Thanks for the info. 
When you call `capture`, and you don't have an internet connection, the SDK caches the event by storing it to disk. 
We try to send all cached events when
* you call `capture`
* the SDK sends any other information to Sentry, like a session update
* or you start the SDK

According to our [unified API](https://develop.sentry.dev/sdk/unified-api/#client), the SKD should offer a `flush` method, which we don't have yet in this SDK. Is this what you are basically looking for?

**Comment by gholias** [comment] 2021-03-22 12:55
yes, that would be a good workaround to the problem, calling flush when returning from the background.

**Comment by philipphofmann** [comment] 2021-03-22 17:27
I created an issue for flush https://github.com/getsentry/sentry-cocoa/issues/1013. Please upvote there, so we know you want this feature and we can prioritize it properly. I'm going to close this issue now, as it would be a duplicate of `flush`.

**Closed by philipphofmann** 2021-03-22 17:27 UTC
