### ISSUE TITLE
iOS12 SentryBreadcrumb *crumb = [[SentryBreadcrumb alloc] init]; crashed

### ISSUE THREAD

**Issue by LBCross** [getsentry/sentry-cocoa#1000] opened 2021-03-16 08:01 UTC
_Platform:_
- [ ]  iOS

_Swift:_
- [ ]  No

_sentry-cocoa installed with:_
- [ ] Manually

Version of sentry-cocoa:
**6.2.1**

---
I have following issue:

Description goes here ...
iOS12  crashed;
```objective-c
@import Sentry;

SentryBreadcrumb *crumb = [[SentryBreadcrumb alloc] init];
crumb.level = kSentryLevelInfo;
crumb.category = @"auth";
crumb.message = [NSString stringWithFormat:@"Authenticated user %@", user.email];
[SentrySDK addBreadcrumb:crumb];
```
If the phone using IOS 12.0.1 calls the appellate code, it will crash;
![image](https://user-images.githubusercontent.com/19235947/111275171-d866b180-8670-11eb-8bf0-8ea3292f451a.png)

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by LBCross** [comment] 2021-03-16 08:16
![image](https://user-images.githubusercontent.com/19235947/111277047-f7664300-8672-11eb-829f-3212184329a3.png)

**Comment by LBCross** [comment] 2021-03-16 08:16
![Uploading image.png…]()

**Comment by LBCross** [comment] 2021-03-16 08:17
![image](https://user-images.githubusercontent.com/19235947/111277194-211f6a00-8673-11eb-88e5-f8d2c2e02107.png)

**Comment by philipphofmann** [comment] 2021-03-16 16:11
Hey @LBCross, 
I'm sorry, but I can't reproduce your issue. Can you maybe share the issue in Sentry or post the exact error message?

We have several tests to make sure `[[SentryBreadcrumb alloc] init]` and other interactions with `SentryBreadcrumb` work fine.  Can it be that the `key` and `value` you get from the `jsonDict` aren't of type `NSString`? 


Another note: for comparing NSStrings I suggest you use `isEqualToString` instead of `isEqual.`

**Comment by LBCross** [comment] 2021-03-17 02:08
> Hey @LBCross,
> I'm sorry, but I can't reproduce your issue. Can you maybe share the issue in Sentry or post the exact error message?
> 
> We have several tests to make sure `[[SentryBreadcrumb alloc] init]` and other interactions with `SentryBreadcrumb` work fine. Can it be that the `key` and `value` you get from the `jsonDict` aren't of type `NSString`?
> 
> Another note: for comparing NSStrings I suggest you use `isEqualToString` instead of `isEqual.`

Hi philipphofmann.

**Comment by LBCross** [comment] 2021-03-17 02:10
**error message:**

_ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN5fbsdk7MTensorEEENS_22__unordered_map_hasherIS7_SA_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_SA_NS_8equal_toIS7_EELb1EEENS5_ISA_EEE21__cons...
Sentry
+0x01c66c
-[SentryHub configureScope:]
Called from:
Sentry
+0x031b94
+[SentrySDK configureScope:]
ro
+0xd3cce4
_ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN5fbsdk7MTensorEEENS_22__unordered_map_hasherIS7_SA_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_SA_NS_8equal_toIS7_EELb1EEENS5_ISA_EEE21__cons...
ro
+0xd3d0c4
_ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN5fbsdk7MTensorEEENS_22__unordered_map_hasherIS7_SA_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_SA_NS_8equal_toIS7_EELb1EEENS5_ISA_EEE21__cons...
ro
+0x01e0b8
<redacted> 
ro
+0xe2fbb0
_ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN5fbsdk7MTensorEEENS_22__unordered_map_hasherIS7_SA_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_SA_NS_8equal_toIS7_EELb1EEENS5_ISA_EEE21__cons...
ro
+0xda8834
_ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN5fbsdk7MTensorEEENS_22__unordered_map_hasherIS7_SA_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_SA_NS_8equal_toIS7_EELb1EEENS5_ISA_EEE21__cons...
ro
+0xda80b8
_ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN5fbsdk7MTensorEEENS_22__unordered_map_hasherIS7_SA_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_SA_NS_8equal_toIS7_EELb1EEENS5_ISA_EEE21__cons...
ro
+0x09d1ac
<redacted> 
ro
+0x9942d4
plcrash::async::dwarf_cfa_state_iterator<T>::next

**Comment by LBCross** [comment] 2021-03-17 02:13
> Hey @LBCross,
> I'm sorry, but I can't reproduce your issue. Can you maybe share the issue in Sentry or post the exact error message?
> 
> We have several tests to make sure `[[SentryBreadcrumb alloc] init]` and other interactions with `SentryBreadcrumb` work fine. Can it be that the `key` and `value` you get from the `jsonDict` aren't of type `NSString`?
> 
> Another note: for comparing NSStrings I suggest you use `isEqualToString` instead of `isEqual.`

Key and value is NSString type. The os system of IOS 12.0.1 will crashed;

**Comment by LBCross** [comment] 2021-03-22 02:00
> @LBCross can you please let me know, which error you get?

The os system of IOS 12.0.1 will crashed;

**Comment by philipphofmann** [comment] 2021-03-22 10:22
Do you receive a crash in Sentry for this? It's hard to know what the problem is when we don't know the error. Does it only happen on iOS 12.0.1, or can you reproduce this error on other iOS versions as well?

**Comment by LBCross** [comment] 2021-03-24 12:23
> Do you receive a crash in Sentry for this? It's hard to know what the problem is when we don't know the error. Does it only happen on iOS 12.0.1, or can you reproduce this error on other iOS versions as well?

Sorry. I only have this phone. When I comment out this code, the program works.
![image](https://user-images.githubusercontent.com/19235947/112309819-c6bf8280-8cde-11eb-9984-e26dbe9c7f5b.png)

**Comment by Enxhi369** [comment] 2021-03-24 15:24
iOS 11 and below

**Comment by philipphofmann** [comment] 2021-03-24 16:09
> iOS 11 and below

@Enxhi369 what exactly do you mean by that?

**Comment by Enxhi369** [comment] 2021-03-24 16:13
I'm sorry I got it finally 
Thank you

**Comment by philipphofmann** [comment] 2021-03-24 16:13
@LBCross, can you try to run this code on a simulator from Xcode and tell me if you get the same error?

Can you please as well try if `[NSString stringWithFormat:@"%@:@%", key, value];` works without the Sentry code? Maybe the problem is in there.

**Comment by LBCross** [comment] 2021-03-25 02:49
> @LBCross, can you try to run this code on a simulator from Xcode and tell me if you get the same error?
> 
> Can you please as well try if `[NSString stringWithFormat:@"%@:@%", key, value];` works without the Sentry code? Maybe the problem is in there.

Sorry, the project is a game made by unity. It only has arm64 architecture, so the simulator can't be debugged. It's not because of this line` [NSString stringWithFormat:@"%@:@%", key, value]; `

**Comment by LBCross** [comment] 2021-03-25 02:57
> @LBCross, can you try to run this code on a simulator from Xcode and tell me if you get the same error?
> 
> Can you please as well try if `[NSString stringWithFormat:@"%@:@%", key, value];` works without the Sentry code? Maybe the problem is in there.

I think  only need to find a iOS12 system phone, and this problem will appear.

**Comment by philipphofmann** [comment] 2021-03-30 14:08
@LBCross does it work on the simulator?

**Comment by bruno-garcia** [comment] 2021-03-30 17:49
> @LBCross does it work on the simulator?

@philipphofmann I believe he can't test on the simulator, [see his comment](https://github.com/getsentry/sentry-cocoa/issues/1000#issuecomment-806323251)

> Sorry, the project is a game made by unity. It only has arm64 architecture, so the simulator can't be debugged. It's not because of this line[NSString stringWithFormat:@"%@:@%", key, value];

@LBCross could you please attach the JSON of the event so we can take a look? Or a link if it's on sentry.io

**Comment by philipphofmann** [comment] 2021-03-31 09:17
@LBCross you can get the JSON in the issue detail view by clicking on JSON.
<img width="843" alt="Screenshot 2021-03-31 at 11 13 54" src="https://user-images.githubusercontent.com/2443292/113120807-42a35880-9212-11eb-9143-487ea4c95a1e.png">

Here is an example [sample_event.json.zip](https://github.com/getsentry/sentry-cocoa/files/6235392/sample_event.json.zip)

**Comment by bruno-garcia** [comment] 2021-03-31 13:29
@LBCross I found a iOS 12 device but I need a repro to test it. Could you please provide is a complete repro?
Something I can just plug in to the device and run.

**Comment by LBCross** [comment] 2021-04-26 09:37
> @LBCross you can get the JSON in the issue detail view by clicking on JSON.
> <img alt="Screenshot 2021-03-31 at 11 13 54" width="843" src="https://user-images.githubusercontent.com/2443292/113120807-42a35880-9212-11eb-9143-487ea4c95a1e.png">
> 
> Here is an example [sample_event.json.zip](https://github.com/getsentry/sentry-cocoa/files/6235392/sample_event.json.zip)

log.txt

**Comment by LBCross** [comment] 2021-04-26 09:40
[log.txt](https://github.com/getsentry/sentry-cocoa/files/6375963/log.txt)


> @LBCross I found a iOS 12 device but I need a repro to test it. Could you please provide is a complete repro?
> Something I can just plug in to the device and run.

[log.txt](https://github.com/getsentry/sentry-cocoa/files/6375966/log.txt)

**Comment by bruno-garcia** [comment] 2021-04-27 02:44
@LBCross could you please share the code that causes the crash so we can run it on our end and debug through?

**Comment by Enxhi369** [comment] 2021-04-27 12:16
Yes o need help with this can you or someone contact me I need to hire a team of doing this please

**Comment by LBCross** [comment] 2021-04-27 13:08
> @LBCross could you please share the code that causes the crash so we can run it on our end and debug through?

![image](https://user-images.githubusercontent.com/19235947/116246647-c2cec680-a79c-11eb-9e1d-c5f9fe51792d.png)

**Comment by bruno-garcia** [comment] 2021-04-27 15:45
@LBCross please paste the code so we don't need to type it all from your image?

**Comment by philipphofmann** [comment] 2021-11-08 08:56
As we didn't hear anything for a while, we are going to close this issue. Feel free to open it again.

**Closed by philipphofmann** 2021-11-08 08:56 UTC
Labels: Status: Needs More Information
