### ISSUE TITLE
Symbols are sometimes not demangled

### ISSUE THREAD

**Issue by sindresorhus** [getsentry/sentry-cocoa#1502] opened 2021-12-02 03:47 UTC
### Environment

How do you use Sentry?

Sentry SaaS (sentry.io)

Which SDK and version?

7.5.2

### Steps to Reproduce

1. Send an error inside an async function.

### Expected Result

I expected the symbol to be demangled.

### Actual Result

`$s10Speediness17NetworkQualityCLIO3run10sequentialAC6ResultVSb_tYaKFZTf4nd_nTQ0_`

---

Report that shows the issue: https://sentry.io/organizations/sindresorhus/issues/2829562928/events/e8b0bd8974e54dafa30e11628c660831/

**Comment by philipphofmann** [comment] 2021-12-02 10:22
Thanks, @sindresorhus for reporting this. 

As [`$s`](https://github.com/apple/swift/blob/8a7ca32cf0f903f218b7eadeb857d5bfa968650c/include/swift/Demangling/Demangler.h#L610) is the mangling prefix of the Mangler of Swift, it seems like our demangling logic can't handle async functions properly. I can easily reproduce this and will add a sample project targeting iOS 15 soon to our repository. Unfortunately, it seems like this is not something we can solve in the sentry-cocoa SDK. I need to include a few other folks to find out what the problem is.

**Comment by philipphofmann** [comment] 2021-12-02 11:12
I think @Swatinem and or @jan-auer can help us here ⬆️.

**Comment by philipphofmann** [comment] 2021-12-02 11:15
According to @Swatinem, our Swift demangler is a few versions behind.

**Comment by philipphofmann** [comment] 2021-12-02 16:49
The problem is fixed with https://github.com/getsentry/symbolic/pull/465. The fix should be deployed next week. I'm going to check then if I still can reproduce this specific issue.

**Comment by philipphofmann** [comment] 2021-12-07 10:24
I was not able to reproduce this issue anymore. Please reopen if it still persists.

**Closed by philipphofmann** 2021-12-07 10:24 UTC
Labels: Type: Bug, Status: Backlog, Component: SentryCrash
