### ISSUE TITLE
Crash swizzling SwiftUI App

### ISSUE THREAD

**Issue by PhilippeWeidmann** [getsentry/sentry-cocoa#3495] opened 2023-12-14 08:13 UTC
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.16.1

### Steps to Reproduce

Sadly I don't have precise steps to reproduce the issue. However, we are seeing a fair amount of crash report located here.

```objc
#    pragma clang diagnostic push
#    pragma clang diagnostic ignored "-Wshadow"
    static const void *swizzleSendActionKey = &swizzleSendActionKey;
    SEL selector = NSSelectorFromString(@"sendAction:to:from:forEvent:");
    SentrySwizzleInstanceMethod(UIApplication, selector, SentrySWReturnType(BOOL), <-- This is is the offending reported in Sentry web
        SentrySWArguments(SEL action, id target, id sender, UIEvent * event), SentrySWReplacement({
            [SentrySwizzleWrapper sendActionCalled:action target:target sender:sender event:event];
            return SentrySWCallOriginal(action, target, sender, event);
        }),
        SentrySwizzleModeOncePerClassAndSuperclasses, swizzleSendActionKey);
``` 

Our app is written entirely using SwiftUI (SwiftUI app lifecycle).

The last breadcrumb logged is:
```
{
view: <UISwipeActionStandardButton: 0x150e42f60; frame = (74 0; 74 87.6667); anchorPoint = (0, 0.5); opaque = NO; autoresize = W+H; tintColor = UIExtendedGrayColorSpace 1 1; gestureRecognizers = <NSArray: 0x281cb8540>; animations = { position=<CASpringAnimation: 0x2813cfbe0>; }; layer = <CALayer: 0x2812afe60>>
}
```

### Expected Result

It shouldn't crash.

### Actual Result

It crashes.

**Comment by kahest** [comment] 2023-12-14 12:42
Hi @PhilippeWeidmann, thanks for the report - could you provide links for the issue? Either here or you can send it to karl.struggl@sentry.io.

**Comment by philipphofmann** [comment] 2023-12-14 14:13
@PhilippeWeidmann, what type of crash are you getting? What's the crash error message?

**Comment by PhilippeWeidmann** [comment] 2023-12-15 06:31
Here is a public link: 
https://sentry-mobile.infomaniak.com/share/issue/8449a6a672dd454ebc7bbcbc4fb75261/

**Comment by philipphofmann** [comment] 2023-12-18 08:35
As pointed out in https://github.com/getsentry/sentry-cocoa/issues/3454#issuecomment-1857582874, due to a misconfiguration on our in-app grouping rules, it seems like our SDK is the root cause for the crash, but instead, the inApp frames above ours are the root cause. This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3454.

**Closed by philipphofmann** 2023-12-18 08:35 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner

**Comment by philipphofmann** [comment] 2023-12-18 15:07
Backend PR merged https://github.com/getsentry/sentry/pull/61903, so we'll release this soon after CI completes.
