### ISSUE TITLE
crash on: -[SentryFramesTracker recordTimestamp:value:array:] (SentryFramesTracker.m:184)

### ISSUE THREAD

**Issue by mr-grey** [getsentry/sentry-cocoa#3607] opened 2024-02-02 08:46 UTC
### Platform

iOS

### Environment

Production

### Installed

CocoaPods

### Version

pod 'Sentry', '~> 8.13.0'

### Did it work on previous versions?

YES

### Steps to Reproduce

log to sentry 
it happens once 

### Expected Result

no crash 
![Screenshot 2024-02-02 at 10 44 40](https://github.com/getsentry/sentry-cocoa/assets/699148/28eb3563-a150-4696-b7f3-b83f0030f8c7)

### Actual Result

```
libobjc.A
+0x002c14
objc_retain

Sentry
+0x041f50
-[SentryFramesTracker recordTimestamp:value:array:] (SentryFramesTracker.m:184)

Sentry
+0x041d4c
-[SentryFramesTracker displayLinkCallback] (SentryFramesTracker.m)
QuartzCore
+0x02f2c8
CA::Display::DisplayLinkItem::dispatch_
QuartzCore
+0x0324b0
CA::Display::DisplayLink::dispatch_items
QuartzCore
+0x031fbc
CA::Display::DisplayLink::callback
QuartzCore
+0x0b128c
CA::Display::DisplayLink::dispatch_deferred_display_links
UIKitCore
+0x0aa7e0
_UIUpdateSequenceRun
UIKitCore
+0x0a9ed0
schedulerStepScheduledMainSection
UIKitCore
+0x0a9f8c
runloopSourceCallback
CoreFoundation
+0x037128
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
CoreFoundation
+0x0363a4
__CFRunLoopDoSource0
CoreFoundation
+0x034b58
__CFRunLoopDoSources0
CoreFoundation
+0x033894
__CFRunLoopRun
CoreFoundation
+0x033474
CFRunLoopRunSpecific
GraphicsServices
+0x0034f4
GSEventRunModal
UIKitCore
+0x22c628
-[UIApplication _run]
UIKitCore
+0x22bc64
UIApplicationMain
```

**Comment by philipphofmann** [comment] 2024-02-02 08:48
Thanks for reporting this. This looks like a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3511 and was fixed with https://github.com/getsentry/sentry-cocoa/pull/3571 in 8.20.0. Please reopen if the problem persists.

**Closed by philipphofmann** 2024-02-02 08:48 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
