### ISSUE TITLE
Sentry sdk getting crash: SentryContinuousProfiler timerExpired]

### ISSUE THREAD

**Issue by arnavgupta180** [getsentry/sentry-cocoa#4608] opened 2024-12-10 11:21 UTC
### Platform

macOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.36

### Xcode Version

15.4

### Steps to Reproduce

```
Due to sentry SDK app is getting crashed. 
Thread 0 Crashed:
0   libsystem_kernel.dylib               0x00007ff80aa5d14a __pthread_kill + 10
1   libsystem_pthread.dylib              0x00007ff80aa95ebd pthread_kill + 261
2   libsystem_c.dylib                    0x00007ff80a9bba79 abort + 125
3   libsystem_malloc.dylib               0x00007ff80a8c03a9 malloc_vreport + 856
4   libsystem_malloc.dylib               0x00007ff80a8e3c5b malloc_zone_error + 182
5   CoreFoundation                       0x00007ff80ab168f8 0x7ff80aaf7000 + 129272
6   Sentry                               0x000000010a1cce9c (anonymous namespace)::_sentry_threadUnsafe_transmitChunkEnvelope() (SentryContinuousProfiler.mm:54)
7   Sentry                               0x000000010a1cd342 +[SentryContinuousProfiler timerExpired] (SentryContinuousProfiler.mm:169)
8   Foundation                           0x00007ff80bb62c64 __NSFireTimer + 66
9   CoreFoundation                       0x00007ff80ab8e44c 0x7ff80aaf7000 + 619596
10  CoreFoundation                       0x00007ff80ab8dffa 0x7ff80aaf7000 + 618490
11  CoreFoundation                       0x00007ff80ab8dc36 0x7ff80aaf7000 + 617526
12  CoreFoundation                       0x00007ff80ab71f12 0x7ff80aaf7000 + 503570
13  CoreFoundation                       0x00007ff80ab71112 0x7ff80aaf7000 + 499986
14  HIToolbox                            0x00007ff81558aa09 RunCurrentEventLoopInMode + 291
15  HIToolbox                            0x00007ff81558a816 ReceiveNextEventCommon + 664
16  HIToolbox                            0x00007ff81558a561 _BlockUntilNextEventMatchingListInModeWithFilter + 65
17  AppKit                               0x00007ff80e1e1c61 _DPSNextEvent + 879
18  AppKit                               0x00007ff80eaf5dc0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1272
19  AppKit                               0x00007ff80e1d3075 -[NSApplication run] + 602
20  AppKit                               0x00007ff80e1a6ff3 NSApplicationMain + 815
21  ???                                  0x00007ff80a70a366 0x0 + 0
```

### Expected Result

App should not crash

### Actual Result

App is crashing due to sentry sdk

### Are you willing to submit a PR?

YES

**Comment by philipphofmann** [comment] 2024-12-11 16:09
Duplicate of https://github.com/getsentry/sentry-cocoa/issues/4607.

**Closed by philipphofmann** 2024-12-11 16:09 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
