### ISSUE TITLE
Attach UIKit view hierarchy to events

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1772] opened 2022-04-25 09:38 UTC
## Description

Capture the view hierarchy and attach it to events. Can be sent as a text file via an [attachment](https://docs.sentry.io/platforms/android/enriching-events/attachments/).

Related to https://github.com/getsentry/sentry-cocoa/issues/1560 and https://github.com/getsentry/sentry-java/issues/1647

## Solution brainstorm

https://github.com/indragiek/InAppViewDebugger does something similar, but according to @indragiek 

> Hey, if you're not interested in capturing the view as an image and only need the data structure then there's no real magic to it besides iterating the view tree recursively starting at some root view and collecting the metadata attributes you're looking for (probably stuff like class name, pointer address, etc.). If you want to capture what's on screen at any given moment you'd do something like this to figure out which window is key: https://stackoverflow.com/a/57169802. And then traverse the tree starting at that window (which inherits from UIView).

**Comment by romtsn** [comment] 2022-04-25 10:01
dupe of https://github.com/getsentry/sentry-cocoa/issues/1560? there's also a lib linked which works with swift UI only though, afaiu

**Comment by romtsn** [comment] 2022-04-25 10:07
Or I mean, we can literally ask @indragiek to help us out :D https://github.com/indragiek/InAppViewDebugger

**Comment by marandaneto** [comment] 2022-04-25 10:08
> dupe of #1560? there's also a lib linked

Not really, related tho.
That one is SwiftUI-specific, but they should be linked for sure, thanks.

**Closed** 2022-08-10 10:04 UTC
Labels: Impact: Medium, Effort: Small, Status: Backlog, Platform: Cocoa
