### ISSUE TITLE
Let users submit error reports manually

### ISSUE THREAD

**Issue by tonyarnold** [getsentry/sentry-cocoa#1986] opened 2022-07-19 01:16 UTC
### Problem Statement

Some of our more privacy-conscious users prefer to have control over what and when their error reports are submitted. They have told us that they prefer to be asked by our app before we submit crash or error reports to any third-party service. 

### Solution Brainstorm

Other solutions in this space provide a user confirmation handler, that allows us to present an alert asking whether the user wants us to:

- Send reports automatically
- Allow them to submit by confirming via an alert/dialog
- Do not ever send a report

**Comment by philipphofmann** [comment] 2022-07-20 09:17
Thanks for opening the issue, @tonyarnold. This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/1780. Let's continue the discussion there.

**Closed by philipphofmann** 2022-07-20 09:17 UTC
Labels: Type: Feature Request, Platform: Cocoa, Status: Untriaged
