### ISSUE TITLE
Crashing inside `-[SentryStacktraceBuilder buildStacktraceForCurrentThread]`

### ISSUE THREAD

**Issue by bjhomer** [getsentry/sentry-cocoa#3248] opened 2023-08-21 18:52 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.9.1

### Steps to Reproduce

We're seeing crashes reported that appear to be entirely within the Sentry SDK. An example [can be found here](https://a8c.sentry.io/issues/4262929420/?query=is%3Aunresolved+HTTPClientError&referrer=issue-stream&statsPeriod=14d&stream_index=0). It seems to consistently be happening shortly after launch, and always on a background thread.

The crash log points [here](https://github.com/getsentry/sentry-cocoa/blob/01a28a940bd9433e974b633d6d2ca2f6861ed6bd/Sources/Sentry/SentryStacktraceBuilder.m#L104), but it's not immediately obvious to me what would be wrong there. Maybe if `sentrycrashsc_initSelfThread()` doesn't properly initialize the stack cursor?

<img width="944" alt="Screenshot 2023-08-21 at 12 46 42 PM" src="https://github.com/getsentry/sentry-cocoa/assets/276263/c5eb497b-8747-41ff-83ce-3f96b4a299d7">

### Expected Result

The SDK shouldn't crash.

### Actual Result

It's crashing.

### Are you willing to submit a PR?

If I could see what was wrong, I'd be happy to.

**Comment by brustolin** [comment] 2023-08-22 06:18
Thanks @bjhomer for reporting this.
Are you experiencing this only in production, or can you reproduce this in development?

We will investigate this.

**Comment by brustolin** [comment] 2023-08-23 08:45
Hello @bjhomer. I overlooked your error at the given link.

So, this is not a crash; we're just reporting a request error that the app received when calling the URL in the error report.
It looks like the server returned code 502 for this particular HTTP request.

I'm closing this issue. Let me know if you think I'm mistaken; we can reopen it.

**Closed by brustolin** 2023-08-23 08:45 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner

**Comment by setoelkahfi** [comment] 2024-06-28 07:23
Hey @brustolin, Is the conclusion that the SDK works fine, but the app's calling the URL produces the error? We got an error spike for this type of error. We thought it was an outdated SDK that we were using. But it is still happening after we bumped it to the latest.

<img width="1344" alt="Screenshot 2024-06-28 at 09 21 38" src="https://github.com/getsentry/sentry-cocoa/assets/1797197/3d7e543f-ffd1-4c70-883f-c6e9222d1d47">

**Comment by brustolin** [comment] 2024-07-08 07:22
Hello @setoelkahfi, this issue is created when the server responds with an error.

You can find more information about the in the [docs](https://docs.sentry.io/platforms/apple/guides/ios/configuration/http-client-errors/).

**Comment by mickeyl** [comment] 2024-09-30 09:19
I like the functionality for user code, but I don't think SDK should report "internal" errors. Is there a canonical way to use the filter callback to suppress these?

**Comment by brustolin** [comment] 2024-09-30 09:56
@mickeyl Can you give me an example? I didn't get it.

**Comment by mickeyl** [comment] 2024-09-30 12:36
@brustolin ![Image](https://github.com/user-attachments/assets/262e2967-6288-4071-9864-31dac4f611ac)

To me, this looks like an error cause by some internal stuff going on in the SDK, not provoked by an error in the actual app ­– or am I misreading it?

**Comment by brustolin** [comment] 2024-09-30 14:27
@mickeyl 

Since you’re statically linking the framework to your project, Sentry treats the Sentry code as part of the app and does not filter it. The error here is a 502 response from the server. The stack trace, in this case, is not relevant since requests are asynchronous.

You can find the URL that triggered the error in the event details.

**Comment by mickeyl** [comment] 2024-09-30 16:19
@brustolin Ok, just to confirm: You are saying that the traceback that points to the Sentry SDK is just misleading in this case and it's indeed _my_ HTTP client (in the app) that encountered an error response?

**Comment by brustolin** [comment] 2024-10-01 06:44
@mickeyl Yes.
