### ISSUE TITLE
Add `sentry-trace` header to outgoing HTTP requests

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cocoa#989] opened 2021-03-10 14:47 UTC
Outgoing HTTP requests should include a header indicating the traceid, spanid, and sampling decision.

Docs are here: https://develop.sentry.dev/sdk/performance/#header-sentry-trace

Some examples:

https://github.com/getsentry/sentry-dotnet/blob/39680350f97cc4c6901f7a0f56d7ad7f2f2aa46a/src/Sentry/SentryTraceHeader.cs
https://github.com/getsentry/sentry-dotnet/blob/2337261333d5743996d6d96ca3aa289d34a9d3ec/src/Sentry/SentryHttpMessageHandler.cs

https://github.com/getsentry/sentry-java/search?q=sentry-trace

**Comment by philipphofmann** [comment] 2021-04-21 12:28
Also, take https://github.com/getsentry/sentry-cocoa/issues/989 into account when fixing this.

**Comment by bruno-garcia** [comment] 2021-04-21 23:57
@philipphofmann linked the wrong issue?

**Comment by philipphofmann** [comment] 2021-04-22 07:06
> @philipphofmann linked the wrong issue?

Yes, thanks for pointing that out. I updated the comment.

**Comment by bruno-garcia** [comment] 2021-04-22 21:59
> Also, take [getsentry/sentry-java#1429](https://github.com/getsentry/sentry-java/pull/1429) into account when fixing this.

Not sure it's related. The problem there is due to a feature we created to map exceptions to spans using weak ref. In which cases we should also make sure to include `transaction.name` to the event captured for that exception.

**Comment by philipphofmann** [comment] 2021-04-23 07:57
Okay then I remove the comment.

**Comment by philipphofmann** [comment] 2021-07-27 13:52
Was fixed with https://github.com/getsentry/sentry-cocoa/pull/1213. Duplicate of https://github.com/getsentry/sentry-cocoa/issues/1199.

**Closed by philipphofmann** 2021-07-27 13:52 UTC
Labels: Performance Product, enhancement
