### ISSUE TITLE
App getting crash due to sentry SDK>[SentryCrashJSONCodec initWithEncodeOptions:decodeOptions:]

### ISSUE THREAD

**Issue by arnavgupta180** [getsentry/sentry-cocoa#4614] opened 2024-12-10 11:40 UTC
### Platform

macOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.36

### Xcode Version

15.4

### Steps to Reproduce

Thread 30 Crashed:
0   libsystem_kernel.dylib               0x00007ff81fc57112 __pthread_kill + 10
1   libsystem_pthread.dylib              0x00007ff81fc8d233 pthread_kill + 262
2   libsystem_c.dylib                    0x00007ff81fbd9d10 abort + 122
3   libsystem_malloc.dylib               0x00007ff81fab73e2 malloc_vreport + 547
4   ???                                  0x000000010a51c000 0x0 + 0
5   libsystem_malloc.dylib               0x00007ff81facb2f2 malloc_zone_error + 182
6   libsystem_malloc.dylib               0x00007ff81faaa09e nanov2_allocate_from_block + 581
7   libsystem_malloc.dylib               0x00007ff81faa9639 nanov2_allocate + 129
8   libsystem_malloc.dylib               0x00007ff81faa9566 nanov2_malloc + 55
9   libsystem_malloc.dylib               0x00007ff81fac5ad6 _malloc_zone_malloc + 124
10  Sentry                               0x000000010b053804 -[SentryCrashJSONCodec initWithEncodeOptions:decodeOptions:] (SentryCrashJSONCodecObjC.m:127)
11  Sentry                               0x000000010b05376e +[SentryCrashJSONCodec codecWithEncodeOptions:decodeOptions:] (SentryCrashJSONCodecObjC.m:118)
12  Sentry                               0x000000010b054066 +[SentryCrashJSONCodec encode:options:error:] (SentryCrashJSONCodecObjC.m:424)
13  Sentry                               0x000000010b068213 -[SentryCrashScopeObserver toJSONEncodedCString:] (SentryCrashScopeObserver.m:149)
14  Sentry                               0x000000010b067fe1 -[SentryCrashScopeObserver addSerializedBreadcrumb:] (SentryCrashScopeObserver.m:90)
15  Sentry                               0x000000010b0aa923 -[SentryScope addBreadcrumb:] (SentryScope.m:138)
16  Sentry                               0x000000010b082d87 -[SentryHub addBreadcrumb:] (SentryHub.m:513)
17  Sentry                               0x000000010b0afa14 +[SentrySDK addBreadcrumb:] (SentrySDK.m:398)
18  Sentry                               0x000000010b03fb45 -[SentryBreadcrumbTracker connectivityChanged:typeDescription:] (SentryBreadcrumbTracker.m:153)
19  Sentry                               0x000000010b0a67b2 SentryConnectivityCallback (SentryReachability.m:121)
20  SystemConfiguration                  0x00007ff820873f48 reachPerformAndUnlock + 631
21  libnetwork.dylib                     0x00007ff823ecf4ab __nw_path_necp_update_evaluator_block_invoke + 426
22  libdispatch.dylib                    0x00007ff81fad5ad8 _dispatch_call_block_and_release + 11
23  libdispatch.dylib                    0x00007ff81fad6cc9 _dispatch_client_callout + 7
24  libdispatch.dylib                    0x00007ff81fadccee _dispatch_lane_serial_drain + 695
25  libdispatch.dylib                    0x00007ff81fadd7c8 _dispatch_lane_invoke + 365
26  libdispatch.dylib                    0x00007ff81fae77e1 _dispatch_workloop_worker_thread + 757
27  libsystem_pthread.dylib              0x00007ff81fc8a08f _pthread_wqthread + 325
28  libsystem_pthread.dylib              0x00007ff81fc8901b start_wqthread + 14

### Expected Result

App should not crash.

### Actual Result

App is crashing.

**Comment by philipphofmann** [comment] 2024-12-11 16:07
Duplicate of https://github.com/getsentry/sentry-cocoa/issues/4424.

**Closed by philipphofmann** 2024-12-11 16:07 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
