### ISSUE TITLE
Xcode 13 Beta strict enforcement of valid exclusion paths causes warning

### ISSUE THREAD

**Issue by OscarGorog** [getsentry/sentry-cocoa#1186] opened 2021-06-19 05:14 UTC
- Sentry SaaS (sentry.io)
- Swift Package - Latest Version

When using the latest version of the SDK in the  Xcode 13 Beta, it appears Apple is now raising a warning if files in the exclude section of Package.swift do not exist. In the current Package.swift there is a reference to "Utils", "Samples", "scripts" and "Tests" which does not exist in the repository.

This is raising a warning against the package in Xcode along the lines of Invalid Exclude... File not found. See the image below for further details.

<img width="2017" alt="Screen Shot 2021-06-19 at 3 12 07 pm" src="https://user-images.githubusercontent.com/18746541/122631708-d1888880-d110-11eb-86de-04dda88b48a7.png">

**Comment by philipphofmann** [comment] 2021-06-21 09:25
Thanks for pointing this out. This should be fixed with https://github.com/getsentry/sentry-cocoa/pull/1169. The fix is going to be in the next beta. Can you reopen the issue if the issue is still there, please?

**Closed by philipphofmann** 2021-06-21 09:25 UTC

**Comment by OscarGorog** [comment] 2021-06-21 09:58
No problem, thanks!
