### ISSUE TITLE
After upgrading to 8.28 visionOS build fails

### ISSUE THREAD

**Issue by rist** [getsentry/sentry-cocoa#4078] opened 2024-06-17 11:42 UTC
### Platform

visionOS

### Environment

Other

### Installed

Swift Package Manager

### Version

8.29

### Xcode Version

15.4

### Did it work on previous versions?

yes

### Steps to Reproduce

Upgraded SPM dependency to 8.29, this fixed our iOS and tvOS builds on Xcode 16, but now visionOS builds fails also on 15.4

### Expected Result

Successful builds for iOS, tvOS and visionOS on Xcode 15 and 16.

### Actual Result

```
Error
Undefined symbol: typeinfo for unsigned long
Error
Undefined symbol: ___cxa_rethrow
Error
Undefined symbol: ___cxa_free_exception
Error
Undefined symbol: vtable for __cxxabiv1::__class_type_info
Error
Undefined symbol: typeinfo for char*
Error
Undefined symbol: std::exception::what() const
Error
Undefined symbol: vtable for __cxxabiv1::__si_class_type_info
Error
Undefined symbol: typeinfo for unsigned char
Error
Undefined symbol: typeinfo for std::exception
Error
Undefined symbol: operator delete(void*)
Error
Undefined symbol: std::logic_error::logic_error(char const*)
Error
Undefined symbol: ___gxx_personality_v0
Error
Undefined symbol: typeinfo for std::__1::__shared_weak_count
Error
Undefined symbol: std::bad_array_new_length::~bad_array_new_length()
Error
Undefined symbol: typeinfo for std::bad_array_new_length
Error
Undefined symbol: ___cxa_allocate_exception
Error
Undefined symbol: typeinfo for short
Error
Undefined symbol: std::__1::__shared_weak_count::__get_deleter(std::type_info const&) const
Error
Undefined symbol: std::__1::__shared_weak_count::__release_weak()
Error
Undefined symbol: typeinfo for int
Error
Undefined symbol: std::terminate()
Error
Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::resize(unsigned long, char)
Error
Undefined symbol: std::__1::mutex::~mutex()
Error
Undefined symbol: typeinfo for long long
Error
Undefined symbol: typeinfo for long double
Error
Undefined symbol: typeinfo for char
Error
Undefined symbol: std::__1::mutex::unlock()
Error
Linker command failed with exit code 1 (use -v to see invocation)
Error
Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
Error
Undefined symbol: std::length_error::~length_error()
Error
Undefined symbol: vtable for std::length_error
Error
Undefined symbol: std::current_exception()
Error
Undefined symbol: ___cxa_current_exception_type
Error
Undefined symbol: std::exception_ptr::~exception_ptr()
Error
Undefined symbol: ___cxa_begin_catch
Error
Undefined symbol: typeinfo for double
Error
Undefined symbol: std::bad_array_new_length::bad_array_new_length()
Error
Undefined symbol: typeinfo for unsigned int
Error
Undefined symbol: typeinfo for std::length_error
Error
Undefined symbol: ___cxa_end_catch
Error
Undefined symbol: typeinfo for unsigned long long
Error
Undefined symbol: std::set_terminate(void (*)())
Error
Undefined symbol: typeinfo for float
Error
Undefined symbol: std::__1::__shared_weak_count::~__shared_weak_count()
Error
Undefined symbol: operator new(unsigned long)
Error
Undefined symbol: std::exception::~exception()
Error
Undefined symbol: typeinfo for unsigned short
Error
Undefined symbol: std::__1::mutex::lock()
Error
Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
Error
Undefined symbol: typeinfo for long
```

**Comment by m4p** [comment] 2024-06-17 13:03
Having the same issue. After a cursory look, it seems [removing c++ from the linker options in Package.swift here](https://github.com/getsentry/sentry-cocoa/commit/3cba0e88ef7bf5987091e4162dd409ba6e31634f) causes this.

**Comment by mcichecki** [comment] 2024-06-18 11:47
I also noticed this issue when trying to build on visionOS, fix or workaround would be helpful.

**Comment by philipphofmann** [comment] 2024-06-18 12:52
I can reproduce the problem. Switching to Sentry-Dynamic seems to solve the problem for me:
![CleanShot 2024-06-18 at 14 51 47](https://github.com/getsentry/sentry-cocoa/assets/2443292/7feead4f-7745-475f-8b13-e2f6d7c58e35)

We're investigating this problem.

**Comment by philipphofmann** [comment] 2024-06-18 13:01
This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3809. Please add further information over there.

**Closed by philipphofmann** 2024-06-18 13:01 UTC
Labels: Type: Bug, Platform: Cocoa
