### ISSUE TITLE
macCatalyst app: Sentry >= 8.11 hangs on launch

### ISSUE THREAD

**Issue by gabors** [getsentry/sentry-cocoa#3293] opened 2023-09-19 20:52 UTC
### Platform

macOS

### Installed

Swift Package Manager

### Version

8.11

### Steps to Reproduce

Create a UIKit macCatalyst app with Xcode 14 or Xcode 15.
Make sure Notifications are disabled for this app in macOS Settings.
Add Sentry Swift Package v 8.11 or 8.12.  8.10 still works fine.
Integrate Sentry to start on app launch.
Launch the app.

App hangs on launch.
<img width="243" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/3a1c32bd-c50e-498a-a44c-11ef83ef2e7b">

`SentrySDK.start { options in
            options.dsn = Configuration.sentry.dsn
            options.environment = Configuration.sentry.env
            options.releaseName = BuildInfo.current.version.description
            options.maxBreadcrumbs = 128
            options.attachStacktrace = true
            options.enableSwizzling = false
            options.enableNetworkTracking = false
            options.enableAutoPerformanceTracing = false
            options.enableCoreDataTracing = false
            options.enableAppHangTracking = false
            options.enableWatchdogTerminationTracking = false
            options.enableCaptureFailedRequests = false
        }

        if let user {
            let su = Sentry.User(userId: user.id.description)
            su.email = user.email
            su.username = user.displayName
            SentrySDK.setUser(su)
        }

        SentrySDK.configureScope { scope in
            scope.setTags(self.createSentryTags())
        }`

### Expected Result

Expecting to launch

### Actual Result

Hangs if Notifications are disabled.
If Notifications are enabled, app launches fine.

<img width="885" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/3587589/70f50460-ecbc-4b78-9180-667fa6c0faf0">

### Are you willing to submit a PR?

Sure

**Comment by brustolin** [comment] 2023-09-20 07:47
Duplicate of #3277.
Please follow the other issue for updates.

**Comment by gabors** [comment] 2023-09-20 17:00
@brustolin is there a workaround currently so we can use Sentry 8.11 and newer?

**Comment by gabors** [comment] 2023-09-20 21:09
@brustolin I do not think this is necessarily the same issue as #3277 
When I run the iOS target of my app, which shares the same code base as the macCatalyst app I do not get the app hanging on startup. App starts up just fine on iOS 17 sim with Sentry SDK 8.12

**Comment by brustolin** [comment] 2023-09-21 08:12
Hello @gabors,

Does the app hang for a while but eventually resume running, or does it freeze forever? 
#3277 was an edge case that also doesn't happen all the time. Maybe this is why you haven't seen it happening on the device simulator.

In any case, I'll take another look at this one

**Comment by gabors** [comment] 2023-09-21 08:15
> Hello @gabors,
> 
> 
> 
> Does the app hang for a while but eventually resume running, or does it freeze forever? 
> 
> #3277 was an edge case that also doesn't happen all the time. Maybe this is why you haven't seen it happening on the device simulator.
> 
> 
> 
> In any case, I'll take another look at this one

The catalyst app freezes every launch and does not eventually unfreeze. Just stays hanging. 
Thanks for looking into this.

**Comment by brustolin** [comment] 2023-09-25 10:01
Hello @gabors.
Can you update to the new SDK version [8.13.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.13.0) to see if the problem persist for you?

**Comment by gabors** [comment] 2023-09-25 17:30
> Hello @gabors.
> Can you update to the new SDK version [8.13.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.13.0) to see if the problem persist for you?

Hi @brustolin Just tried 8.13 and so far so good! Mac Catalyst app no long hangs on launch!

**Comment by brustolin** [comment] 2023-09-26 07:13
> Hi @brustolin Just tried 8.13 and so far so good! Mac Catalyst app no long hangs on launch!

Awesome. I will close this issue. Let me know if this happens again.

**Closed by brustolin** 2023-09-26 07:13 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
