### ISSUE TITLE
Why don't OOM reports include breadcrumbs

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#2377] opened 2022-11-11 22:25 UTC
### Problem Statement

When I get an OOM I don't see the breadcrumbs that happened before the crash. Instead I have to upload a log file to get the context of what happened.

**Comment by brustolin** [comment] 2022-11-14 08:15
Hello @Eric.
#2347 Will solve this issue.

**Comment by philipphofmann** [comment] 2022-11-14 09:05
Duplicate of https://github.com/getsentry/sentry-cocoa/issues/1759.

**Closed by philipphofmann** 2022-11-14 09:05 UTC
Labels: Type: Feature Request, Platform: Cocoa, Status: Untriaged
