### ISSUE TITLE
Xcode 16 'terminate_handler' issue

### ISSUE THREAD

**Issue by dlbuckley** [getsentry/sentry-cocoa#4052] opened 2024-06-12 07:47 UTC
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.18.0

### Xcode Version

16 Beta 1

### Did it work on previous versions?

yes, Xcode 15

### Steps to Reproduce

1. Open a project in Xcode 16 (build artefacts have been cleaned, Xcode toolchain has been switched to Xcode 16, no other project changes)
2. Build the project
3. 3 compilation errors from `SentryCrashMonitor_CPPException` with the errors `No type named 'terminate_handler' in namespace 'std'` & `No member named 'set_terminate' in namespace 'std'`

### Expected Result

No compilation errors

### Actual Result

3 errors in `SentryCrashMonitor_CPPException` with the errors `No type named 'terminate_handler' in namespace 'std'` (line 60) and `No member named 'set_terminate' in namespace 'std'` (line 207 & 209).

### Are you willing to submit a PR?

Not proficient in c++.

**Comment by philipphofmann** [comment] 2024-06-12 08:56
Thanks for reporting this, @dlbuckley. This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/4050, which is already fixed and will be in the next release.

**Closed by philipphofmann** 2024-06-12 08:56 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
