### ISSUE TITLE
Crash in SentryViewPhotographer

### ISSUE THREAD

**Issue by MarekSlaninka** [getsentry/sentry-cocoa#4547] opened 2024-11-18 10:18 UTC
### Platform

iOS, iPadOS

### Environment

TestFlight

### Installed

Swift Package Manager

### Version

8.41.0

### Xcode Version

16.1

### Did it work on previous versions?

Yes, 8.36.0

### Steps to Reproduce

Just using the app it seems

### Expected Result

Dont crash

### Actual Result

![Image](https://github.com/user-attachments/assets/4ee2a927-e08f-47df-b09a-21be23d7eb6e)

**Comment by MarekSlaninka** [comment] 2024-11-18 10:58
Im sorry, I updated the picture

**Comment by brustolin** [comment] 2024-11-18 11:07
Thanks for the quick reply, we will investigate this.

**Comment by philipphofmann** [comment] 2024-11-27 13:30
This is duplicate of https://github.com/getsentry/sentry-cocoa/issues/4558.

**Closed by philipphofmann** 2024-11-27 13:30 UTC
Labels: Type: Bug, Platform: Cocoa, Session Replay
