### ISSUE TITLE
Swift package manager + Bitrise, duplicate symbol '___gcov_flush'

### ISSUE THREAD

**Issue by timarcngroup** [getsentry/sentry-cocoa#623] opened 2020-07-14 18:26 UTC
_Platform:_
- [X]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [X]  Yes -> 5
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually
- [X] Swift Package Manager

Version of sentry-cocoa:
**5.1.9**

---
I have following issue:

Can not build on Bitrise CI for duplicate symbol  '___gcov_flush' (locally build the project correctly)

Output:
```
❌  duplicate symbol '___gcov_flush' in
> Sentry.o
> Installations.o
❌  duplicate symbol '___gcov_flush' in
> Sentry.o
> Recording.o
❌  duplicate symbol '___gcov_flush' in
> Sentry.o
> Monitors.o
❌  duplicate symbol '___gcov_flush' in
> Sentry.o
> Tools.o
❌  duplicate symbol '___gcov_flush' in
> Sentry.o
> Filters.o
❌  duplicate symbol '___gcov_flush' in
> Sentry.o
> Tools.o
❌  duplicate symbol '___gcov_flush' in
> Sentry.o
> Tools.o
❌  ld: 7 duplicate symbols for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
**Actual result:**
- Duplicate symbols

**Expected result:**
- Success builds on Bitrie CI

**Comment by philipphofmann** [comment] 2020-07-21 12:54
Hi @timarcngroup, it seems like this could be an issue with your Bitrise configuration, if you can build the project locally. Can you let us know how you build the project on Bitrise, so we can reproduce the issue?

**Comment by floskel** [comment] 2020-09-24 07:13
Im seing the same problems also on Bitrise. It seems to be a conflict with RxSwift for my setup. I have notified Bitrise about this ticket.

**Comment by floskel** [comment] 2020-11-03 09:23
Any updates on this?

**Comment by philipphofmann** [comment] 2020-11-04 08:17
Someone opened a similar issue here https://github.com/realm/realm-cocoa/issues/6814. This seems to be a bug in the Xcode build system. They talked to an engineer from Bitrise and suggest a workaround (https://github.com/realm/realm-cocoa/issues/6814#issuecomment-704210233): 

> There might be a more efficient workaround that I just thought of. You could potentially turn the "generate code coverage" section off, then use the "Additional options for xcodebuild build test call" section to add the "GCC_GENERATE_TEST_COVERAGE_FILES=YES" argument.

Does this fix your problem?

**Comment by philipphofmann** [comment] 2021-10-18 14:34
As we didn't hear anything for a while, we are going to close this issue. Feel free to open it again.

**Closed by philipphofmann** 2021-10-18 14:34 UTC
