### ISSUE TITLE
Document that binding transaction to the scope is required to connect spans and errors

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-cocoa#1324] opened 2021-09-10 06:44 UTC
Similar to Android/Java https://docs.sentry.io/platforms/android/performance/instrumentation/custom-instrumentation/#connect-errors-with-spans

**Comment by bruno-garcia** [comment] 2021-09-10 13:09
Possibly a dupe of: https://github.com/getsentry/sentry-cocoa/issues/990 which was closed as implemented through #1065

**Comment by marandaneto** [comment] 2021-09-10 13:13
only if the transaction is set in the scope, not calling `setThrowable` which makes sense as exceptions are not used in Swift/ObjC, but we'r missing docs then

**Comment by bruno-garcia** [comment] 2021-09-10 14:59
The equivalent here would be: Can we connect a crash event with a transaction if one was bound to the scope? That would be very valuable. 
The transaction could be sent after restart too if that made sense but couldn't be added to the same envelope as the crash event

**Comment by marandaneto** [comment] 2021-09-13 05:59
@bruno-garcia that would be a nice feature but it'd require changes, we'd need to find a way on how to track all the "manual" transactions so we can finish em all when there's a hard crash, obviously it's easier for automatic transactions.

**Comment by bruno-garcia** [comment] 2021-09-15 14:20
For reference: https://github.com/getsentry/sentry-docs/issues/4153

**Comment by philipphofmann** [comment] 2022-04-06 13:15
https://docs.sentry.io/platforms/apple/performance/instrumentation/custom-instrumentation/#create-transaction-bound-to-the-current-scope should mention this.

**Comment by brustolin** [comment] 2023-03-31 08:36
Related docs PR https://github.com/getsentry/sentry-docs/pull/6570#issuecomment-1491504077

**Closed** 2023-04-05 15:04 UTC
Labels: Component: Performance, Effort: Small, Status: Backlog, Platform: Cocoa
