### ISSUE TITLE
iOS 12 in some cases don't get UIViewController performance tracking

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#1694] opened 2022-03-14 17:28 UTC
### Description

We got a new crash report (https://github.com/getsentry/sentry-cocoa/issues/1690) related to the new `UIViewController` swizzling. 

This bug was fixed with the PR https://github.com/getsentry/sentry-cocoa/pull/1692, but iOS 12 may lose performance tracking.

We need to investigate why this happen and a way around it.

**Comment by philipphofmann** [comment] 2022-03-14 17:29
Duplicate of https://github.com/getsentry/sentry-cocoa/issues/1693.

**Closed by philipphofmann** 2022-03-14 17:29 UTC
Labels: Platform: Cocoa
