### ISSUE TITLE
Don't crash when out of disk space

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#2575] opened 2023-01-05 06:38 UTC
### Platform

iOS

### Installed

CocoaPods

### Version

7.31.2

### Steps to Reproduce

1. Run out of disk space
2. Create a breadcrumb

### Expected Result

Sentry doesn't throw an exception

### Actual Result

<img width="850" alt="screenshot-2023-01-04-22 37 28@2x" src="https://user-images.githubusercontent.com/470/210717345-44938604-b316-490f-851e-e2a6034e5c94.png">

**Comment by philipphofmann** [comment] 2023-01-05 14:59
Thanks for reporting this, @eric. We fixed this in 7.31.5. This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/2548.

**Closed by philipphofmann** 2023-01-05 14:59 UTC
Labels: Type: Bug, Platform: Cocoa, Status: Untriaged

**Comment by eric** [comment] 2023-01-06 03:04
Thanks.
