### ISSUE TITLE
SentryUIApplication blocks the main thread for seconds and errors are thrown for thread management 

### ISSUE THREAD

**Issue by sadaf-behbahani** [getsentry/sentry-cocoa#2571] opened 2023-01-03 10:11 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

7.31.3

### Steps to Reproduce

It does not happen often and I have no definite steps to reproduce, here is a screenshot of what happens. It blocks the main thread and leads to a few seconds hang on the application. 
This is the thrown warnings from the  Inspecter. 
`-[UIApplication connectedScenes] must be used from main thread only`

### Expected Result

Correct thread management -  [UIApplication connectedScenes] must be used from main thread only

### Actual Result

<img width="1111" alt="Screenshot 2023-01-03 at 11 09 31" src="https://user-images.githubusercontent.com/23311093/210337295-8aa96174-544f-48f7-ab8c-615264f6917e.png">

**Comment by brustolin** [comment] 2023-01-03 13:40
There is something weird here. The inspector is complaining about `connectScenes` being called in a background thread, but the main thread is hanging for a few seconds. 
We do capture screenshots and view hierarchies in the main thread, but, unless you are capturing a bunch of errors in a tight loop, these should not block the main thread for a few seconds. 

And I dont have a clue what is causing the thread warning.

We need more information. The stack trace would help a lot. Maybe try to use `captureAppHangs` to capture the stack trace of the hang itself.

**Comment by sadaf-behbahani** [comment] 2023-01-06 09:26
Here is a stack trace of what happens, hope it helps. You can see in the logs, we make an API call and in the result we have 403 with an error. What happens next is that Sentry blocks the main thread for few seconds. 
The API call is made in a very common situation, in the background thread using async/await from URLSession. 
[stacktraceSentry.txt](https://github.com/getsentry/sentry-cocoa/files/10359018/stacktraceSentry.txt)

**Comment by brustolin** [comment] 2023-01-09 10:36
@sadaf-behbahani How big is your UI? Can you share the view-hierarchy.txt attachment?

**Comment by philipphofmann** [comment] 2023-01-18 13:36
@sadaf-behbahani, could it be that you capture many errors in a short time? What could happen is that your thread checker blocks the main thread for a couple of seconds cause it detected that we do something from a background thread that we should do on the main thread. It could be that fixing 
`-[UIApplication connectedScenes] must be used from main thread only` would solve this problem.

**Comment by philipphofmann** [comment] 2023-01-18 13:37
We believe this is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/2586. If fixing https://github.com/getsentry/sentry-cocoa/issues/2586 doesn't fix your problem, @sadaf-behbahani, please reopen this issue..

**Closed by philipphofmann** 2023-01-18 13:37 UTC
Labels: Type: Bug, Platform: Cocoa

**Comment by sadaf-behbahani** [comment] 2023-01-19 08:46
> @sadaf-behbahani, could it be that you capture many errors in a short time? What could happen is that your thread checker blocks the main thread for a couple of seconds cause it detected that we do something from a background thread that we should do on the main thread. It could be that fixing
> `-[UIApplication connectedScenes] must be used from main thread only` would solve this problem.

Generally it happens when a simple API call fails, only one API call and if it fails, the app freezes. No matter the number of errors we try to catch, if one error occurs it freezes , if many errors occur it still freezes.

**Comment by philipphofmann** [comment] 2023-01-19 16:13
Thanks for the update. @brustolin, see the info provided by @sadaf-behbahani :arrrow_up:.

**Comment by brustolin** [comment] 2023-01-20 08:42
We have a suspicion that the thread analyser may be causing this. 
If this is the case, #2586 will solve this.
