### ISSUE TITLE
Breadcrumbs Are Not Properly Logged

### ISSUE THREAD

**Issue by eaigner** [getsentry/sentry-cocoa#442] opened 2020-04-16 15:30 UTC
_Platform:_
- [ ]  iOS
- [ ]  tvOS
- [x]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes, Version 5.2.2
- [ ]  No

_sentry-cocoa installed with:_
- [ ] CocoaPods
- [ ] Carthage
- [x] Manually

Version of sentry-cocoa:
**5.0.0-beta.3**

---
I have following issue:

If Breadcrumbs are recorded in the following way, they do not show up in the web interface.

```
SentrySDK.addBreadcrumb(crumb: foo)
SentrySDK.addBreadcrumb(crumb: bar)
SentrySDK.capture(error: error)
```

If the breadcrumb is added inside a scope block, the breadcrumb shows up in the web interface, but any breadcrumb that was added before the scope block will not show up.

```
SentrySDK.capture(error: error) { scope in
   scope.add(foo)
}
```

**Comment by eaigner** [comment] 2020-04-16 15:53
Might be of interest, the log shows an error for the first case.

```
Sentry - Error:: Invalid JSON.
Sentry - Debug:: Writing to current session: /Users/era/Library/Caches/io.sentry/297cbaf404dbc12b1a829ae01ca691482a2854ab/session.current
Sentry - Debug:: Writing to file: /Users/era/Library/Caches/io.sentry/297cbaf404dbc12b1a829ae01ca691482a2854ab/events/1587052318.233642-0-DC71D667-57E7-47B8-87BB-D5C6E022AD5A.json
Sentry - Debug:: Request status: 200
Sentry - Debug:: Queued requests: 0
```

**Comment by bruno-garcia** [comment] 2020-04-16 21:57
Thanks for raising this @eaigner . The `Invalid JSON` I've identified and #443 will address.
I'll look into why the breadcrumb isnt' logged since they seem unrelated

**Comment by bruno-garcia** [comment] 2020-04-17 01:44
I've tried it like this, and the breadcrumb was included.

```swift
        let crumb = Breadcrumb();
        crumb.message = "What happens when I click here?";
        SentrySDK.addBreadcrumb(crumb: crumb)
        SentrySDK.capture(message: "does it incl the crumb?");
```

I couldn't reproduce. Even without the fix in #443 
Maybe something else on your setup? Could you please describe it in more detail or provide a repro so we can run it?

**Comment by eaigner** [comment] 2020-04-17 06:47
Mhm that seems strange. Could it be that the Breadcrumb processing just takes a long time? Because when I looked at the issue again today, some breadcrumbs were attached.

Then I deleted the issue again, and triggered a new error in the app, and when I opened the new issue again, it again had no breadcrumbs.

**Comment by eaigner** [comment] 2020-04-17 06:54
When I reduced `maxBreadcrumbs` to 10 in my `SentrySDK` configuration, they showed up immediately.

**Comment by philipphofmann** [comment] 2020-05-29 10:22
Hi @eaigner, we did lots of fixes in our SDK in the last weeks. Do you still experience the issue or can we close this?

**Comment by eaigner** [comment] 2020-05-29 12:40
I updated my app to 5.1.0 yesterday, will let you know!

**Comment by philipphofmann** [comment] 2020-06-26 08:29
@eaigner any update on this?

**Comment by eaigner** [comment] 2020-06-27 19:50
Currently have no way to test it.

**Comment by philipphofmann** [comment] 2020-07-02 12:14
I close this for now @eaigner. Feel free to open this issue again or another one if you have trouble with breadcrumbs again.

**Closed by philipphofmann** 2020-07-02 12:14 UTC
Labels: bug

**Comment by nburyak** [comment] 2020-09-08 20:21
- Platform: iOS 13
- Swift: Yes
- sentry-cocoa v5.2.2 installed with CocoaPods.

Hi @philipphofmann, I have a weird behavior with the similar result as described above. Here are 2 different ways of initialization:
```
        let options = Options()
        options.dsn = dsn
        options.enableAutoSessionTracking = true
        options.sessionTrackingIntervalMillis = 60000
        options.debug = true
        SentrySDK.start(options: options)

// FAILS TO INITIALIZE
// > Sentry - Error:: Invalid JSON.
// > Sentry - Error:: Event cannot be converted to JSON
```

However, the code below works perfectly fine:
```
        SentrySDK.start(options: [
            "dsn": dsn,
            "enableAutoSessionTracking": true,
            "sessionTrackingIntervalMillis": 60000,
            "debug": true
        ])
```

**Comment by bruno-garcia** [comment] 2020-09-08 22:06
@nburyak That sounds like a problem.

This issue has been resolved and was closed. Can you please create a new one?
