### ISSUE TITLE
Missing Crashlog Symbolication in 5.x.x (Ad-hoc distribution)

### ISSUE THREAD

**Issue by ostatnicky** [getsentry/sentry-cocoa#574] opened 2020-06-09 16:47 UTC
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes. Swift 5
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**5.1.4**

---

I have `redacted` words in `crashlog` using SentrySDK version 5.x.x. The app is enterprise app and distributed by ad-hoc profile. 

On the same code I run the test crash with different SentrySDK version with this crashlog result: 
- SentrySDK 5.1.4: https://sentry.io/share/issue/2e8aac5663cb4af2913822765987762c/
- SentrySDK 4.5.0: https://sentry.io/share/issue/a35d42323e034001abcebb54add16daf/

I'm expecting to have the crashlog readable in 5.x.x too.

**Steps to reproduce:**
My Build Settings:
- `Debug Information Format = DWAFT with dSYM File`
- `Enable Bitcode = NO`
- `Symbols Hidden by Default = NO`

Archived and exported **without** `Rebuild from Bitcode`.

In code call `SentrySDK.crash()` for 5.1.4 or `Client.shared?.crash()` for 4.5.0.

Uploading of dSYMs is done by `sentry-cli upload-dif` after the app building.

**Actual result:**
- Actual
Getting app calls in my app redacted. https://sentry.io/share/issue/2e8aac5663cb4af2913822765987762c/ (5.x.x)

**Expected result:**
- Result
Expecting full readable symbolicated crashlog like https://sentry.io/share/issue/a35d42323e034001abcebb54add16daf/ (4.5.0)

**Comment by philipphofmann** [comment] 2020-06-15 12:48
Hi @ostatnicky, can you please check if you also have the issue when you capture an error ` SentrySDK.capture(error: error)` or an exception `SentrySDK.capture(exception: exception, scope: scope)`?

**Comment by RuiAAPeres** [comment] 2020-07-01 11:24
> On the same code I run the test crash with different SentrySDK version with this crashlog result:

> SentrySDK 5.1.4: https://sentry.io/share/issue/2e8aac5663cb4af2913822765987762c/
> SentrySDK 4.5.0: https://sentry.io/share/issue/a35d42323e034001abcebb54add16daf/

I am curious about what's happening here. @philipphofmann do you think this might be an SDK regression?

**Comment by RuiAAPeres** [comment] 2020-07-01 15:16
@philipphofmann I tried with:

```
let exception = NSException(name: .genericException, reason: "Something bad happened", userInfo: nil)
SentrySDK.capture(exception: exception)
```

Using 5.1.6 and it looks like this: https://sentry.io/share/issue/3d6e42fe35eb406593720c1a0ae99345/

**Comment by philipphofmann** [comment] 2020-07-02 10:10
@ostatnicky I see that 5.1.4 https://sentry.io/share/issue/2e8aac5663cb4af2913822765987762c/ has no debug information for Barista.
<img width="769" alt="Screenshot 2020-07-02 at 12 06 01" src="https://user-images.githubusercontent.com/2443292/86345874-670ade00-bc5c-11ea-83b4-faff26ad66a4.png">.
It looks like something went wrong with uploading your dSYMs. Can you please check if it was uploaded correctly in Sentry in your project settings -> debug files.

**Comment by philipphofmann** [comment] 2020-07-02 10:13
> @philipphofmann I tried with:
> 
> ```
> let exception = NSException(name: .genericException, reason: "Something bad happened", userInfo: nil)
> SentrySDK.capture(exception: exception)
> ```
> 
> Using 5.1.6 and it looks like this: https://sentry.io/share/issue/3d6e42fe35eb406593720c1a0ae99345/

@RuiAAPeres the stack trace there looks fine to me although the dSYMs are missing for Sphere. Am I missing something here?

Keep in mind that stack traces for messages or errors only are attached for the current thread.

**Comment by ostatnicky** [comment] 2020-07-02 10:14
@philipphofmann In Project Settings -> Debug Files and Processing Issues there is no Missing dSYMs alert. And I'm pretty sure that I uploaded the dSYMs.

**Comment by ostatnicky** [comment] 2020-07-02 10:20
@philipphofmann But it's true that I can't find `3c16df23-221d-3eac-bf16-34c065941109` in DIFs Search...

**Comment by ostatnicky** [comment] 2020-07-02 10:20
@philipphofmann Why is Sentry not alerting me that some dSYMs are missing?

**Comment by philipphofmann** [comment] 2020-07-02 12:12
> @philipphofmann Why is Sentry not alerting me that some dSYMs are missing?

Is this a feature request 😁?

Yes, it would be handy to get an alert when dSYMS are missing. @ostatnicky is your problem solved now?

**Comment by ostatnicky** [comment] 2020-07-02 12:23
> Is this a feature request 😁?

It is. And it does. But in this case it didn't. Sentry is warning you when you're missing some dSYMs. And it warns you that you have run `curl -sL “https://sentry.io/api/0/projects/...” | bash`.

I uploaded the missing dSYMs. But I didn't get the crashlog symbolicated. And I would expect because I have `Reprocessing active` turned on.

**Comment by ostatnicky** [comment] 2020-07-02 12:30
@philipphofmann I tried the test crash again after the missing dSYMs upload. I've got the right crash log now. Ok, not sure what's wrong. It looks that dSYMs was missing but Sentry didn't warn me although it normally does. So ok, let's close this issue.

**Comment by philipphofmann** [comment] 2020-07-02 12:31
> I uploaded the missing dSYMs. But I didn't get the crashlog symbolicated. And I would expect because I have Reprocessing active turned on.

Maybe it takes a few minutes until reprocessing kicks in, but it should work.

**Comment by philipphofmann** [comment] 2020-07-02 12:32
I'm happy to close it. Reach out to us again if you have problems.

**Closed by philipphofmann** 2020-07-02 12:32 UTC

**Comment by HazAT** [comment] 2020-07-06 18:47
If you were on version `5.1.6` please update to at least `5.1.8` we fixed a bug there.
