### ISSUE TITLE
SentryCoreDataSwizzling mutated while being enumerated on coredata

### ISSUE THREAD

**Issue by libratiger** [getsentry/sentry-cocoa#3177] opened 2023-07-20 11:30 UTC
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.8.0

### Steps to Reproduce

is depends on my App, it hard to explain, but i can add more info if you can give me more detail instruction

### Expected Result

do not corrupted

### Actual Result

```
Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSCFSet: 0x600003b711a0> was mutated while being enumerated.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180437330 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001804368d4 +[__NSFastEnumerationEnumerator allocWithZone:] + 0
	3   CoreData                            0x000000018447ea5c -[NSManagedObjectContext executeFetchRequest:error:] + 2036
	4   voicememo                           0x00000001049b0c44 __42-[SentryCoreDataSwizzling swizzleCoreData]_block_invoke_3 + 108
	5   voicememo                           0x00000001049b135c -[SentryCoreDataTracker managedObjectContext:executeFetchRequest:error:originalImp:] + 656
	6   voicememo                           0x00000001049b0b1c __42-[SentryCoreDataSwizzling swizzleCoreData]_block_invoke_2 + 312
	7   CoreData                            0x000000018447c6d0 -[NSManagedObjectContext executeRequest:error:] + 312
	8   CoreData                            0x00000001843d3488 $sSo22NSManagedObjectContextC8CoreDataE5fetchySayxGSo14NSFetchRequestCyxGKSo0gH6ResultRzlF + 80
	9   voicememo                           0x00000001047b4344 $s9voicememo9RecordingC15getRecordByName8username4name2inACSgSS_SSSo22NSManagedObjectContextCtFZ + 1056
	10  voicememo                           0x0000000104761978 $s9voicememo18UploadFetchManagerC07processC9AudioTask33_96B12489ABEFE8BE8787D95B01EE8F04LLyyAA0cfG0VFy10Foundation4DataVcfU0_ + 696
	11  Combine                             0x000000019c949884 $s7Combine11SubscribersO4SinkC7receiveyAC6DemandVxF + 88
	12  Combine                             0x000000019c949ea8 $s7Combine11SubscribersO4SinkCy_xq_GAA10SubscriberA2aGP7receiveyAC6DemandV5InputQzFTW + 20
	13  Combine                             0x000000019c9b9468 $s7Combine10PublishersO5RetryV5Inner019_A59D7E0B40DB2D5EA7F12ED6C867521EBLLC7receiveyAA11SubscribersO6DemandV6OutputQzF + 396
	14  Combine                             0x000000019c9b9b70 $s7Combine10PublishersO5RetryV5Inner019_A59D7E0B40DB2D5EA7F12ED6C867521EBLLCy_x_qd__GAA10SubscriberA2aJP7receiveyAA11SubscribersO6DemandV5InputQzFTW + 20
	15  Combine                             0x000000019c96a9bc $s7Combine6FutureC7Conduit33_3AE68DE9BADC00342FC052FEBC7D3BA6LLC7fulfillyys6ResultOyxq_GF + 1180
	16  Combine                             0x000000019c96ab34 $s7Combine6FutureC7Conduit33_3AE68DE9BADC00342FC052FEBC7D3BA6LLC5offeryyxF + 160
	17  Combine                             0x000000019c96ce48 $s7Combine6FutureC7promise33_3AE68DE9BADC00342FC052FEBC7D3BA6LLyys6ResultOyxq_GFyAA11ConduitBaseCyxq_GXEfU_TA + 40
	18  Combine                             0x000000019c98b068 $s7Combine11ConduitListO7forEachyyyAA0B4BaseCyxq_GKXEKF + 212
	19  Combine                             0x000000019c969088 $s7Combine6FutureC7promise33_3AE68DE9BADC00342FC052FEBC7D3BA6LLyys6ResultOyxq_GF + 716
	20  Combine                             0x000000019c96cdf8 $s7Combine6FutureCyACyxq_Gyys6ResultOyxq_GcccfcyAGcfU_TA + 20
	21  voicememo                           0x0000000104779f80 $ss6ResultOy10Foundation4DataVs5Error_pGIegn_AGIegg_TR + 92
	22  voicememo                           0x000000010477a4dc $s9voicememo15NetworkManangerC14fetchAudioData33_A78993B8A4D4950017B5C429A08B881FLL4with7Combine6FutureCy10Foundation0F0Vs5Error_pGAJ10URLRequestV_tFyys6ResultOyALsAM_pGccfU_yALSg_So13NSURLResponseCSgsAM_pSgtYbcfU_ + 1348
	23  voicememo                           0x0000000104779bbc $s10Foundation4DataVSgSo13NSURLResponseCSgs5Error_pSgIeghggg_So6NSDataCSgAGSo7NSErrorCSgIeyBhyyy_TR + 280
	24  CFNetwork                           0x0000000183d30cf8 CFNetwork + 27896
	25  CFNetwork                           0x0000000183d4c170 _CFHTTPMessageSetResponseProxyURL + 14628
	26  libdispatch.dylib                   0x00000001064ac528 _dispatch_call_block_and_release + 24
	27  libdispatch.dylib                   0x00000001064add50 _dispatch_client_callout + 16
	28  libdispatch.dylib                   0x00000001064b6014 _dispatch_lane_serial_drain + 924
	29  libdispatch.dylib                   0x00000001064b6da4 _dispatch_lane_invoke + 480
	30  libdispatch.dylib                   0x00000001064c4b74 _dispatch_workloop_worker_thread + 1716
	31  libsystem_pthread.dylib             0x00000001b1834878 _pthread_wqthread + 284
	32  libsystem_pthread.dylib             0x00000001b183363c start_wqthread + 8
)
libc++abi: terminating due to uncaught exception of type NSException
```

### Are you willing to submit a PR?

no

**Comment by philipphofmann** [comment] 2023-07-20 13:23
I checked the stacktrace and our code and didn't yet figure out what could cause this, @libratiger. How often does this happen? It could also be that the root cause is not our code but some functional error in your app and our swizzling code simply shows up in the stacktrace. Do you get similar errors when you don't [enable performance](https://docs.sentry.io/platforms/apple/performance/)?

**Comment by armcknight** [comment] 2023-08-17 17:08
Yes, this is something in the consuming app. The sentry frames there are the pass-through tracking code that is called when the app executes a fetch request, and then the block invocation is us passing through back to the app. The block enumeration modifying a mutable set is in the application code.

I will close this issue but never hesitate to reopen or file a new one if you find an issue with Sentry code. Thanks!

**Closed by armcknight** 2023-08-17 17:08 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Community
