### ISSUE TITLE
SentryPerformanceTracker: key cannot be nil

### ISSUE THREAD

**Issue by ArchimboldiMao** [getsentry/sentry-cocoa#1367] opened 2021-10-08 09:09 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
Sentry-Cocoa 7.4.3 and 7.4.0

### Steps to Reproduce

1. When I update a view's frame, the first time is fine, the second time it throws an exception.
this.bottomView.frame = CGRectMake(0,0,30,30)

2. In file **SentryPerformanceTracker.h**
self.spans[spanId] = newSpan; 
 this line(63) will be throw an exception, Thread 1: "*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil"

### Expected Result

newSpan can't be nil. Maybe the activeSpanTracker gets the wrong object.

### Actual Result

More details are below,
```
 - (SentrySpanId *)startSpanWithName:(NSString *)name operation:(NSString *)operation{
...
id<SentrySpan> newSpan;
    if (activeSpanTracker != nil) {
        newSpan = [activeSpanTracker startChildWithOperation:operation description:name];
    }
...
}
(lldb) po activeSpanTracker
<SentrySpan: 0x105a04080>

(lldb) po operation
ui.load

(lldb) po name
viewWillLayoutSubviews

(lldb) po newSpan
 nil
```

**Comment by vincentisambart** [comment] 2021-10-12 00:43
I get the same error at the same line in `-[SentryPerformanceTracker startSpanWithName:operation:]` when using Sentry 7.4.3.

```
#5	0x000000011551e4a3 in -[SentryPerformanceTracker startSpanWithName:operation:] at [...]/Pods/Sentry/Sources/Sentry/SentryPerformanceTracker.m:63
#6	0x000000011551e5f7 in -[SentryPerformanceTracker measureSpanWithDescription:operation:inBlock:] at [...]/Pods/Sentry/Sources/Sentry/SentryPerformanceTracker.m:73
#7	0x000000011553bdc0 in __90-[SentryUIViewControllerPerformanceTracker viewControllerViewWillAppear:callbackToOrigin:]_block_invoke at [...]/Pods/Sentry/Sources/Sentry/SentryUIViewControllerPerformanceTracker.m:104
#8	0x000000011553caff in -[SentryUIViewControllerPerformanceTracker limitOverride:target:callbackToOrigin:block:] at [...]/Pods/Sentry/Sources/Sentry/SentryUIViewControllerPerformanceTracker.m:261
#9	0x000000011553bc23 in -[SentryUIViewControllerPerformanceTracker viewControllerViewWillAppear:callbackToOrigin:] at [...]/Pods/Sentry/Sources/Sentry/SentryUIViewControllerPerformanceTracker.m:91
#10	0x000000011553e90c in __58+[SentryUIViewControllerSwizziling swizzleViewWillAppear:]_block_invoke_2 at [...]/Pods/Sentry/Sources/Sentry/SentryUIViewControllerSwizziling.m:193
#11	0x00007fff24847f0e in -[UIViewController _setViewAppearState:isAnimating:] ()
#12	0x00007fff248487ce in -[UIViewController __viewWillAppear:] ()
#13	0x00007fff24743438 in -[UICollectionViewController __viewWillAppear:] ()
#14	0x00007fff248498c5 in -[UIViewController viewWillMoveToWindow:] ()
#15	0x00007fff255a5842 in -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:] ()
#16	0x00007fff255b608d in -[UIView(Internal) _addSubview:positioned:relativeTo:] ()
```
Our code calls `containerView.insertSubview(viewController.view, at: 0)` that then behind the scenes calls that `-[UIView(Internal) _addSubview:positioned:relativeTo:]`.

**Comment by vincentisambart** [comment] 2021-10-13 07:12
I got the same exception.

**Comment by philipphofmann** [comment] 2021-10-13 08:26
It seems like the `spanId` is null here.
https://github.com/getsentry/sentry-cocoa/blob/13bc7ca8b77ff0ea0980918f9c8317ab757297b8/Sources/Sentry/SentryPerformanceTracker.m#L63

**Comment by brustolin** [comment] 2021-10-18 16:49
Nice catch. I can see the problem of this issue happening because of the new weak reference, a little hard to reproduce but it is possible.
 
I think that we should created this no-op span to avoid some issues, but I believe we also should work on another solution, because the performance lifecycle will be incomplete in some cases. `SentryPerformanceTracker` should not release `SentryTracer` reference until it is really finished.

**Comment by awulf** [comment] 2021-10-19 03:22
Happening consistently in our app too, with 7.4.6.

![Screen Shot 2021-10-19 at 1 51 06 pm](https://user-images.githubusercontent.com/186606/137838477-6e077bbb-232c-48bf-9709-6f8bd24aa7d2.png)

**Comment by marandaneto** [comment] 2021-10-19 07:12
> We must use `weak` for the `tracer` for `SentrySpan` to avoid a strong reference cycle. Therefore, the `tracer` can always become `nil` at any point in time. Of course, if the code somewhere has a strong reference to the `tracer` the `tracer` of the `SentrySpan` won't be `nil`. The `SentryPerformanceTracker` should keep a reference to the `tracer` so ARC doesn't deallocate it. I would spend some more time on finding out why this is the case later. Anyway, we need to ensure that we don't crash when ARC deallocates the `tracer` of the'SentrySpan`.
> 
> My plan to solve this is to add a `NoOpSpan`, [similar to Java](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/NoOpSpan.java?rgh-link-date=2021-10-18T16%3A34%3A29Z). The `SentrySpan` would then return this `NoOpSpan` when the `tracer` is `nil`. The `SentryPerformanceTracker` wouldn't see a difference and would just continue with its regular work.
> 
> What do you guys think @bruno-garcia, @marandaneto, and @brustolin?

I believe that we should investigate why the `tracer` is becoming `nil` then.
Ensuring that the App does not crash is important but adding a `NoOpSpan` sounds like the wrong approach because then we'll get complaints that the transactions or spans are not being sent to Sentry and it's gonna be even harder to debug (no crash, no idea what's happening).
`NoOpSpan` only exists because we don't want people handling nullable transactions or spans, in the meaning of, the SDK is disabled but somebody called `startTransaction(x)`.
See https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Hub.java#L635-L641

So again, I'd rather investigate why the `tracer` is becoming `nil`, I'd be strongly against adding `NoOpSpan` for this reason.

**Comment by philipphofmann** [comment] 2021-10-19 16:52
We (@bruno-garcia, @marandaneto, @brustolin, @romtsn) decided the following on a call: The tracer being `nil` is a side effect of something not working properly with the UIViewController instrumentation. There is an extra issue to address the problem with weak, see https://github.com/getsentry/sentry-cocoa/issues/1407. 

We are not 100% sure what causes this crash, but we guess it has something to do with finishing and clearing transactions in the SentryPerformanceTracker. As a first step, we are going to end the UIViewController transaction as canceled if the transaction is still not finished in `viewDidDisappear` and `viewDidDispappear` to avoid having unfinished transactions lingering around in `SentryPerformanceTracer`. [Java](https://github.com/getsentry/sentry-java/blob/dedc0a114928e8e6017f4eb3a6eff63804e4ba1f/sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java#L296-L319) already has a similar approach. I'm going to open up a PR for this soon.

Furthermore, @brustolin and I found potential problems with the pushing and popping of the `activeSpan` in the `SentryPerformanceTracer` when having multiple UIViewControllers. We are going to investigate if there are problems to fix and add more test cases.

**Comment by philipphofmann** [comment] 2021-10-21 13:29
Might also be fixed with GH-1409 and GH-1408.

**Comment by HimanshuRstar** [comment] 2024-02-22 06:38
I am getting a similar issue in Sentry while integrating it with my React native app. 
`[__NSDictionaryM setObject:forKey:]: key cannot be nil`

Error Details
issue in finding the setObject:forKey: in Container+SentryDeepSearch.m (path - pods/sentry/sources/SentryCrash/Reporting. It might be due to the updates in the dependency of sentry.

**Comment by philipphofmann** [comment] 2024-02-23 09:39
@himujs, can you share a proper stacktrace only including Sentry frames and system library frames, please? This would help us to understand better what could be causing this. If your stacktrace doesn't include `[SentryPerformanceTracker startSpanWithName:operation:]` please open a new issue instead because it shouldn't be related to this one.

I don't see any crashes in `[SentryPerformanceTracker startSpanWithName:operation:]` in our [internal SDK crashes](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+sentryperformancetracker&referrer=issue-list&sort=user&statsPeriod=14d).

**Closed** 2024-02-28 13:38 UTC
Labels: Type: Bug, Component: Performance
