### ISSUE TITLE
Missing breadcrumbs in Watchdog Terminations

### ISSUE THREAD

**Issue by chaseklingelzen** [getsentry/sentry-cocoa#3561] opened 2024-01-16 20:08 UTC
### Platform

iOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.18.0

### Did it work on previous versions?

No

### Steps to Reproduce

1. Trigger applicationDidReceiveMemoryWarning to execute in AppDelegate 
2. Log a breadcrumb in this method. Could be anything. 
3. Force a watchdog termination error to be logged 

### Expected Result

I would expect that the breadcrumb logged in applicationDidReceiveMemoryWarning shows up in the sentry error. 

### Actual Result

The breadcrumb intermittently appears in the sentry error. 

This may not be a bug. I'm more looking for clarification here. Is it expected that watchdog termination errors may not always be able to collect all the breadcrumbs due to the nature of the error?  Also, do the breadcrumbs reported possibly contain data related to the latest launch rather than when the actual watchdog termination occurred? 

For example, in our applicationDidReceiveMemoryWarning, we log a breadcrumb with the following data:

```Swift
{
   appState: {active, inactive, etc.)
   availableAppMemory: {some amount of GB}
   // this is equivalent to what you would see in xcode debugger when looking at memory in MB
   memoryInMB: {some amount of memory in MB} 
}
```

We noticed in our breadcrumbs for a watchdog termination that memoryInMB specified something like 16 MB and the appState was "active". However, when I saw this data get logged the MBs were actually something like 130 MB and the app state was inactive. I'm wondering if this contextData is gathered on the next app launch somehow and that is why the data appears to be mismatched? 

### Are you willing to submit a PR?

Possibly

**Comment by philipphofmann** [comment] 2024-01-17 14:04
Hey @chaseklingelzen, 

So I can answer your question, can you please specify how exactly you achieve:

> 1. Trigger applicationDidReceiveMemoryWarning to execute in AppDelegate
> 2. Force a watchdog termination error to be logged

**Comment by chaseklingelzen** [comment] 2024-01-17 15:34
You got me thinking though... in order to more easily reproduce a watchdog termination, you can do the following:

1. Observe when your app gets backgrounded 
2. When your app gets backgrounded, execute the following code to spike the memory:

```Swift
static var wastedMemory = Data()
let data = Data(repeating: 0, count: 500_000_000)
/// In our case, we set up this static var in our AppDelegate
AppDelegate.wastedMemory.append(data)
```

This should lead to a lost connection to the debugger alert and ultimately end up as a watchdog termination. Happy to provide a more concrete code example if required for observing when the app gets backgrounded if required.

**Comment by philipphofmann** [comment] 2024-01-18 13:51
@chaseklingelzen, thanks for the update. The SDK should only report watchdog terminations when the app is in the foreground, and no debugger is attached; see docs https://docs.sentry.io/platforms/apple/configuration/watchdog-terminations/.

Our sample app has a way to reliably produce a watchdog termination by allocating a bunch of memory in a loop that you can also use for testing https://github.com/getsentry/sentry-cocoa/blob/42ef6baf82435c9e60f92974097657417ca4839a/Samples/iOS-Swift/iOS-Swift/ErrorsViewController.swift#L69-L85

When the OS calls `applicationDidReceiveMemoryWarning`, it could be that you already have such high memory pressure that it shortly after terminates your app, and our SDK doesn't have enough time to store the breadcrumb. Breadcrumbs before `applicationDidReceiveMemoryWarning` should be there, though.

**Comment by chaseklingelzen** [comment] 2024-01-18 16:50
Thanks for the info @philipphofmann. Great to know about that sample code! Regarding this statement:

_The SDK should only report watchdog terminations when the app is in the foreground, and no debugger is attached_

I've been able to successfully trigger watchdog terminations when the app is backgrounded and a debugger is attached. Here is a list of them that I triggered yesterday while testing:

<img width="1521" alt="Screenshot 2024-01-18 at 10 48 55 AM" src="https://github.com/getsentry/sentry-cocoa/assets/94926620/245fb9d8-4ef5-4d21-9c14-d8bc79e8d5a6">

Any idea how that could be?

**Comment by chaseklingelzen** [comment] 2024-01-18 16:52
**Re:** When the OS calls applicationDidReceiveMemoryWarning, it could be that you already have such high memory pressure that it shortly after terminates your app, and our SDK doesn't have enough time to store the breadcrumb. Breadcrumbs before applicationDidReceiveMemoryWarning should be there, though.

I was curious to understand how the breadcrumbs do get stored. Do you have any documentation / could you provide an explanation of that process here? It sounds like we may have to get smarter about how/when we capture memory used and add it to our breadcrumbs.

**Comment by philipphofmann** [comment] 2024-01-19 09:47
> I've been able to successfully trigger watchdog terminations when the app is backgrounded and a debugger is attached. Here is a list of them that I triggered yesterday while testing:

Do you maybe attach the debugger after you launched the app by using `Xcode / Debug / Attach to Process` or something similar? That's the only reason I can think of right now, how that could be possible. 

> I was curious to understand how the breadcrumbs do get stored.

Luckily, we are open source 😄. So here is the code https://github.com/getsentry/sentry-cocoa/blob/42ef6baf82435c9e60f92974097657417ca4839a/Sources/Sentry/SentryWatchdogTerminationScopeObserver.m#L102-L117

**Comment by chaseklingelzen** [comment] 2024-01-22 22:02
Sorry for the delay here @philipphofmann. I'll try and get you a video tomorrow to show you how I'm reproducing.

**Comment by chaseklingelzen** [comment] 2024-01-23 19:48
Hi @philipphofmann I've uploaded an example reproduction video [here](https://drive.google.com/file/d/1XWhhkL3-jfiznQDxEks2ED9UwbQWx4O_/view?usp=sharing) where we receive watchdog terminations in development env when a debugger is attached and the app is in the background. Note that at the start of the video there are 13 existing issues in Sentry for watchdog termination (see 2 second timestamp in video). 

After receiving the out of memory alert in xcode (see 2:29 timestamp in video), I launched the app again / waited for roughly ~ 5 minutes, and then checked Sentry where I saw a 14th watchdog termination appear (see screenshot below). 

<img width="1372" alt="Screenshot 2024-01-23 at 1 29 49 PM" src="https://github.com/getsentry/sentry-cocoa/assets/94926620/bdcbaf0a-1114-461f-844e-4041da570e22">

It does seem like I get the "using too much memory" alert in xcode directly after I backgrounded the app. So, perhaps Sentry did actually log it at the time it was being backgrounded?

 I'm still surprised that the 14th watchdog termination issue doesn't have our breadcrumb from applicationDidReceiveMemoryWarning.  Would you chalk that up to your previous statement?
 
 **Previous statement:** 
 
_When the OS calls applicationDidReceiveMemoryWarning, it could be that you already have such high memory pressure that it shortly after terminates your app, and our SDK doesn't have enough time to store the breadcrumb._

**Comment by chaseklingelzen** [comment] 2024-01-23 19:53
Perhaps a better question would be whether you have any recommendations on when to log a breadcrumb for available app memory and megabytesOfMemoryUsed? / Have you encountered others who have tried to do something similar like this in the past?

**Comment by philipphofmann** [comment] 2024-01-24 13:42
Thanks for the video, @chaseklingelzen. I tried to reproduce getting a watchdog event with a debugger attached while the app is in the background as you showed in your video, but was unable to. The logic worked as expected. Could you try again what you did in the video. Set a breakpoint here https://github.com/getsentry/sentry-cocoa/blob/59935161dffa6060e6b4be49238006d60f62954e/Sources/Sentry/SentryWatchdogTerminationLogic.m#L112

Then start the app with a debugger attached after Xcode tells you the OS killed your app cause of an OOM error, and then see if Xcode hits the breakpoint. If it does, please share the values of previousAppState and currentAppState here. A screenshot would be sufficient.

> Perhaps a better question would be whether you have any recommendations on when to log a breadcrumb for available app memory and megabytes of memory used (e.g. what the debugger tells you as you're using the app)? I'd also be curious to know if you've had other teams who have tried to implement something similar like this to get more insights?

No, not really. Ideally, we build such a solution for you. We could add a memory info breadcrumb every x seconds, and when receiving a `applicationDidReceiveMemoryWarning` we could increase the frequency.

**Comment by chaseklingelzen** [comment] 2024-01-24 15:34
@philipphofmann unfortunately, I set a breakpoint where you mentioned and reproduced the out of memory alert shown in xcode, but the breakpoint was not hit. Happy to try any further suggestions. 

I like the idea you proposed: 

_We could add a memory info breadcrumb every x seconds, and when receiving a applicationDidReceiveMemoryWarning we could increase the frequency._

Is this something I would need to submit as a feature request? If so, do you have any guidance on how I can go about submitting that?

**Comment by philipphofmann** [comment] 2024-01-25 10:53
> @philipphofmann unfortunately, I set a breakpoint where you mentioned and reproduced the out of memory alert shown in xcode, but the breakpoint was not hit. Happy to try any further suggestions.

That's weird, then, because only if you hit that breakpoint do we capture a watchog event. See https://github.com/getsentry/sentry-cocoa/blob/50bb751cfe50189673d3c0ec5b0d664659218ade/Sources/Sentry/SentryWatchdogTerminationTracker.m#L54-L86

Only the SentryWatchdogTerminationTracker creates watchdog events. If you don't have a debugger attached and restart your app from Xcode, the SDK will also report a watchdog event. That's also a reason, we also disabled reporting watchdog events for simulators.

> Is this something I would need to submit as a feature request? If so, do you have any guidance on how I can go about submitting that?

I added the idea to this issue https://github.com/getsentry/sentry-cocoa/issues/3518#issuecomment-1909911490.

**Comment by chaseklingelzen** [comment] 2024-01-25 16:43
Hi @philipphofmann, after attempting again this morning, I was able to successfully hit that breakpoint you mentioned. 
I don't know how helpful these values are going to be for previousAppState and currentAppState:

<img width="1918" alt="Screenshot 2024-01-25 at 10 41 44 AM" src="https://github.com/getsentry/sentry-cocoa/assets/94926620/372d475a-826a-4466-a64f-d450265c541e">

I have the debugger paused still. So, if you get back to me soon here I can try and get other information while I still have the breakpoint active.

**Comment by chaseklingelzen** [comment] 2024-01-25 16:46
<img width="1916" alt="Screenshot 2024-01-25 at 10 46 12 AM" src="https://github.com/getsentry/sentry-cocoa/assets/94926620/5c3293a4-fcdc-4ea7-a273-06e8cbb52253">

**Comment by chaseklingelzen** [comment] 2024-01-25 19:15
Wanted to know that an actual watchdog error did not show up in Sentry when this breakpoint was hit. I don't want to keep this issue open forever. If you have any last thoughts on the previousAppState and. currentAppState, that would be great. We can then close this and wait for that feature request to get added to the sdk.

**Comment by philipphofmann** [comment] 2024-01-26 12:33
I agree. Let's close this and wait for the feature. Thanks for all your investigations, @chaseklingelzen.

**Closed by philipphofmann** 2024-01-26 12:33 UTC
Labels: Type: Bug, Platform: Cocoa, Waiting for: Product Owner
