### ISSUE TITLE
build error on Xcode 16.0.0 Beta

### ISSUE THREAD

**Issue by alfredcc** [getsentry/sentry-cocoa#4062] opened 2024-06-13 05:37 UTC
### Description

Version:  8.28.0

<img width="1474" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/5411840/9f15d31e-7e54-4d0d-bf99-a5dc8a70316a">

No type named 'terminate_handler' in namespace 'std'
No member named 'current_exception' in namespace 'std'
No member named 'current_exception' in namespace 'std'
No member named 'set_terminate' in namespace 'std'

**Comment by philipphofmann** [comment] 2024-06-13 06:23
Thanks for reporting this, @alfredcc. This is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/4052 and https://github.com/getsentry/sentry-cocoa/issues/4050, which is already fixed and will be in the next release.

**Closed by philipphofmann** 2024-06-13 06:23 UTC
Labels: Platform: Cocoa, Waiting for: Product Owner
