### ISSUE TITLE
Don't run internal symbolication for crashes.

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#3688] opened 2024-02-29 09:15 UTC
### Description

We have removed internal symbolication for error events, but we haven't changed the behavior for crashes. The symbolication process is relatively slow, and during signal handling, we need to be as fast as possible. Additionally, in the vast majority of cases, apps are not shipped with debug symbols, rendering internal symbolication irrelevant.

Related to https://github.com/getsentry/sentry-cocoa/issues/3687#issuecomment-1970681668

**Comment by philipphofmann** [comment] 2024-02-29 13:17
@brustolin, I think that's a duplicate of https://github.com/getsentry/sentry-cocoa/issues/2996. If not, please reopen.

**Closed by philipphofmann** 2024-02-29 13:17 UTC
Labels: Platform: Cocoa
